package grpcapi

// routeRPC is the versioned route-to-RPC contract for the 99 user-facing
// HTTP routes. Browser OAuth, Runner callbacks and probes are deliberately
// omitted; every new route needs an explicit decision.
var routeRPC = map[string]string{
	"GET /api/v1/auth/methods":                                                "/eruun.v1.AccountService/GetAuthMethods",
	"POST /api/v1/auth/codes":                                                 "/eruun.v1.AccountService/SendAuthCode",
	"POST /api/v1/auth/register":                                              "/eruun.v1.AccountService/Register",
	"POST /api/v1/auth/login":                                                 "/eruun.v1.AccountService/Login",
	"POST /api/v1/auth/refresh":                                               "/eruun.v1.AccountService/Refresh",
	"POST /api/v1/auth/logout":                                                "/eruun.v1.AccountService/Logout",
	"GET /api/v1/auth/me":                                                     "/eruun.v1.AccountService/GetMe",
	"PUT /api/v1/auth/password":                                               "/eruun.v1.AccountService/ChangePassword",
	"POST /api/v1/auth/password/reset":                                        "/eruun.v1.AccountService/ResetPassword",
	"GET /api/v1/auth/identities":                                             "/eruun.v1.AccountService/ListIdentities",
	"POST /api/v1/auth/identities":                                            "/eruun.v1.AccountService/BindIdentity",
	"DELETE /api/v1/auth/identities/:identityID":                              "/eruun.v1.AccountService/UnbindIdentity",
	"GET /api/v1/workspaces":                                                  "/eruun.v1.AccountService/ListWorkspaces",
	"POST /api/v1/workspaces":                                                 "/eruun.v1.AccountService/CreateWorkspace",
	"GET /api/v1/workspaces/:workspaceID":                                     "/eruun.v1.AccountService/GetWorkspace",
	"PATCH /api/v1/workspaces/:workspaceID":                                   "/eruun.v1.AccountService/RenameWorkspace",
	"DELETE /api/v1/workspaces/:workspaceID":                                  "/eruun.v1.AccountService/DeleteWorkspace",
	"GET /api/v1/workspaces/:workspaceID/members":                             "/eruun.v1.AccountService/ListWorkspaceMembers",
	"PATCH /api/v1/workspaces/:workspaceID/members/:userID":                   "/eruun.v1.AccountService/UpdateWorkspaceMember",
	"DELETE /api/v1/workspaces/:workspaceID/members/:userID":                  "/eruun.v1.AccountService/RemoveWorkspaceMember",
	"POST /api/v1/workspaces/:workspaceID/transfer":                           "/eruun.v1.AccountService/TransferWorkspace",
	"POST /api/v1/workspaces/:workspaceID/invitations":                        "/eruun.v1.AccountService/InviteWorkspaceMember",
	"DELETE /api/v1/workspaces/:workspaceID/invitations/:invitationID":        "/eruun.v1.AccountService/RevokeWorkspaceInvitation",
	"POST /api/v1/workspace-invitations/accept":                               "/eruun.v1.AccountService/AcceptWorkspaceInvitation",
	"GET /api/v1/admin/users":                                                 "/eruun.v1.AccountService/ListAdminUsers",
	"PATCH /api/v1/admin/users/:userID":                                       "/eruun.v1.AccountService/SetAdminUserDisabled",
	"GET /api/v1/schemas/v1/canonical.json":                                   "/eruun.v1.ApplicationService/GetCanonicalJSONSchema",
	"GET /api/v1/applications":                                                "/eruun.v1.ApplicationService/ListApplications",
	"GET /api/v1/applications/templates":                                      "/eruun.v1.ApplicationService/ListTemplateApplications",
	"GET /api/v1/cronjobs":                                                    "/eruun.v1.ApplicationService/ListCronJobs",
	"GET /api/v1/scheduledjobs":                                               "/eruun.v1.ApplicationService/ListScheduledJobs",
	"POST /api/v1/applications":                                               "/eruun.v1.ApplicationService/CreateApplications",
	"POST /api/v1/applications/create-and-exec":                               "/eruun.v1.ApplicationService/CreateAndExecApplications",
	"POST /api/v1/applications/query":                                         "/eruun.v1.ApplicationService/BatchGetApplications",
	"POST /api/v1/applications/convert":                                       "/eruun.v1.ApplicationService/ConvertApplications",
	"POST /api/v1/applications/import/namespace":                              "/eruun.v1.ApplicationService/ImportNamespaceApplications",
	"POST /api/v1/applications/import/namespace/try":                          "/eruun.v1.ApplicationService/TryImportNamespaceApplications",
	"GET /api/v1/applications/:appID/workflows":                               "/eruun.v1.ApplicationService/ListApplicationWorkflows",
	"GET /api/v1/applications/:appID/spec":                                    "/eruun.v1.ApplicationService/GetApplicationSpec",
	"GET /api/v1/applications/:appID/status":                                  "/eruun.v1.ApplicationService/GetApplicationStatus",
	"GET /api/v1/applications/:appID/components":                              "/eruun.v1.ApplicationService/ListApplicationComponents",
	"GET /api/v1/applications/:appID/components/status":                       "/eruun.v1.ApplicationService/GetApplicationComponentStatus",
	"GET /api/v1/applications/:appID/components/:componentName/containers":    "/eruun.v1.ApplicationService/ListComponentContainers",
	"POST /api/v1/applications/components/status":                             "/eruun.v1.ApplicationService/BatchApplicationComponentStatus",
	"GET /api/v1/applications/:appID/components/:componentName/logs":          "/eruun.v1.ApplicationService/StreamComponentLogs",
	"POST /api/v1/applications/:appID/components/:componentName/files/export": "/eruun.v1.ApplicationService/ExportComponentFiles",
	"POST /api/v1/applications/:appID/components/:componentName/shell/exec":   "/eruun.v1.ApplicationService/ExecComponentShell",
	"POST /api/v1/applications/:appID/components/:componentName/shell/stream": "/eruun.v1.ApplicationService/StreamComponentShell",
	"DELETE /api/v1/applications/:appID":                                      "/eruun.v1.ApplicationService/DeleteApplication",
	"PUT /api/v1/applications/:appID/workflow":                                "/eruun.v1.ApplicationService/UpdateApplicationWorkflow",
	"GET /api/v1/applications/:appID/workflow/schedules":                      "/eruun.v1.ApplicationService/ListWorkflowSchedules",
	"POST /api/v1/applications/:appID/workflow/schedule":                      "/eruun.v1.ApplicationService/UpsertWorkflowSchedule",
	"DELETE /api/v1/applications/:appID/workflow/schedule/:workflowID":        "/eruun.v1.ApplicationService/DeleteWorkflowSchedule",
	"POST /api/v1/applications/:appID/resources/cleanup-plan":                 "/eruun.v1.ApplicationService/PlanApplicationResourceCleanup",
	"DELETE /api/v1/applications/:appID/resources":                            "/eruun.v1.ApplicationService/ApplyApplicationResourceCleanup",
	"POST /api/v1/applications/:appID/database-reset":                         "/eruun.v1.ApplicationService/ResetApplicationDatabases",
	"POST /api/v1/applications/:appID/log-archives":                           "/eruun.v1.ApplicationService/DownloadLogArchive",
	"POST /api/v1/applications/:appID/restart":                                "/eruun.v1.ApplicationService/RestartApplicationWorkloads",
	"POST /api/v1/applications/:appID/stop":                                   "/eruun.v1.ApplicationService/StopApplicationDeployments",
	"POST /api/v1/applications/:appID/start":                                  "/eruun.v1.ApplicationService/StartApplicationDeployments",
	"POST /api/v1/applications/:appID/workflow/exec":                          "/eruun.v1.ApplicationService/ExecApplicationWorkflow",
	"POST /api/v1/applications/:appID/workflow/cancel":                        "/eruun.v1.ApplicationService/CancelApplicationWorkflow",
	"POST /api/v1/applications/:appID/workflow/tasks/cancel-all":              "/eruun.v1.ApplicationService/CancelAllApplicationWorkflows",
	"GET /api/v1/applications/:appID/workflow/tasks":                          "/eruun.v1.ApplicationService/ListApplicationTasks",
	"POST /api/v1/workflow/tasks/:taskID/approval":                            "/eruun.v1.ApplicationService/ApproveWorkflowTask",
	"GET /api/v1/workflow/tasks/:taskID/status":                               "/eruun.v1.ApplicationService/GetWorkflowTaskStatus",
	"GET /api/v1/workflow/tasks/:taskID/stages":                               "/eruun.v1.ApplicationService/GetWorkflowTaskStages",
	"POST /api/v1/applications/:appID/version":                                "/eruun.v1.ApplicationService/UpdateApplicationVersion",
	"POST /api/v1/applications/:appID/version/diff-update":                    "/eruun.v1.ApplicationService/DiffUpdateApplicationVersion",
	"POST /api/v1/applications/:appID/version/cancel":                         "/eruun.v1.ApplicationService/CancelDelayedVersionUpdate",
	"POST /api/v1/applications/try":                                           "/eruun.v1.ApplicationService/TryApplication",
	"POST /api/v1/applications/:appID/workflow/try":                           "/eruun.v1.ApplicationService/TryWorkflow",
	"POST /api/v1/jobs":                                                       "/eruun.v1.JobsService/SubmitJob",
	"GET /api/v1/jobs/:taskID":                                                "/eruun.v1.JobsService/GetJob",
	"POST /api/v1/jobs/:taskID/cancel":                                        "/eruun.v1.JobsService/CancelJob",
	"GET /api/v1/jobs/:taskID/results":                                        "/eruun.v1.JobsService/GetJobResults",
	"GET /api/v1/jobs/:taskID/results/:artifactID/download":                   "/eruun.v1.JobsService/DownloadJobResult",
	"GET /api/v1/jobs/:taskID/deliveries/:target/download":                    "/eruun.v1.JobsService/DownloadJobDelivery",
	"POST /api/v1/jobs/:taskID/deliveries/:target/retry":                      "/eruun.v1.JobsService/RetryJobDelivery",
	"PUT /api/v1/jobs/:taskID/retention":                                      "/eruun.v1.JobsService/SetJobRetention",
	"GET /api/v1/job-storage-policy":                                          "/eruun.v1.JobsService/GetJobStoragePolicy",
	"PUT /api/v1/job-storage-policy":                                          "/eruun.v1.JobsService/SetJobStoragePolicy",
	"POST /api/v1/job-datasets":                                               "/eruun.v1.JobsService/UploadJobDataset",
	"GET /api/v1/job-datasets":                                                "/eruun.v1.JobsService/ListJobDatasets",
	"GET /api/v1/job-datasets/:datasetID":                                     "/eruun.v1.JobsService/GetJobDataset",
	"GET /api/v1/job-datasets/:datasetID/download":                            "/eruun.v1.JobsService/DownloadJobDataset",
	"GET /api/v1/settings":                                                    "/eruun.v1.SettingsService/ListSettings",
	"GET /api/v1/settings/:type":                                              "/eruun.v1.SettingsService/GetSetting",
	"POST /api/v1/settings":                                                   "/eruun.v1.SettingsService/CreateSetting",
	"PUT /api/v1/settings/:type":                                              "/eruun.v1.SettingsService/UpdateSetting",
	"DELETE /api/v1/settings/:type":                                           "/eruun.v1.SettingsService/DeleteSetting",
	"GET /api/v1/programming-languages":                                       "/eruun.v1.ProgrammingLanguagesService/ListProgrammingLanguages",
	"GET /api/v1/programming-languages/:id":                                   "/eruun.v1.ProgrammingLanguagesService/GetProgrammingLanguage",
	"POST /api/v1/programming-languages":                                      "/eruun.v1.ProgrammingLanguagesService/CreateProgrammingLanguage",
	"PUT /api/v1/programming-languages/:id":                                   "/eruun.v1.ProgrammingLanguagesService/UpdateProgrammingLanguage",
	"DELETE /api/v1/programming-languages/:id":                                "/eruun.v1.ProgrammingLanguagesService/DeleteProgrammingLanguage",
	"POST /api/v1/resource-import/jobs/scan":                                  "/eruun.v1.ResourceImportService/SubmitResourceImportScan",
	"POST /api/v1/resource-import/jobs/manage":                                "/eruun.v1.ResourceImportService/SubmitResourceImportManage",
	"GET /api/v1/resource-import/jobs/:taskID":                                "/eruun.v1.ResourceImportService/GetResourceImportJob",
}

var grpcRouteExceptions = map[string]bool{
	// Runner capability and Pod identity authentication is HTTP-only.
	"POST /api/v1/job-runners/:taskID/checkpoints/:checkpointID":         true,
	"GET /api/v1/job-runners/:taskID/checkpoints/:checkpointID":          true,
	"GET /api/v1/job-runners/:taskID/checkpoints/:checkpointID/material": true,
	"POST /api/v1/job-runners/:taskID/sandboxes":                         true,
	"GET /api/v1/job-runners/:taskID/sandboxes/:trialID":                 true,
	"POST /api/v1/job-runners/:taskID/sandboxes/:trialID/release":        true,
	"POST /api/v1/auth/oauth2/:provider/start":                           true,
	"POST /api/v1/auth/oauth2/:provider/callback":                        true,
	"GET /api/v1/job-runners/:taskID/dataset":                            true,
	"POST /api/v1/job-runners/:taskID/results":                           true,
	"POST /api/v1/job-runners/:taskID/events":                            true,
	"GET /api/v1/health":                                                 true,
	"GET /api/v1/healthz":                                                true,
	"GET /api/v1/ready":                                                  true,
	"GET /api/v1/readyz":                                                 true,
}

// RouteRPCMappings returns a defensive copy for documentation and tests.
func RouteRPCMappings() map[string]string {
	result := make(map[string]string, len(routeRPC))
	for route, method := range routeRPC {
		result[route] = method
	}
	return result
}
