apiVersion: v1
kind: Secret
metadata:
  name: eruun-mysql-secret
  namespace: eruun-system
type: Opaque
stringData:
  mysql-root-password: "__REPLACE_WITH_STRONG_PASSWORD__"
  mysql-user: eruun
  mysql-password: "__REPLACE_WITH_STRONG_PASSWORD__"
  mysql-database: eruun
---
apiVersion: v1
kind: Secret
metadata:
  name: eruun-secret
  namespace: eruun-system
type: Opaque
stringData:
  datastore-url: "eruun:__REPLACE_WITH_STRONG_PASSWORD__@tcp(eruun-mysql:3306)/eruun?charset=utf8mb4&parseTime=true&loc=Local"
  cache-password: "__REPLACE_WITH_STRONG_PASSWORD__"
