// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: eruun/v1/account.proto

package eruunv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      bool                   `protobuf:"varint,1,opt,name=password,proto3" json:"password,omitempty"`
	Email         bool                   `protobuf:"varint,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         bool                   `protobuf:"varint,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Google        bool                   `protobuf:"varint,4,opt,name=google,proto3" json:"google,omitempty"`
	Github        bool                   `protobuf:"varint,5,opt,name=github,proto3" json:"github,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMethodsResponse) Reset() {
	*x = AuthMethodsResponse{}
	mi := &file_eruun_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMethodsResponse) ProtoMessage() {}

func (x *AuthMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMethodsResponse.ProtoReflect.Descriptor instead.
func (*AuthMethodsResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *AuthMethodsResponse) GetPassword() bool {
	if x != nil {
		return x.Password
	}
	return false
}

func (x *AuthMethodsResponse) GetEmail() bool {
	if x != nil {
		return x.Email
	}
	return false
}

func (x *AuthMethodsResponse) GetPhone() bool {
	if x != nil {
		return x.Phone
	}
	return false
}

func (x *AuthMethodsResponse) GetGoogle() bool {
	if x != nil {
		return x.Google
	}
	return false
}

func (x *AuthMethodsResponse) GetGithub() bool {
	if x != nil {
		return x.Github
	}
	return false
}

type AuthCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purpose       string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Identifier    string                 `protobuf:"bytes,3,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCodeRequest) Reset() {
	*x = AuthCodeRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCodeRequest) ProtoMessage() {}

func (x *AuthCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCodeRequest.ProtoReflect.Descriptor instead.
func (*AuthCodeRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AuthCodeRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *AuthCodeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AuthCodeRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RegisterRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *RegisterRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoginRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccessToken string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType   string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn   int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	User        *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// The non-browser client must store this secret and single-flight refresh.
	RefreshToken  string `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_eruun_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SystemAdmin        bool                   `protobuf:"varint,3,opt,name=system_admin,json=systemAdmin,proto3" json:"system_admin,omitempty"`
	Disabled           bool                   `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	MustChangePassword bool                   `protobuf:"varint,5,opt,name=must_change_password,json=mustChangePassword,proto3" json:"must_change_password,omitempty"`
	CreateTime         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_eruun_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSystemAdmin() bool {
	if x != nil {
		return x.SystemAdmin
	}
	return false
}

func (x *User) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *User) GetMustChangePassword() bool {
	if x != nil {
		return x.MustChangePassword
	}
	return false
}

func (x *User) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *User) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type MeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Workspaces    []*WorkspaceAccess     `protobuf:"bytes,2,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeResponse) Reset() {
	*x = MeResponse{}
	mi := &file_eruun_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeResponse) ProtoMessage() {}

func (x *MeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeResponse.ProtoReflect.Descriptor instead.
func (*MeResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *MeResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *MeResponse) GetWorkspaces() []*WorkspaceAccess {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *ChangePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *ResetPasswordRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ResetPasswordRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ResetPasswordRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_eruun_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Identity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Identity) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Identity) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type ListIdentitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identities    []*Identity            `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIdentitiesResponse) Reset() {
	*x = ListIdentitiesResponse{}
	mi := &file_eruun_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIdentitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdentitiesResponse) ProtoMessage() {}

func (x *ListIdentitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdentitiesResponse.ProtoReflect.Descriptor instead.
func (*ListIdentitiesResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *ListIdentitiesResponse) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

type BindIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Identifier    string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindIdentityRequest) Reset() {
	*x = BindIdentityRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindIdentityRequest) ProtoMessage() {}

func (x *BindIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindIdentityRequest.ProtoReflect.Descriptor instead.
func (*BindIdentityRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *BindIdentityRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *BindIdentityRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *BindIdentityRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type IdentityIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityIDRequest) Reset() {
	*x = IdentityIDRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityIDRequest) ProtoMessage() {}

func (x *IdentityIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityIDRequest.ProtoReflect.Descriptor instead.
func (*IdentityIDRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *IdentityIDRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_eruun_v1_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{14}
}

func (x *Workspace) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workspace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workspace) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Workspace) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Workspace) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Workspace) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Workspace) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type WorkspaceAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceAccess) Reset() {
	*x = WorkspaceAccess{}
	mi := &file_eruun_v1_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceAccess) ProtoMessage() {}

func (x *WorkspaceAccess) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceAccess.ProtoReflect.Descriptor instead.
func (*WorkspaceAccess) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{15}
}

func (x *WorkspaceAccess) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *WorkspaceAccess) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*WorkspaceAccess     `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_eruun_v1_account_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{16}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*WorkspaceAccess {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type WorkspaceIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceIDRequest) Reset() {
	*x = WorkspaceIDRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceIDRequest) ProtoMessage() {}

func (x *WorkspaceIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceIDRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceIDRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{17}
}

func (x *WorkspaceIDRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type WorkspaceNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceNameRequest) Reset() {
	*x = WorkspaceNameRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceNameRequest) ProtoMessage() {}

func (x *WorkspaceNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceNameRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceNameRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{18}
}

func (x *WorkspaceNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RenameWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameWorkspaceRequest) Reset() {
	*x = RenameWorkspaceRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameWorkspaceRequest) ProtoMessage() {}

func (x *RenameWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*RenameWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{19}
}

func (x *RenameWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RenameWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkspaceMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceMember) Reset() {
	*x = WorkspaceMember{}
	mi := &file_eruun_v1_account_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMember) ProtoMessage() {}

func (x *WorkspaceMember) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMember.ProtoReflect.Descriptor instead.
func (*WorkspaceMember) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{20}
}

func (x *WorkspaceMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceMember) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkspaceMember) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkspaceMember) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *WorkspaceMember) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type ListWorkspaceMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*WorkspaceMember     `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspaceMembersResponse) Reset() {
	*x = ListWorkspaceMembersResponse{}
	mi := &file_eruun_v1_account_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspaceMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspaceMembersResponse) ProtoMessage() {}

func (x *ListWorkspaceMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspaceMembersResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspaceMembersResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{21}
}

func (x *ListWorkspaceMembersResponse) GetMembers() []*WorkspaceMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type UpdateWorkspaceMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceMemberRequest) Reset() {
	*x = UpdateWorkspaceMemberRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceMemberRequest) ProtoMessage() {}

func (x *UpdateWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateWorkspaceMemberRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateWorkspaceMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateWorkspaceMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type WorkspaceMemberIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceMemberIDRequest) Reset() {
	*x = WorkspaceMemberIDRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceMemberIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceMemberIDRequest) ProtoMessage() {}

func (x *WorkspaceMemberIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceMemberIDRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceMemberIDRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{23}
}

func (x *WorkspaceMemberIDRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceMemberIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TransferWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferWorkspaceRequest) Reset() {
	*x = TransferWorkspaceRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferWorkspaceRequest) ProtoMessage() {}

func (x *TransferWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*TransferWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{24}
}

func (x *TransferWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *TransferWorkspaceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InviteWorkspaceMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteWorkspaceMemberRequest) Reset() {
	*x = InviteWorkspaceMemberRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteWorkspaceMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteWorkspaceMemberRequest) ProtoMessage() {}

func (x *InviteWorkspaceMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteWorkspaceMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteWorkspaceMemberRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{25}
}

func (x *InviteWorkspaceMemberRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *InviteWorkspaceMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteWorkspaceMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type WorkspaceInvitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	AcceptedBy    string                 `protobuf:"bytes,6,opt,name=accepted_by,json=acceptedBy,proto3" json:"accepted_by,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInvitation) Reset() {
	*x = WorkspaceInvitation{}
	mi := &file_eruun_v1_account_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInvitation) ProtoMessage() {}

func (x *WorkspaceInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInvitation.ProtoReflect.Descriptor instead.
func (*WorkspaceInvitation) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{26}
}

func (x *WorkspaceInvitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceInvitation) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceInvitation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *WorkspaceInvitation) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WorkspaceInvitation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *WorkspaceInvitation) GetAcceptedBy() string {
	if x != nil {
		return x.AcceptedBy
	}
	return ""
}

func (x *WorkspaceInvitation) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *WorkspaceInvitation) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type WorkspaceInvitationIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	InvitationId  string                 `protobuf:"bytes,2,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInvitationIDRequest) Reset() {
	*x = WorkspaceInvitationIDRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInvitationIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInvitationIDRequest) ProtoMessage() {}

func (x *WorkspaceInvitationIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInvitationIDRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceInvitationIDRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{27}
}

func (x *WorkspaceInvitationIDRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *WorkspaceInvitationIDRequest) GetInvitationId() string {
	if x != nil {
		return x.InvitationId
	}
	return ""
}

type AcceptWorkspaceInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptWorkspaceInvitationRequest) Reset() {
	*x = AcceptWorkspaceInvitationRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptWorkspaceInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptWorkspaceInvitationRequest) ProtoMessage() {}

func (x *AcceptWorkspaceInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptWorkspaceInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptWorkspaceInvitationRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{28}
}

func (x *AcceptWorkspaceInvitationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListAdminUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersRequest) Reset() {
	*x = ListAdminUsersRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersRequest) ProtoMessage() {}

func (x *ListAdminUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersRequest.ProtoReflect.Descriptor instead.
func (*ListAdminUsersRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{29}
}

func (x *ListAdminUsersRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListAdminUsersRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type ListAdminUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminUsersResponse) Reset() {
	*x = ListAdminUsersResponse{}
	mi := &file_eruun_v1_account_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminUsersResponse) ProtoMessage() {}

func (x *ListAdminUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminUsersResponse.ProtoReflect.Descriptor instead.
func (*ListAdminUsersResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{30}
}

func (x *ListAdminUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type SetAdminUserDisabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Disabled      *bool                  `protobuf:"varint,2,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAdminUserDisabledRequest) Reset() {
	*x = SetAdminUserDisabledRequest{}
	mi := &file_eruun_v1_account_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAdminUserDisabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAdminUserDisabledRequest) ProtoMessage() {}

func (x *SetAdminUserDisabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_account_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAdminUserDisabledRequest.ProtoReflect.Descriptor instead.
func (*SetAdminUserDisabledRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_account_proto_rawDescGZIP(), []int{31}
}

func (x *SetAdminUserDisabledRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetAdminUserDisabledRequest) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

var File_eruun_v1_account_proto protoreflect.FileDescriptor

const file_eruun_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x16eruun/v1/account.proto\x12\beruun.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x01\n" +
	"\x13AuthMethodsResponse\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\bR\bpassword\x12\x14\n" +
	"\x05email\x18\x02 \x01(\bR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\bR\x05phone\x12\x16\n" +
	"\x06google\x18\x04 \x01(\bR\x06google\x12\x16\n" +
	"\x06github\x18\x05 \x01(\bR\x06github\"g\n" +
	"\x0fAuthCodeRequest\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"identifier\x18\x03 \x01(\tR\n" +
	"identifier\"\x91\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"z\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xb9\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12\"\n" +
	"\x04user\x18\x04 \x01(\v2\x0e.eruun.v1.UserR\x04user\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\"\x95\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fsystem_admin\x18\x03 \x01(\bR\vsystemAdmin\x12\x1a\n" +
	"\bdisabled\x18\x04 \x01(\bR\bdisabled\x120\n" +
	"\x14must_change_password\x18\x05 \x01(\bR\x12mustChangePassword\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"k\n" +
	"\n" +
	"MeResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.eruun.v1.UserR\x04user\x129\n" +
	"\n" +
	"workspaces\x18\x02 \x03(\v2\x19.eruun.v1.WorkspaceAccessR\n" +
	"workspaces\"3\n" +
	"\x15ChangePasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\x82\x01\n" +
	"\x14ResetPasswordRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\xca\x01\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"L\n" +
	"\x16ListIdentitiesResponse\x122\n" +
	"\n" +
	"identities\x18\x01 \x03(\v2\x12.eruun.v1.IdentityR\n" +
	"identities\"e\n" +
	"\x13BindIdentityRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"4\n" +
	"\x11IdentityIDRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\"\xf6\x01\n" +
	"\tWorkspace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"X\n" +
	"\x0fWorkspaceAccess\x121\n" +
	"\tworkspace\x18\x01 \x01(\v2\x13.eruun.v1.WorkspaceR\tworkspace\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"S\n" +
	"\x16ListWorkspacesResponse\x129\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x19.eruun.v1.WorkspaceAccessR\n" +
	"workspaces\"7\n" +
	"\x12WorkspaceIDRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"*\n" +
	"\x14WorkspaceNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"O\n" +
	"\x16RenameWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xeb\x01\n" +
	"\x0fWorkspaceMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"S\n" +
	"\x1cListWorkspaceMembersResponse\x123\n" +
	"\amembers\x18\x01 \x03(\v2\x19.eruun.v1.WorkspaceMemberR\amembers\"n\n" +
	"\x1cUpdateWorkspaceMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"V\n" +
	"\x18WorkspaceMemberIDRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"V\n" +
	"\x18TransferWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"k\n" +
	"\x1cInviteWorkspaceMemberRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xc8\x02\n" +
	"\x13WorkspaceInvitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1f\n" +
	"\vaccepted_by\x18\x06 \x01(\tR\n" +
	"acceptedBy\x12;\n" +
	"\vcreate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"f\n" +
	"\x1cWorkspaceInvitationIDRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rinvitation_id\x18\x02 \x01(\tR\finvitationId\"8\n" +
	" AcceptWorkspaceInvitationRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"i\n" +
	"\x15ListAdminUsersRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\">\n" +
	"\x16ListAdminUsersResponse\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.eruun.v1.UserR\x05users\"d\n" +
	"\x1bSetAdminUserDisabledRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\bdisabled\x18\x02 \x01(\bH\x00R\bdisabled\x88\x01\x01B\v\n" +
	"\t_disabled2\xca\x0f\n" +
	"\x0eAccountService\x12G\n" +
	"\x0eGetAuthMethods\x12\x16.google.protobuf.Empty\x1a\x1d.eruun.v1.AuthMethodsResponse\x12A\n" +
	"\fSendAuthCode\x12\x19.eruun.v1.AuthCodeRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\bRegister\x12\x19.eruun.v1.RegisterRequest\x1a\x17.eruun.v1.LoginResponse\x128\n" +
	"\x05Login\x12\x16.eruun.v1.LoginRequest\x1a\x17.eruun.v1.LoginResponse\x12<\n" +
	"\aRefresh\x12\x18.eruun.v1.RefreshRequest\x1a\x17.eruun.v1.LoginResponse\x128\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x125\n" +
	"\x05GetMe\x12\x16.google.protobuf.Empty\x1a\x14.eruun.v1.MeResponse\x12I\n" +
	"\x0eChangePassword\x12\x1f.eruun.v1.ChangePasswordRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\rResetPassword\x12\x1e.eruun.v1.ResetPasswordRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eListIdentities\x12\x16.google.protobuf.Empty\x1a .eruun.v1.ListIdentitiesResponse\x12E\n" +
	"\fBindIdentity\x12\x1d.eruun.v1.BindIdentityRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x0eUnbindIdentity\x12\x1b.eruun.v1.IdentityIDRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eListWorkspaces\x12\x16.google.protobuf.Empty\x1a .eruun.v1.ListWorkspacesResponse\x12F\n" +
	"\x0fCreateWorkspace\x12\x1e.eruun.v1.WorkspaceNameRequest\x1a\x13.eruun.v1.Workspace\x12G\n" +
	"\fGetWorkspace\x12\x1c.eruun.v1.WorkspaceIDRequest\x1a\x19.eruun.v1.WorkspaceAccess\x12K\n" +
	"\x0fRenameWorkspace\x12 .eruun.v1.RenameWorkspaceRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x0fDeleteWorkspace\x12\x1c.eruun.v1.WorkspaceIDRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x14ListWorkspaceMembers\x12\x1c.eruun.v1.WorkspaceIDRequest\x1a&.eruun.v1.ListWorkspaceMembersResponse\x12W\n" +
	"\x15UpdateWorkspaceMember\x12&.eruun.v1.UpdateWorkspaceMemberRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x15RemoveWorkspaceMember\x12\".eruun.v1.WorkspaceMemberIDRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x11TransferWorkspace\x12\".eruun.v1.TransferWorkspaceRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x15InviteWorkspaceMember\x12&.eruun.v1.InviteWorkspaceMemberRequest\x1a\x1d.eruun.v1.WorkspaceInvitation\x12[\n" +
	"\x19RevokeWorkspaceInvitation\x12&.eruun.v1.WorkspaceInvitationIDRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x19AcceptWorkspaceInvitation\x12*.eruun.v1.AcceptWorkspaceInvitationRequest\x1a\x13.eruun.v1.Workspace\x12S\n" +
	"\x0eListAdminUsers\x12\x1f.eruun.v1.ListAdminUsersRequest\x1a .eruun.v1.ListAdminUsersResponse\x12U\n" +
	"\x14SetAdminUserDisabled\x12%.eruun.v1.SetAdminUserDisabledRequest\x1a\x16.google.protobuf.EmptyBIZGgithub.com/PixelCores/Eruun/pkg/apiserver/interfaces/grpc/pb/v1;eruunv1b\x06proto3"

var (
	file_eruun_v1_account_proto_rawDescOnce sync.Once
	file_eruun_v1_account_proto_rawDescData []byte
)

func file_eruun_v1_account_proto_rawDescGZIP() []byte {
	file_eruun_v1_account_proto_rawDescOnce.Do(func() {
		file_eruun_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eruun_v1_account_proto_rawDesc), len(file_eruun_v1_account_proto_rawDesc)))
	})
	return file_eruun_v1_account_proto_rawDescData
}

var file_eruun_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_eruun_v1_account_proto_goTypes = []any{
	(*AuthMethodsResponse)(nil),              // 0: eruun.v1.AuthMethodsResponse
	(*AuthCodeRequest)(nil),                  // 1: eruun.v1.AuthCodeRequest
	(*RegisterRequest)(nil),                  // 2: eruun.v1.RegisterRequest
	(*LoginRequest)(nil),                     // 3: eruun.v1.LoginRequest
	(*RefreshRequest)(nil),                   // 4: eruun.v1.RefreshRequest
	(*LoginResponse)(nil),                    // 5: eruun.v1.LoginResponse
	(*User)(nil),                             // 6: eruun.v1.User
	(*MeResponse)(nil),                       // 7: eruun.v1.MeResponse
	(*ChangePasswordRequest)(nil),            // 8: eruun.v1.ChangePasswordRequest
	(*ResetPasswordRequest)(nil),             // 9: eruun.v1.ResetPasswordRequest
	(*Identity)(nil),                         // 10: eruun.v1.Identity
	(*ListIdentitiesResponse)(nil),           // 11: eruun.v1.ListIdentitiesResponse
	(*BindIdentityRequest)(nil),              // 12: eruun.v1.BindIdentityRequest
	(*IdentityIDRequest)(nil),                // 13: eruun.v1.IdentityIDRequest
	(*Workspace)(nil),                        // 14: eruun.v1.Workspace
	(*WorkspaceAccess)(nil),                  // 15: eruun.v1.WorkspaceAccess
	(*ListWorkspacesResponse)(nil),           // 16: eruun.v1.ListWorkspacesResponse
	(*WorkspaceIDRequest)(nil),               // 17: eruun.v1.WorkspaceIDRequest
	(*WorkspaceNameRequest)(nil),             // 18: eruun.v1.WorkspaceNameRequest
	(*RenameWorkspaceRequest)(nil),           // 19: eruun.v1.RenameWorkspaceRequest
	(*WorkspaceMember)(nil),                  // 20: eruun.v1.WorkspaceMember
	(*ListWorkspaceMembersResponse)(nil),     // 21: eruun.v1.ListWorkspaceMembersResponse
	(*UpdateWorkspaceMemberRequest)(nil),     // 22: eruun.v1.UpdateWorkspaceMemberRequest
	(*WorkspaceMemberIDRequest)(nil),         // 23: eruun.v1.WorkspaceMemberIDRequest
	(*TransferWorkspaceRequest)(nil),         // 24: eruun.v1.TransferWorkspaceRequest
	(*InviteWorkspaceMemberRequest)(nil),     // 25: eruun.v1.InviteWorkspaceMemberRequest
	(*WorkspaceInvitation)(nil),              // 26: eruun.v1.WorkspaceInvitation
	(*WorkspaceInvitationIDRequest)(nil),     // 27: eruun.v1.WorkspaceInvitationIDRequest
	(*AcceptWorkspaceInvitationRequest)(nil), // 28: eruun.v1.AcceptWorkspaceInvitationRequest
	(*ListAdminUsersRequest)(nil),            // 29: eruun.v1.ListAdminUsersRequest
	(*ListAdminUsersResponse)(nil),           // 30: eruun.v1.ListAdminUsersResponse
	(*SetAdminUserDisabledRequest)(nil),      // 31: eruun.v1.SetAdminUserDisabledRequest
	(*timestamppb.Timestamp)(nil),            // 32: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 33: google.protobuf.Empty
}
var file_eruun_v1_account_proto_depIdxs = []int32{
	6,  // 0: eruun.v1.LoginResponse.user:type_name -> eruun.v1.User
	32, // 1: eruun.v1.User.create_time:type_name -> google.protobuf.Timestamp
	32, // 2: eruun.v1.User.update_time:type_name -> google.protobuf.Timestamp
	6,  // 3: eruun.v1.MeResponse.user:type_name -> eruun.v1.User
	15, // 4: eruun.v1.MeResponse.workspaces:type_name -> eruun.v1.WorkspaceAccess
	32, // 5: eruun.v1.Identity.create_time:type_name -> google.protobuf.Timestamp
	32, // 6: eruun.v1.Identity.update_time:type_name -> google.protobuf.Timestamp
	10, // 7: eruun.v1.ListIdentitiesResponse.identities:type_name -> eruun.v1.Identity
	32, // 8: eruun.v1.Workspace.create_time:type_name -> google.protobuf.Timestamp
	32, // 9: eruun.v1.Workspace.update_time:type_name -> google.protobuf.Timestamp
	14, // 10: eruun.v1.WorkspaceAccess.workspace:type_name -> eruun.v1.Workspace
	15, // 11: eruun.v1.ListWorkspacesResponse.workspaces:type_name -> eruun.v1.WorkspaceAccess
	32, // 12: eruun.v1.WorkspaceMember.create_time:type_name -> google.protobuf.Timestamp
	32, // 13: eruun.v1.WorkspaceMember.update_time:type_name -> google.protobuf.Timestamp
	20, // 14: eruun.v1.ListWorkspaceMembersResponse.members:type_name -> eruun.v1.WorkspaceMember
	32, // 15: eruun.v1.WorkspaceInvitation.expires_at:type_name -> google.protobuf.Timestamp
	32, // 16: eruun.v1.WorkspaceInvitation.create_time:type_name -> google.protobuf.Timestamp
	32, // 17: eruun.v1.WorkspaceInvitation.update_time:type_name -> google.protobuf.Timestamp
	6,  // 18: eruun.v1.ListAdminUsersResponse.users:type_name -> eruun.v1.User
	33, // 19: eruun.v1.AccountService.GetAuthMethods:input_type -> google.protobuf.Empty
	1,  // 20: eruun.v1.AccountService.SendAuthCode:input_type -> eruun.v1.AuthCodeRequest
	2,  // 21: eruun.v1.AccountService.Register:input_type -> eruun.v1.RegisterRequest
	3,  // 22: eruun.v1.AccountService.Login:input_type -> eruun.v1.LoginRequest
	4,  // 23: eruun.v1.AccountService.Refresh:input_type -> eruun.v1.RefreshRequest
	33, // 24: eruun.v1.AccountService.Logout:input_type -> google.protobuf.Empty
	33, // 25: eruun.v1.AccountService.GetMe:input_type -> google.protobuf.Empty
	8,  // 26: eruun.v1.AccountService.ChangePassword:input_type -> eruun.v1.ChangePasswordRequest
	9,  // 27: eruun.v1.AccountService.ResetPassword:input_type -> eruun.v1.ResetPasswordRequest
	33, // 28: eruun.v1.AccountService.ListIdentities:input_type -> google.protobuf.Empty
	12, // 29: eruun.v1.AccountService.BindIdentity:input_type -> eruun.v1.BindIdentityRequest
	13, // 30: eruun.v1.AccountService.UnbindIdentity:input_type -> eruun.v1.IdentityIDRequest
	33, // 31: eruun.v1.AccountService.ListWorkspaces:input_type -> google.protobuf.Empty
	18, // 32: eruun.v1.AccountService.CreateWorkspace:input_type -> eruun.v1.WorkspaceNameRequest
	17, // 33: eruun.v1.AccountService.GetWorkspace:input_type -> eruun.v1.WorkspaceIDRequest
	19, // 34: eruun.v1.AccountService.RenameWorkspace:input_type -> eruun.v1.RenameWorkspaceRequest
	17, // 35: eruun.v1.AccountService.DeleteWorkspace:input_type -> eruun.v1.WorkspaceIDRequest
	17, // 36: eruun.v1.AccountService.ListWorkspaceMembers:input_type -> eruun.v1.WorkspaceIDRequest
	22, // 37: eruun.v1.AccountService.UpdateWorkspaceMember:input_type -> eruun.v1.UpdateWorkspaceMemberRequest
	23, // 38: eruun.v1.AccountService.RemoveWorkspaceMember:input_type -> eruun.v1.WorkspaceMemberIDRequest
	24, // 39: eruun.v1.AccountService.TransferWorkspace:input_type -> eruun.v1.TransferWorkspaceRequest
	25, // 40: eruun.v1.AccountService.InviteWorkspaceMember:input_type -> eruun.v1.InviteWorkspaceMemberRequest
	27, // 41: eruun.v1.AccountService.RevokeWorkspaceInvitation:input_type -> eruun.v1.WorkspaceInvitationIDRequest
	28, // 42: eruun.v1.AccountService.AcceptWorkspaceInvitation:input_type -> eruun.v1.AcceptWorkspaceInvitationRequest
	29, // 43: eruun.v1.AccountService.ListAdminUsers:input_type -> eruun.v1.ListAdminUsersRequest
	31, // 44: eruun.v1.AccountService.SetAdminUserDisabled:input_type -> eruun.v1.SetAdminUserDisabledRequest
	0,  // 45: eruun.v1.AccountService.GetAuthMethods:output_type -> eruun.v1.AuthMethodsResponse
	33, // 46: eruun.v1.AccountService.SendAuthCode:output_type -> google.protobuf.Empty
	5,  // 47: eruun.v1.AccountService.Register:output_type -> eruun.v1.LoginResponse
	5,  // 48: eruun.v1.AccountService.Login:output_type -> eruun.v1.LoginResponse
	5,  // 49: eruun.v1.AccountService.Refresh:output_type -> eruun.v1.LoginResponse
	33, // 50: eruun.v1.AccountService.Logout:output_type -> google.protobuf.Empty
	7,  // 51: eruun.v1.AccountService.GetMe:output_type -> eruun.v1.MeResponse
	33, // 52: eruun.v1.AccountService.ChangePassword:output_type -> google.protobuf.Empty
	33, // 53: eruun.v1.AccountService.ResetPassword:output_type -> google.protobuf.Empty
	11, // 54: eruun.v1.AccountService.ListIdentities:output_type -> eruun.v1.ListIdentitiesResponse
	33, // 55: eruun.v1.AccountService.BindIdentity:output_type -> google.protobuf.Empty
	33, // 56: eruun.v1.AccountService.UnbindIdentity:output_type -> google.protobuf.Empty
	16, // 57: eruun.v1.AccountService.ListWorkspaces:output_type -> eruun.v1.ListWorkspacesResponse
	14, // 58: eruun.v1.AccountService.CreateWorkspace:output_type -> eruun.v1.Workspace
	15, // 59: eruun.v1.AccountService.GetWorkspace:output_type -> eruun.v1.WorkspaceAccess
	33, // 60: eruun.v1.AccountService.RenameWorkspace:output_type -> google.protobuf.Empty
	33, // 61: eruun.v1.AccountService.DeleteWorkspace:output_type -> google.protobuf.Empty
	21, // 62: eruun.v1.AccountService.ListWorkspaceMembers:output_type -> eruun.v1.ListWorkspaceMembersResponse
	33, // 63: eruun.v1.AccountService.UpdateWorkspaceMember:output_type -> google.protobuf.Empty
	33, // 64: eruun.v1.AccountService.RemoveWorkspaceMember:output_type -> google.protobuf.Empty
	33, // 65: eruun.v1.AccountService.TransferWorkspace:output_type -> google.protobuf.Empty
	26, // 66: eruun.v1.AccountService.InviteWorkspaceMember:output_type -> eruun.v1.WorkspaceInvitation
	33, // 67: eruun.v1.AccountService.RevokeWorkspaceInvitation:output_type -> google.protobuf.Empty
	14, // 68: eruun.v1.AccountService.AcceptWorkspaceInvitation:output_type -> eruun.v1.Workspace
	30, // 69: eruun.v1.AccountService.ListAdminUsers:output_type -> eruun.v1.ListAdminUsersResponse
	33, // 70: eruun.v1.AccountService.SetAdminUserDisabled:output_type -> google.protobuf.Empty
	45, // [45:71] is the sub-list for method output_type
	19, // [19:45] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_eruun_v1_account_proto_init() }
func file_eruun_v1_account_proto_init() {
	if File_eruun_v1_account_proto != nil {
		return
	}
	file_eruun_v1_account_proto_msgTypes[29].OneofWrappers = []any{}
	file_eruun_v1_account_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eruun_v1_account_proto_rawDesc), len(file_eruun_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eruun_v1_account_proto_goTypes,
		DependencyIndexes: file_eruun_v1_account_proto_depIdxs,
		MessageInfos:      file_eruun_v1_account_proto_msgTypes,
	}.Build()
	File_eruun_v1_account_proto = out.File
	file_eruun_v1_account_proto_goTypes = nil
	file_eruun_v1_account_proto_depIdxs = nil
}
