// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: eruun/v1/account.proto

package eruunv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_GetAuthMethods_FullMethodName            = "/eruun.v1.AccountService/GetAuthMethods"
	AccountService_SendAuthCode_FullMethodName              = "/eruun.v1.AccountService/SendAuthCode"
	AccountService_Register_FullMethodName                  = "/eruun.v1.AccountService/Register"
	AccountService_Login_FullMethodName                     = "/eruun.v1.AccountService/Login"
	AccountService_Refresh_FullMethodName                   = "/eruun.v1.AccountService/Refresh"
	AccountService_Logout_FullMethodName                    = "/eruun.v1.AccountService/Logout"
	AccountService_GetMe_FullMethodName                     = "/eruun.v1.AccountService/GetMe"
	AccountService_ChangePassword_FullMethodName            = "/eruun.v1.AccountService/ChangePassword"
	AccountService_ResetPassword_FullMethodName             = "/eruun.v1.AccountService/ResetPassword"
	AccountService_ListIdentities_FullMethodName            = "/eruun.v1.AccountService/ListIdentities"
	AccountService_BindIdentity_FullMethodName              = "/eruun.v1.AccountService/BindIdentity"
	AccountService_UnbindIdentity_FullMethodName            = "/eruun.v1.AccountService/UnbindIdentity"
	AccountService_ListWorkspaces_FullMethodName            = "/eruun.v1.AccountService/ListWorkspaces"
	AccountService_CreateWorkspace_FullMethodName           = "/eruun.v1.AccountService/CreateWorkspace"
	AccountService_GetWorkspace_FullMethodName              = "/eruun.v1.AccountService/GetWorkspace"
	AccountService_RenameWorkspace_FullMethodName           = "/eruun.v1.AccountService/RenameWorkspace"
	AccountService_DeleteWorkspace_FullMethodName           = "/eruun.v1.AccountService/DeleteWorkspace"
	AccountService_ListWorkspaceMembers_FullMethodName      = "/eruun.v1.AccountService/ListWorkspaceMembers"
	AccountService_UpdateWorkspaceMember_FullMethodName     = "/eruun.v1.AccountService/UpdateWorkspaceMember"
	AccountService_RemoveWorkspaceMember_FullMethodName     = "/eruun.v1.AccountService/RemoveWorkspaceMember"
	AccountService_TransferWorkspace_FullMethodName         = "/eruun.v1.AccountService/TransferWorkspace"
	AccountService_InviteWorkspaceMember_FullMethodName     = "/eruun.v1.AccountService/InviteWorkspaceMember"
	AccountService_RevokeWorkspaceInvitation_FullMethodName = "/eruun.v1.AccountService/RevokeWorkspaceInvitation"
	AccountService_AcceptWorkspaceInvitation_FullMethodName = "/eruun.v1.AccountService/AcceptWorkspaceInvitation"
	AccountService_ListAdminUsers_FullMethodName            = "/eruun.v1.AccountService/ListAdminUsers"
	AccountService_SetAdminUserDisabled_FullMethodName      = "/eruun.v1.AccountService/SetAdminUserDisabled"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountService exposes the non-browser account and workspace operations.
// OAuth browser start/callback remain HTTP-only.
type AccountServiceClient interface {
	GetAuthMethods(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AuthMethodsResponse, error)
	SendAuthCode(ctx context.Context, in *AuthCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetMe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MeResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListIdentities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListIdentitiesResponse, error)
	BindIdentity(ctx context.Context, in *BindIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnbindIdentity(ctx context.Context, in *IdentityIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListWorkspaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWorkspacesResponse, error)
	CreateWorkspace(ctx context.Context, in *WorkspaceNameRequest, opts ...grpc.CallOption) (*Workspace, error)
	GetWorkspace(ctx context.Context, in *WorkspaceIDRequest, opts ...grpc.CallOption) (*WorkspaceAccess, error)
	RenameWorkspace(ctx context.Context, in *RenameWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteWorkspace(ctx context.Context, in *WorkspaceIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListWorkspaceMembers(ctx context.Context, in *WorkspaceIDRequest, opts ...grpc.CallOption) (*ListWorkspaceMembersResponse, error)
	UpdateWorkspaceMember(ctx context.Context, in *UpdateWorkspaceMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveWorkspaceMember(ctx context.Context, in *WorkspaceMemberIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	TransferWorkspace(ctx context.Context, in *TransferWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	InviteWorkspaceMember(ctx context.Context, in *InviteWorkspaceMemberRequest, opts ...grpc.CallOption) (*WorkspaceInvitation, error)
	RevokeWorkspaceInvitation(ctx context.Context, in *WorkspaceInvitationIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AcceptWorkspaceInvitation(ctx context.Context, in *AcceptWorkspaceInvitationRequest, opts ...grpc.CallOption) (*Workspace, error)
	ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error)
	SetAdminUserDisabled(ctx context.Context, in *SetAdminUserDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetAuthMethods(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AuthMethodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthMethodsResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAuthMethods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SendAuthCode(ctx context.Context, in *AuthCodeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_SendAuthCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AccountService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AccountService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AccountService_Refresh_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Logout(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetMe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MeResponse)
	err := c.cc.Invoke(ctx, AccountService_GetMe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListIdentities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentitiesResponse)
	err := c.cc.Invoke(ctx, AccountService_ListIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) BindIdentity(ctx context.Context, in *BindIdentityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_BindIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UnbindIdentity(ctx context.Context, in *IdentityIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_UnbindIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListWorkspaces(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListWorkspacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspacesResponse)
	err := c.cc.Invoke(ctx, AccountService_ListWorkspaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateWorkspace(ctx context.Context, in *WorkspaceNameRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, AccountService_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetWorkspace(ctx context.Context, in *WorkspaceIDRequest, opts ...grpc.CallOption) (*WorkspaceAccess, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceAccess)
	err := c.cc.Invoke(ctx, AccountService_GetWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RenameWorkspace(ctx context.Context, in *RenameWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_RenameWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteWorkspace(ctx context.Context, in *WorkspaceIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_DeleteWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListWorkspaceMembers(ctx context.Context, in *WorkspaceIDRequest, opts ...grpc.CallOption) (*ListWorkspaceMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkspaceMembersResponse)
	err := c.cc.Invoke(ctx, AccountService_ListWorkspaceMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateWorkspaceMember(ctx context.Context, in *UpdateWorkspaceMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_UpdateWorkspaceMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RemoveWorkspaceMember(ctx context.Context, in *WorkspaceMemberIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_RemoveWorkspaceMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) TransferWorkspace(ctx context.Context, in *TransferWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_TransferWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) InviteWorkspaceMember(ctx context.Context, in *InviteWorkspaceMemberRequest, opts ...grpc.CallOption) (*WorkspaceInvitation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkspaceInvitation)
	err := c.cc.Invoke(ctx, AccountService_InviteWorkspaceMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RevokeWorkspaceInvitation(ctx context.Context, in *WorkspaceInvitationIDRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_RevokeWorkspaceInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AcceptWorkspaceInvitation(ctx context.Context, in *AcceptWorkspaceInvitationRequest, opts ...grpc.CallOption) (*Workspace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workspace)
	err := c.cc.Invoke(ctx, AccountService_AcceptWorkspaceInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListAdminUsers(ctx context.Context, in *ListAdminUsersRequest, opts ...grpc.CallOption) (*ListAdminUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminUsersResponse)
	err := c.cc.Invoke(ctx, AccountService_ListAdminUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SetAdminUserDisabled(ctx context.Context, in *SetAdminUserDisabledRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AccountService_SetAdminUserDisabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// AccountService exposes the non-browser account and workspace operations.
// OAuth browser start/callback remain HTTP-only.
type AccountServiceServer interface {
	GetAuthMethods(context.Context, *emptypb.Empty) (*AuthMethodsResponse, error)
	SendAuthCode(context.Context, *AuthCodeRequest) (*emptypb.Empty, error)
	Register(context.Context, *RegisterRequest) (*LoginResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Refresh(context.Context, *RefreshRequest) (*LoginResponse, error)
	Logout(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetMe(context.Context, *emptypb.Empty) (*MeResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*emptypb.Empty, error)
	ListIdentities(context.Context, *emptypb.Empty) (*ListIdentitiesResponse, error)
	BindIdentity(context.Context, *BindIdentityRequest) (*emptypb.Empty, error)
	UnbindIdentity(context.Context, *IdentityIDRequest) (*emptypb.Empty, error)
	ListWorkspaces(context.Context, *emptypb.Empty) (*ListWorkspacesResponse, error)
	CreateWorkspace(context.Context, *WorkspaceNameRequest) (*Workspace, error)
	GetWorkspace(context.Context, *WorkspaceIDRequest) (*WorkspaceAccess, error)
	RenameWorkspace(context.Context, *RenameWorkspaceRequest) (*emptypb.Empty, error)
	DeleteWorkspace(context.Context, *WorkspaceIDRequest) (*emptypb.Empty, error)
	ListWorkspaceMembers(context.Context, *WorkspaceIDRequest) (*ListWorkspaceMembersResponse, error)
	UpdateWorkspaceMember(context.Context, *UpdateWorkspaceMemberRequest) (*emptypb.Empty, error)
	RemoveWorkspaceMember(context.Context, *WorkspaceMemberIDRequest) (*emptypb.Empty, error)
	TransferWorkspace(context.Context, *TransferWorkspaceRequest) (*emptypb.Empty, error)
	InviteWorkspaceMember(context.Context, *InviteWorkspaceMemberRequest) (*WorkspaceInvitation, error)
	RevokeWorkspaceInvitation(context.Context, *WorkspaceInvitationIDRequest) (*emptypb.Empty, error)
	AcceptWorkspaceInvitation(context.Context, *AcceptWorkspaceInvitationRequest) (*Workspace, error)
	ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error)
	SetAdminUserDisabled(context.Context, *SetAdminUserDisabledRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) GetAuthMethods(context.Context, *emptypb.Empty) (*AuthMethodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthMethods not implemented")
}
func (UnimplementedAccountServiceServer) SendAuthCode(context.Context, *AuthCodeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAuthCode not implemented")
}
func (UnimplementedAccountServiceServer) Register(context.Context, *RegisterRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAccountServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAccountServiceServer) Refresh(context.Context, *RefreshRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Refresh not implemented")
}
func (UnimplementedAccountServiceServer) Logout(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAccountServiceServer) GetMe(context.Context, *emptypb.Empty) (*MeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMe not implemented")
}
func (UnimplementedAccountServiceServer) ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedAccountServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedAccountServiceServer) ListIdentities(context.Context, *emptypb.Empty) (*ListIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentities not implemented")
}
func (UnimplementedAccountServiceServer) BindIdentity(context.Context, *BindIdentityRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BindIdentity not implemented")
}
func (UnimplementedAccountServiceServer) UnbindIdentity(context.Context, *IdentityIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindIdentity not implemented")
}
func (UnimplementedAccountServiceServer) ListWorkspaces(context.Context, *emptypb.Empty) (*ListWorkspacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkspaces not implemented")
}
func (UnimplementedAccountServiceServer) CreateWorkspace(context.Context, *WorkspaceNameRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedAccountServiceServer) GetWorkspace(context.Context, *WorkspaceIDRequest) (*WorkspaceAccess, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkspace not implemented")
}
func (UnimplementedAccountServiceServer) RenameWorkspace(context.Context, *RenameWorkspaceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameWorkspace not implemented")
}
func (UnimplementedAccountServiceServer) DeleteWorkspace(context.Context, *WorkspaceIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkspace not implemented")
}
func (UnimplementedAccountServiceServer) ListWorkspaceMembers(context.Context, *WorkspaceIDRequest) (*ListWorkspaceMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkspaceMembers not implemented")
}
func (UnimplementedAccountServiceServer) UpdateWorkspaceMember(context.Context, *UpdateWorkspaceMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkspaceMember not implemented")
}
func (UnimplementedAccountServiceServer) RemoveWorkspaceMember(context.Context, *WorkspaceMemberIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWorkspaceMember not implemented")
}
func (UnimplementedAccountServiceServer) TransferWorkspace(context.Context, *TransferWorkspaceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferWorkspace not implemented")
}
func (UnimplementedAccountServiceServer) InviteWorkspaceMember(context.Context, *InviteWorkspaceMemberRequest) (*WorkspaceInvitation, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteWorkspaceMember not implemented")
}
func (UnimplementedAccountServiceServer) RevokeWorkspaceInvitation(context.Context, *WorkspaceInvitationIDRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeWorkspaceInvitation not implemented")
}
func (UnimplementedAccountServiceServer) AcceptWorkspaceInvitation(context.Context, *AcceptWorkspaceInvitationRequest) (*Workspace, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptWorkspaceInvitation not implemented")
}
func (UnimplementedAccountServiceServer) ListAdminUsers(context.Context, *ListAdminUsersRequest) (*ListAdminUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminUsers not implemented")
}
func (UnimplementedAccountServiceServer) SetAdminUserDisabled(context.Context, *SetAdminUserDisabledRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAdminUserDisabled not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_GetAuthMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAuthMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAuthMethods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAuthMethods(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SendAuthCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SendAuthCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SendAuthCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SendAuthCode(ctx, req.(*AuthCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Refresh_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Refresh(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Refresh_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Refresh(ctx, req.(*RefreshRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Logout(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetMe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetMe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetMe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetMe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListIdentities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_BindIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).BindIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_BindIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).BindIdentity(ctx, req.(*BindIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UnbindIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UnbindIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UnbindIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UnbindIdentity(ctx, req.(*IdentityIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListWorkspaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListWorkspaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListWorkspaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListWorkspaces(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateWorkspace(ctx, req.(*WorkspaceNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetWorkspace(ctx, req.(*WorkspaceIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RenameWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RenameWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_RenameWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RenameWorkspace(ctx, req.(*RenameWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeleteWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteWorkspace(ctx, req.(*WorkspaceIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListWorkspaceMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListWorkspaceMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListWorkspaceMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListWorkspaceMembers(ctx, req.(*WorkspaceIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateWorkspaceMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkspaceMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateWorkspaceMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateWorkspaceMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateWorkspaceMember(ctx, req.(*UpdateWorkspaceMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RemoveWorkspaceMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceMemberIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RemoveWorkspaceMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_RemoveWorkspaceMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RemoveWorkspaceMember(ctx, req.(*WorkspaceMemberIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_TransferWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).TransferWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_TransferWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).TransferWorkspace(ctx, req.(*TransferWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_InviteWorkspaceMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteWorkspaceMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).InviteWorkspaceMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_InviteWorkspaceMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).InviteWorkspaceMember(ctx, req.(*InviteWorkspaceMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RevokeWorkspaceInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceInvitationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RevokeWorkspaceInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_RevokeWorkspaceInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RevokeWorkspaceInvitation(ctx, req.(*WorkspaceInvitationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AcceptWorkspaceInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptWorkspaceInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AcceptWorkspaceInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AcceptWorkspaceInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AcceptWorkspaceInvitation(ctx, req.(*AcceptWorkspaceInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListAdminUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListAdminUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListAdminUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListAdminUsers(ctx, req.(*ListAdminUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SetAdminUserDisabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdminUserDisabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SetAdminUserDisabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SetAdminUserDisabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SetAdminUserDisabled(ctx, req.(*SetAdminUserDisabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eruun.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthMethods",
			Handler:    _AccountService_GetAuthMethods_Handler,
		},
		{
			MethodName: "SendAuthCode",
			Handler:    _AccountService_SendAuthCode_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AccountService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _AccountService_Login_Handler,
		},
		{
			MethodName: "Refresh",
			Handler:    _AccountService_Refresh_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AccountService_Logout_Handler,
		},
		{
			MethodName: "GetMe",
			Handler:    _AccountService_GetMe_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _AccountService_ChangePassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AccountService_ResetPassword_Handler,
		},
		{
			MethodName: "ListIdentities",
			Handler:    _AccountService_ListIdentities_Handler,
		},
		{
			MethodName: "BindIdentity",
			Handler:    _AccountService_BindIdentity_Handler,
		},
		{
			MethodName: "UnbindIdentity",
			Handler:    _AccountService_UnbindIdentity_Handler,
		},
		{
			MethodName: "ListWorkspaces",
			Handler:    _AccountService_ListWorkspaces_Handler,
		},
		{
			MethodName: "CreateWorkspace",
			Handler:    _AccountService_CreateWorkspace_Handler,
		},
		{
			MethodName: "GetWorkspace",
			Handler:    _AccountService_GetWorkspace_Handler,
		},
		{
			MethodName: "RenameWorkspace",
			Handler:    _AccountService_RenameWorkspace_Handler,
		},
		{
			MethodName: "DeleteWorkspace",
			Handler:    _AccountService_DeleteWorkspace_Handler,
		},
		{
			MethodName: "ListWorkspaceMembers",
			Handler:    _AccountService_ListWorkspaceMembers_Handler,
		},
		{
			MethodName: "UpdateWorkspaceMember",
			Handler:    _AccountService_UpdateWorkspaceMember_Handler,
		},
		{
			MethodName: "RemoveWorkspaceMember",
			Handler:    _AccountService_RemoveWorkspaceMember_Handler,
		},
		{
			MethodName: "TransferWorkspace",
			Handler:    _AccountService_TransferWorkspace_Handler,
		},
		{
			MethodName: "InviteWorkspaceMember",
			Handler:    _AccountService_InviteWorkspaceMember_Handler,
		},
		{
			MethodName: "RevokeWorkspaceInvitation",
			Handler:    _AccountService_RevokeWorkspaceInvitation_Handler,
		},
		{
			MethodName: "AcceptWorkspaceInvitation",
			Handler:    _AccountService_AcceptWorkspaceInvitation_Handler,
		},
		{
			MethodName: "ListAdminUsers",
			Handler:    _AccountService_ListAdminUsers_Handler,
		},
		{
			MethodName: "SetAdminUserDisabled",
			Handler:    _AccountService_SetAdminUserDisabled_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eruun/v1/account.proto",
}
