// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: eruun/v1/administration.proto

package eruunv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingsService_ListSettings_FullMethodName  = "/eruun.v1.SettingsService/ListSettings"
	SettingsService_GetSetting_FullMethodName    = "/eruun.v1.SettingsService/GetSetting"
	SettingsService_CreateSetting_FullMethodName = "/eruun.v1.SettingsService/CreateSetting"
	SettingsService_UpdateSetting_FullMethodName = "/eruun.v1.SettingsService/UpdateSetting"
	SettingsService_DeleteSetting_FullMethodName = "/eruun.v1.SettingsService/DeleteSetting"
)

// SettingsServiceClient is the client API for SettingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingsServiceClient interface {
	ListSettings(ctx context.Context, in *ListSettingsRequest, opts ...grpc.CallOption) (*ListSettingsResponse, error)
	GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*SystemSetting, error)
	CreateSetting(ctx context.Context, in *CreateSettingRequest, opts ...grpc.CallOption) (*SystemSetting, error)
	UpdateSetting(ctx context.Context, in *UpdateSettingRequest, opts ...grpc.CallOption) (*SystemSetting, error)
	DeleteSetting(ctx context.Context, in *DeleteSettingRequest, opts ...grpc.CallOption) (*DeleteSettingResponse, error)
}

type settingsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsServiceClient(cc grpc.ClientConnInterface) SettingsServiceClient {
	return &settingsServiceClient{cc}
}

func (c *settingsServiceClient) ListSettings(ctx context.Context, in *ListSettingsRequest, opts ...grpc.CallOption) (*ListSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSettingsResponse)
	err := c.cc.Invoke(ctx, SettingsService_ListSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) GetSetting(ctx context.Context, in *GetSettingRequest, opts ...grpc.CallOption) (*SystemSetting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemSetting)
	err := c.cc.Invoke(ctx, SettingsService_GetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) CreateSetting(ctx context.Context, in *CreateSettingRequest, opts ...grpc.CallOption) (*SystemSetting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemSetting)
	err := c.cc.Invoke(ctx, SettingsService_CreateSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) UpdateSetting(ctx context.Context, in *UpdateSettingRequest, opts ...grpc.CallOption) (*SystemSetting, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemSetting)
	err := c.cc.Invoke(ctx, SettingsService_UpdateSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsServiceClient) DeleteSetting(ctx context.Context, in *DeleteSettingRequest, opts ...grpc.CallOption) (*DeleteSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSettingResponse)
	err := c.cc.Invoke(ctx, SettingsService_DeleteSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsServiceServer is the server API for SettingsService service.
// All implementations must embed UnimplementedSettingsServiceServer
// for forward compatibility.
type SettingsServiceServer interface {
	ListSettings(context.Context, *ListSettingsRequest) (*ListSettingsResponse, error)
	GetSetting(context.Context, *GetSettingRequest) (*SystemSetting, error)
	CreateSetting(context.Context, *CreateSettingRequest) (*SystemSetting, error)
	UpdateSetting(context.Context, *UpdateSettingRequest) (*SystemSetting, error)
	DeleteSetting(context.Context, *DeleteSettingRequest) (*DeleteSettingResponse, error)
	mustEmbedUnimplementedSettingsServiceServer()
}

// UnimplementedSettingsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingsServiceServer struct{}

func (UnimplementedSettingsServiceServer) ListSettings(context.Context, *ListSettingsRequest) (*ListSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSettings not implemented")
}
func (UnimplementedSettingsServiceServer) GetSetting(context.Context, *GetSettingRequest) (*SystemSetting, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSetting not implemented")
}
func (UnimplementedSettingsServiceServer) CreateSetting(context.Context, *CreateSettingRequest) (*SystemSetting, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSetting not implemented")
}
func (UnimplementedSettingsServiceServer) UpdateSetting(context.Context, *UpdateSettingRequest) (*SystemSetting, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSetting not implemented")
}
func (UnimplementedSettingsServiceServer) DeleteSetting(context.Context, *DeleteSettingRequest) (*DeleteSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSetting not implemented")
}
func (UnimplementedSettingsServiceServer) mustEmbedUnimplementedSettingsServiceServer() {}
func (UnimplementedSettingsServiceServer) testEmbeddedByValue()                         {}

// UnsafeSettingsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingsServiceServer will
// result in compilation errors.
type UnsafeSettingsServiceServer interface {
	mustEmbedUnimplementedSettingsServiceServer()
}

func RegisterSettingsServiceServer(s grpc.ServiceRegistrar, srv SettingsServiceServer) {
	// If the following call panics, it indicates UnimplementedSettingsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingsService_ServiceDesc, srv)
}

func _SettingsService_ListSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).ListSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_ListSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).ListSettings(ctx, req.(*ListSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_GetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).GetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_GetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).GetSetting(ctx, req.(*GetSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_CreateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).CreateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_CreateSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).CreateSetting(ctx, req.(*CreateSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_UpdateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).UpdateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_UpdateSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).UpdateSetting(ctx, req.(*UpdateSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsService_DeleteSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServiceServer).DeleteSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsService_DeleteSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServiceServer).DeleteSetting(ctx, req.(*DeleteSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingsService_ServiceDesc is the grpc.ServiceDesc for SettingsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eruun.v1.SettingsService",
	HandlerType: (*SettingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSettings",
			Handler:    _SettingsService_ListSettings_Handler,
		},
		{
			MethodName: "GetSetting",
			Handler:    _SettingsService_GetSetting_Handler,
		},
		{
			MethodName: "CreateSetting",
			Handler:    _SettingsService_CreateSetting_Handler,
		},
		{
			MethodName: "UpdateSetting",
			Handler:    _SettingsService_UpdateSetting_Handler,
		},
		{
			MethodName: "DeleteSetting",
			Handler:    _SettingsService_DeleteSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eruun/v1/administration.proto",
}

const (
	ProgrammingLanguagesService_ListProgrammingLanguages_FullMethodName  = "/eruun.v1.ProgrammingLanguagesService/ListProgrammingLanguages"
	ProgrammingLanguagesService_GetProgrammingLanguage_FullMethodName    = "/eruun.v1.ProgrammingLanguagesService/GetProgrammingLanguage"
	ProgrammingLanguagesService_CreateProgrammingLanguage_FullMethodName = "/eruun.v1.ProgrammingLanguagesService/CreateProgrammingLanguage"
	ProgrammingLanguagesService_UpdateProgrammingLanguage_FullMethodName = "/eruun.v1.ProgrammingLanguagesService/UpdateProgrammingLanguage"
	ProgrammingLanguagesService_DeleteProgrammingLanguage_FullMethodName = "/eruun.v1.ProgrammingLanguagesService/DeleteProgrammingLanguage"
)

// ProgrammingLanguagesServiceClient is the client API for ProgrammingLanguagesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgrammingLanguagesServiceClient interface {
	ListProgrammingLanguages(ctx context.Context, in *ListProgrammingLanguagesRequest, opts ...grpc.CallOption) (*ListProgrammingLanguagesResponse, error)
	GetProgrammingLanguage(ctx context.Context, in *ProgrammingLanguageIDRequest, opts ...grpc.CallOption) (*ProgrammingLanguage, error)
	CreateProgrammingLanguage(ctx context.Context, in *CreateProgrammingLanguageRequest, opts ...grpc.CallOption) (*ProgrammingLanguage, error)
	UpdateProgrammingLanguage(ctx context.Context, in *UpdateProgrammingLanguageRequest, opts ...grpc.CallOption) (*ProgrammingLanguage, error)
	DeleteProgrammingLanguage(ctx context.Context, in *ProgrammingLanguageIDRequest, opts ...grpc.CallOption) (*DeleteProgrammingLanguageResponse, error)
}

type programmingLanguagesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProgrammingLanguagesServiceClient(cc grpc.ClientConnInterface) ProgrammingLanguagesServiceClient {
	return &programmingLanguagesServiceClient{cc}
}

func (c *programmingLanguagesServiceClient) ListProgrammingLanguages(ctx context.Context, in *ListProgrammingLanguagesRequest, opts ...grpc.CallOption) (*ListProgrammingLanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProgrammingLanguagesResponse)
	err := c.cc.Invoke(ctx, ProgrammingLanguagesService_ListProgrammingLanguages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programmingLanguagesServiceClient) GetProgrammingLanguage(ctx context.Context, in *ProgrammingLanguageIDRequest, opts ...grpc.CallOption) (*ProgrammingLanguage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgrammingLanguage)
	err := c.cc.Invoke(ctx, ProgrammingLanguagesService_GetProgrammingLanguage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programmingLanguagesServiceClient) CreateProgrammingLanguage(ctx context.Context, in *CreateProgrammingLanguageRequest, opts ...grpc.CallOption) (*ProgrammingLanguage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgrammingLanguage)
	err := c.cc.Invoke(ctx, ProgrammingLanguagesService_CreateProgrammingLanguage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programmingLanguagesServiceClient) UpdateProgrammingLanguage(ctx context.Context, in *UpdateProgrammingLanguageRequest, opts ...grpc.CallOption) (*ProgrammingLanguage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgrammingLanguage)
	err := c.cc.Invoke(ctx, ProgrammingLanguagesService_UpdateProgrammingLanguage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programmingLanguagesServiceClient) DeleteProgrammingLanguage(ctx context.Context, in *ProgrammingLanguageIDRequest, opts ...grpc.CallOption) (*DeleteProgrammingLanguageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProgrammingLanguageResponse)
	err := c.cc.Invoke(ctx, ProgrammingLanguagesService_DeleteProgrammingLanguage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgrammingLanguagesServiceServer is the server API for ProgrammingLanguagesService service.
// All implementations must embed UnimplementedProgrammingLanguagesServiceServer
// for forward compatibility.
type ProgrammingLanguagesServiceServer interface {
	ListProgrammingLanguages(context.Context, *ListProgrammingLanguagesRequest) (*ListProgrammingLanguagesResponse, error)
	GetProgrammingLanguage(context.Context, *ProgrammingLanguageIDRequest) (*ProgrammingLanguage, error)
	CreateProgrammingLanguage(context.Context, *CreateProgrammingLanguageRequest) (*ProgrammingLanguage, error)
	UpdateProgrammingLanguage(context.Context, *UpdateProgrammingLanguageRequest) (*ProgrammingLanguage, error)
	DeleteProgrammingLanguage(context.Context, *ProgrammingLanguageIDRequest) (*DeleteProgrammingLanguageResponse, error)
	mustEmbedUnimplementedProgrammingLanguagesServiceServer()
}

// UnimplementedProgrammingLanguagesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgrammingLanguagesServiceServer struct{}

func (UnimplementedProgrammingLanguagesServiceServer) ListProgrammingLanguages(context.Context, *ListProgrammingLanguagesRequest) (*ListProgrammingLanguagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProgrammingLanguages not implemented")
}
func (UnimplementedProgrammingLanguagesServiceServer) GetProgrammingLanguage(context.Context, *ProgrammingLanguageIDRequest) (*ProgrammingLanguage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgrammingLanguage not implemented")
}
func (UnimplementedProgrammingLanguagesServiceServer) CreateProgrammingLanguage(context.Context, *CreateProgrammingLanguageRequest) (*ProgrammingLanguage, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProgrammingLanguage not implemented")
}
func (UnimplementedProgrammingLanguagesServiceServer) UpdateProgrammingLanguage(context.Context, *UpdateProgrammingLanguageRequest) (*ProgrammingLanguage, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProgrammingLanguage not implemented")
}
func (UnimplementedProgrammingLanguagesServiceServer) DeleteProgrammingLanguage(context.Context, *ProgrammingLanguageIDRequest) (*DeleteProgrammingLanguageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProgrammingLanguage not implemented")
}
func (UnimplementedProgrammingLanguagesServiceServer) mustEmbedUnimplementedProgrammingLanguagesServiceServer() {
}
func (UnimplementedProgrammingLanguagesServiceServer) testEmbeddedByValue() {}

// UnsafeProgrammingLanguagesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgrammingLanguagesServiceServer will
// result in compilation errors.
type UnsafeProgrammingLanguagesServiceServer interface {
	mustEmbedUnimplementedProgrammingLanguagesServiceServer()
}

func RegisterProgrammingLanguagesServiceServer(s grpc.ServiceRegistrar, srv ProgrammingLanguagesServiceServer) {
	// If the following call panics, it indicates UnimplementedProgrammingLanguagesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgrammingLanguagesService_ServiceDesc, srv)
}

func _ProgrammingLanguagesService_ListProgrammingLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProgrammingLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgrammingLanguagesServiceServer).ListProgrammingLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgrammingLanguagesService_ListProgrammingLanguages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgrammingLanguagesServiceServer).ListProgrammingLanguages(ctx, req.(*ListProgrammingLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgrammingLanguagesService_GetProgrammingLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgrammingLanguageIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgrammingLanguagesServiceServer).GetProgrammingLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgrammingLanguagesService_GetProgrammingLanguage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgrammingLanguagesServiceServer).GetProgrammingLanguage(ctx, req.(*ProgrammingLanguageIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgrammingLanguagesService_CreateProgrammingLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProgrammingLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgrammingLanguagesServiceServer).CreateProgrammingLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgrammingLanguagesService_CreateProgrammingLanguage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgrammingLanguagesServiceServer).CreateProgrammingLanguage(ctx, req.(*CreateProgrammingLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgrammingLanguagesService_UpdateProgrammingLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgrammingLanguageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgrammingLanguagesServiceServer).UpdateProgrammingLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgrammingLanguagesService_UpdateProgrammingLanguage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgrammingLanguagesServiceServer).UpdateProgrammingLanguage(ctx, req.(*UpdateProgrammingLanguageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgrammingLanguagesService_DeleteProgrammingLanguage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgrammingLanguageIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgrammingLanguagesServiceServer).DeleteProgrammingLanguage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgrammingLanguagesService_DeleteProgrammingLanguage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgrammingLanguagesServiceServer).DeleteProgrammingLanguage(ctx, req.(*ProgrammingLanguageIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgrammingLanguagesService_ServiceDesc is the grpc.ServiceDesc for ProgrammingLanguagesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgrammingLanguagesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eruun.v1.ProgrammingLanguagesService",
	HandlerType: (*ProgrammingLanguagesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProgrammingLanguages",
			Handler:    _ProgrammingLanguagesService_ListProgrammingLanguages_Handler,
		},
		{
			MethodName: "GetProgrammingLanguage",
			Handler:    _ProgrammingLanguagesService_GetProgrammingLanguage_Handler,
		},
		{
			MethodName: "CreateProgrammingLanguage",
			Handler:    _ProgrammingLanguagesService_CreateProgrammingLanguage_Handler,
		},
		{
			MethodName: "UpdateProgrammingLanguage",
			Handler:    _ProgrammingLanguagesService_UpdateProgrammingLanguage_Handler,
		},
		{
			MethodName: "DeleteProgrammingLanguage",
			Handler:    _ProgrammingLanguagesService_DeleteProgrammingLanguage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eruun/v1/administration.proto",
}
