// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: eruun/v1/applications.proto

package eruunv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApplicationService_GetCanonicalJSONSchema_FullMethodName          = "/eruun.v1.ApplicationService/GetCanonicalJSONSchema"
	ApplicationService_ListApplications_FullMethodName                = "/eruun.v1.ApplicationService/ListApplications"
	ApplicationService_ListTemplateApplications_FullMethodName        = "/eruun.v1.ApplicationService/ListTemplateApplications"
	ApplicationService_ListCronJobs_FullMethodName                    = "/eruun.v1.ApplicationService/ListCronJobs"
	ApplicationService_ListScheduledJobs_FullMethodName               = "/eruun.v1.ApplicationService/ListScheduledJobs"
	ApplicationService_CreateApplications_FullMethodName              = "/eruun.v1.ApplicationService/CreateApplications"
	ApplicationService_CreateAndExecApplications_FullMethodName       = "/eruun.v1.ApplicationService/CreateAndExecApplications"
	ApplicationService_BatchGetApplications_FullMethodName            = "/eruun.v1.ApplicationService/BatchGetApplications"
	ApplicationService_ConvertApplications_FullMethodName             = "/eruun.v1.ApplicationService/ConvertApplications"
	ApplicationService_ImportNamespaceApplications_FullMethodName     = "/eruun.v1.ApplicationService/ImportNamespaceApplications"
	ApplicationService_TryImportNamespaceApplications_FullMethodName  = "/eruun.v1.ApplicationService/TryImportNamespaceApplications"
	ApplicationService_ListApplicationWorkflows_FullMethodName        = "/eruun.v1.ApplicationService/ListApplicationWorkflows"
	ApplicationService_GetApplicationSpec_FullMethodName              = "/eruun.v1.ApplicationService/GetApplicationSpec"
	ApplicationService_GetApplicationStatus_FullMethodName            = "/eruun.v1.ApplicationService/GetApplicationStatus"
	ApplicationService_ListApplicationComponents_FullMethodName       = "/eruun.v1.ApplicationService/ListApplicationComponents"
	ApplicationService_GetApplicationComponentStatus_FullMethodName   = "/eruun.v1.ApplicationService/GetApplicationComponentStatus"
	ApplicationService_ListComponentContainers_FullMethodName         = "/eruun.v1.ApplicationService/ListComponentContainers"
	ApplicationService_BatchApplicationComponentStatus_FullMethodName = "/eruun.v1.ApplicationService/BatchApplicationComponentStatus"
	ApplicationService_StreamComponentLogs_FullMethodName             = "/eruun.v1.ApplicationService/StreamComponentLogs"
	ApplicationService_ExportComponentFiles_FullMethodName            = "/eruun.v1.ApplicationService/ExportComponentFiles"
	ApplicationService_ExecComponentShell_FullMethodName              = "/eruun.v1.ApplicationService/ExecComponentShell"
	ApplicationService_StreamComponentShell_FullMethodName            = "/eruun.v1.ApplicationService/StreamComponentShell"
	ApplicationService_DeleteApplication_FullMethodName               = "/eruun.v1.ApplicationService/DeleteApplication"
	ApplicationService_UpdateApplicationWorkflow_FullMethodName       = "/eruun.v1.ApplicationService/UpdateApplicationWorkflow"
	ApplicationService_ListWorkflowSchedules_FullMethodName           = "/eruun.v1.ApplicationService/ListWorkflowSchedules"
	ApplicationService_UpsertWorkflowSchedule_FullMethodName          = "/eruun.v1.ApplicationService/UpsertWorkflowSchedule"
	ApplicationService_DeleteWorkflowSchedule_FullMethodName          = "/eruun.v1.ApplicationService/DeleteWorkflowSchedule"
	ApplicationService_PlanApplicationResourceCleanup_FullMethodName  = "/eruun.v1.ApplicationService/PlanApplicationResourceCleanup"
	ApplicationService_ApplyApplicationResourceCleanup_FullMethodName = "/eruun.v1.ApplicationService/ApplyApplicationResourceCleanup"
	ApplicationService_ResetApplicationDatabases_FullMethodName       = "/eruun.v1.ApplicationService/ResetApplicationDatabases"
	ApplicationService_DownloadLogArchive_FullMethodName              = "/eruun.v1.ApplicationService/DownloadLogArchive"
	ApplicationService_RestartApplicationWorkloads_FullMethodName     = "/eruun.v1.ApplicationService/RestartApplicationWorkloads"
	ApplicationService_StopApplicationDeployments_FullMethodName      = "/eruun.v1.ApplicationService/StopApplicationDeployments"
	ApplicationService_StartApplicationDeployments_FullMethodName     = "/eruun.v1.ApplicationService/StartApplicationDeployments"
	ApplicationService_ExecApplicationWorkflow_FullMethodName         = "/eruun.v1.ApplicationService/ExecApplicationWorkflow"
	ApplicationService_CancelApplicationWorkflow_FullMethodName       = "/eruun.v1.ApplicationService/CancelApplicationWorkflow"
	ApplicationService_CancelAllApplicationWorkflows_FullMethodName   = "/eruun.v1.ApplicationService/CancelAllApplicationWorkflows"
	ApplicationService_ListApplicationTasks_FullMethodName            = "/eruun.v1.ApplicationService/ListApplicationTasks"
	ApplicationService_ApproveWorkflowTask_FullMethodName             = "/eruun.v1.ApplicationService/ApproveWorkflowTask"
	ApplicationService_GetWorkflowTaskStatus_FullMethodName           = "/eruun.v1.ApplicationService/GetWorkflowTaskStatus"
	ApplicationService_GetWorkflowTaskStages_FullMethodName           = "/eruun.v1.ApplicationService/GetWorkflowTaskStages"
	ApplicationService_UpdateApplicationVersion_FullMethodName        = "/eruun.v1.ApplicationService/UpdateApplicationVersion"
	ApplicationService_DiffUpdateApplicationVersion_FullMethodName    = "/eruun.v1.ApplicationService/DiffUpdateApplicationVersion"
	ApplicationService_CancelDelayedVersionUpdate_FullMethodName      = "/eruun.v1.ApplicationService/CancelDelayedVersionUpdate"
	ApplicationService_TryApplication_FullMethodName                  = "/eruun.v1.ApplicationService/TryApplication"
	ApplicationService_TryWorkflow_FullMethodName                     = "/eruun.v1.ApplicationService/TryWorkflow"
)

// ApplicationServiceClient is the client API for ApplicationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApplicationService mirrors the user-facing application and Workflow routes.
type ApplicationServiceClient interface {
	GetCanonicalJSONSchema(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CanonicalJSONSchema, error)
	ListApplications(ctx context.Context, in *ApplicationListRequest, opts ...grpc.CallOption) (*AppDTOListApplicationResponse, error)
	ListTemplateApplications(ctx context.Context, in *ApplicationListRequest, opts ...grpc.CallOption) (*AppDTOListApplicationResponse, error)
	ListCronJobs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApplicationCronJobs, error)
	ListScheduledJobs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApplicationScheduledJobs, error)
	CreateApplications(ctx context.Context, in *AppDTOCreateApplicationsRequest, opts ...grpc.CallOption) (*AppDTOApplicationBase, error)
	CreateAndExecApplications(ctx context.Context, in *AppDTOCreateAndExecApplicationRequest, opts ...grpc.CallOption) (*AppDTOCreateAndExecApplicationResponse, error)
	BatchGetApplications(ctx context.Context, in *AppDTOBatchGetApplicationsRequest, opts ...grpc.CallOption) (*AppDTOBatchGetApplicationsResponse, error)
	ConvertApplications(ctx context.Context, in *AppDTOConvertApplicationsRequest, opts ...grpc.CallOption) (*AppDTOConvertApplicationsResponse, error)
	ImportNamespaceApplications(ctx context.Context, in *AppDTOImportNamespaceApplicationsRequest, opts ...grpc.CallOption) (*AppDTOImportNamespaceApplicationsResponse, error)
	TryImportNamespaceApplications(ctx context.Context, in *AppDTOTryImportNamespaceApplicationsRequest, opts ...grpc.CallOption) (*AppDTOTryImportNamespaceApplicationsResponse, error)
	ListApplicationWorkflows(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOListApplicationWorkflowsResponse, error)
	GetApplicationSpec(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOCreateApplicationsRequest, error)
	GetApplicationStatus(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOApplicationStatusResponse, error)
	ListApplicationComponents(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOListApplicationComponentsResponse, error)
	GetApplicationComponentStatus(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOApplicationComponentStatusResponse, error)
	ListComponentContainers(ctx context.Context, in *ApplicationComponentRequest, opts ...grpc.CallOption) (*AppDTOComponentContainersResponse, error)
	BatchApplicationComponentStatus(ctx context.Context, in *AppDTOBatchApplicationComponentStatusRequest, opts ...grpc.CallOption) (*AppDTOBatchApplicationComponentStatusResponse, error)
	StreamComponentLogs(ctx context.Context, in *ComponentLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComponentLogLine], error)
	ExportComponentFiles(ctx context.Context, in *ComponentFilesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComponentFileChunk], error)
	ExecComponentShell(ctx context.Context, in *ComponentShellRequest, opts ...grpc.CallOption) (*AppDTOExecComponentShellScriptResponse, error)
	StreamComponentShell(ctx context.Context, in *ComponentShellRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComponentShellEvent], error)
	DeleteApplication(ctx context.Context, in *DeleteApplicationRPCRequest, opts ...grpc.CallOption) (*AppDTODeleteApplicationResponse, error)
	UpdateApplicationWorkflow(ctx context.Context, in *UpdateApplicationWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOUpdateWorkflowResponse, error)
	ListWorkflowSchedules(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOListWorkflowSchedulesResponse, error)
	UpsertWorkflowSchedule(ctx context.Context, in *UpsertWorkflowScheduleRPCRequest, opts ...grpc.CallOption) (*AppDTOUpsertWorkflowScheduleResponse, error)
	DeleteWorkflowSchedule(ctx context.Context, in *ApplicationWorkflowRequest, opts ...grpc.CallOption) (*AppDTODeleteWorkflowScheduleResponse, error)
	PlanApplicationResourceCleanup(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOCleanupApplicationResourcesPlanResponse, error)
	ApplyApplicationResourceCleanup(ctx context.Context, in *CleanupApplicationRPCRequest, opts ...grpc.CallOption) (*AppDTOCleanupApplicationResourcesResponse, error)
	ResetApplicationDatabases(ctx context.Context, in *ResetApplicationDatabasesRPCRequest, opts ...grpc.CallOption) (*AppDTODatabaseResetResponse, error)
	DownloadLogArchive(ctx context.Context, in *LogArchiveRPCRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComponentFileChunk], error)
	RestartApplicationWorkloads(ctx context.Context, in *ApplicationLifecycleRPCRequest, opts ...grpc.CallOption) (*AppDTORestartApplicationWorkloadsResponse, error)
	StopApplicationDeployments(ctx context.Context, in *ApplicationLifecycleRPCRequest, opts ...grpc.CallOption) (*AppDTOStopApplicationDeploymentsResponse, error)
	StartApplicationDeployments(ctx context.Context, in *ApplicationLifecycleRPCRequest, opts ...grpc.CallOption) (*AppDTOStartApplicationDeploymentsResponse, error)
	ExecApplicationWorkflow(ctx context.Context, in *ExecWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOExecWorkflowResponse, error)
	CancelApplicationWorkflow(ctx context.Context, in *CancelWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOCancelWorkflowResponse, error)
	CancelAllApplicationWorkflows(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOCancelAllApplicationWorkflowsResponse, error)
	ListApplicationTasks(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOListApplicationTasksResponse, error)
	ApproveWorkflowTask(ctx context.Context, in *TaskApprovalRPCRequest, opts ...grpc.CallOption) (*AppDTOTaskApprovalResponse, error)
	GetWorkflowTaskStatus(ctx context.Context, in *WorkflowTaskIDRequest, opts ...grpc.CallOption) (*AppDTOTaskStatusResponse, error)
	GetWorkflowTaskStages(ctx context.Context, in *WorkflowTaskIDRequest, opts ...grpc.CallOption) (*AppDTOTaskStagesResponse, error)
	UpdateApplicationVersion(ctx context.Context, in *UpdateVersionRPCRequest, opts ...grpc.CallOption) (*AppDTOUpdateVersionResponse, error)
	DiffUpdateApplicationVersion(ctx context.Context, in *DiffUpdateVersionRPCRequest, opts ...grpc.CallOption) (*AppDTODiffUpdateVersionResponse, error)
	CancelDelayedVersionUpdate(ctx context.Context, in *CancelWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOCancelWorkflowResponse, error)
	TryApplication(ctx context.Context, in *AppDTOCreateApplicationsRequest, opts ...grpc.CallOption) (*AppDTOTryApplicationResponse, error)
	TryWorkflow(ctx context.Context, in *UpdateApplicationWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOTryWorkflowResponse, error)
}

type applicationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationServiceClient(cc grpc.ClientConnInterface) ApplicationServiceClient {
	return &applicationServiceClient{cc}
}

func (c *applicationServiceClient) GetCanonicalJSONSchema(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CanonicalJSONSchema, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanonicalJSONSchema)
	err := c.cc.Invoke(ctx, ApplicationService_GetCanonicalJSONSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListApplications(ctx context.Context, in *ApplicationListRequest, opts ...grpc.CallOption) (*AppDTOListApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOListApplicationResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListTemplateApplications(ctx context.Context, in *ApplicationListRequest, opts ...grpc.CallOption) (*AppDTOListApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOListApplicationResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListTemplateApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListCronJobs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApplicationCronJobs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationCronJobs)
	err := c.cc.Invoke(ctx, ApplicationService_ListCronJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListScheduledJobs(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApplicationScheduledJobs, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplicationScheduledJobs)
	err := c.cc.Invoke(ctx, ApplicationService_ListScheduledJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) CreateApplications(ctx context.Context, in *AppDTOCreateApplicationsRequest, opts ...grpc.CallOption) (*AppDTOApplicationBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOApplicationBase)
	err := c.cc.Invoke(ctx, ApplicationService_CreateApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) CreateAndExecApplications(ctx context.Context, in *AppDTOCreateAndExecApplicationRequest, opts ...grpc.CallOption) (*AppDTOCreateAndExecApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOCreateAndExecApplicationResponse)
	err := c.cc.Invoke(ctx, ApplicationService_CreateAndExecApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) BatchGetApplications(ctx context.Context, in *AppDTOBatchGetApplicationsRequest, opts ...grpc.CallOption) (*AppDTOBatchGetApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOBatchGetApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_BatchGetApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ConvertApplications(ctx context.Context, in *AppDTOConvertApplicationsRequest, opts ...grpc.CallOption) (*AppDTOConvertApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOConvertApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ConvertApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ImportNamespaceApplications(ctx context.Context, in *AppDTOImportNamespaceApplicationsRequest, opts ...grpc.CallOption) (*AppDTOImportNamespaceApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOImportNamespaceApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ImportNamespaceApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) TryImportNamespaceApplications(ctx context.Context, in *AppDTOTryImportNamespaceApplicationsRequest, opts ...grpc.CallOption) (*AppDTOTryImportNamespaceApplicationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOTryImportNamespaceApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_TryImportNamespaceApplications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListApplicationWorkflows(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOListApplicationWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOListApplicationWorkflowsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListApplicationWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetApplicationSpec(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOCreateApplicationsRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOCreateApplicationsRequest)
	err := c.cc.Invoke(ctx, ApplicationService_GetApplicationSpec_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetApplicationStatus(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOApplicationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOApplicationStatusResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetApplicationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListApplicationComponents(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOListApplicationComponentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOListApplicationComponentsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListApplicationComponents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetApplicationComponentStatus(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOApplicationComponentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOApplicationComponentStatusResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetApplicationComponentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListComponentContainers(ctx context.Context, in *ApplicationComponentRequest, opts ...grpc.CallOption) (*AppDTOComponentContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOComponentContainersResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListComponentContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) BatchApplicationComponentStatus(ctx context.Context, in *AppDTOBatchApplicationComponentStatusRequest, opts ...grpc.CallOption) (*AppDTOBatchApplicationComponentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOBatchApplicationComponentStatusResponse)
	err := c.cc.Invoke(ctx, ApplicationService_BatchApplicationComponentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) StreamComponentLogs(ctx context.Context, in *ComponentLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComponentLogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[0], ApplicationService_StreamComponentLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ComponentLogsRequest, ComponentLogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_StreamComponentLogsClient = grpc.ServerStreamingClient[ComponentLogLine]

func (c *applicationServiceClient) ExportComponentFiles(ctx context.Context, in *ComponentFilesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComponentFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[1], ApplicationService_ExportComponentFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ComponentFilesRequest, ComponentFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_ExportComponentFilesClient = grpc.ServerStreamingClient[ComponentFileChunk]

func (c *applicationServiceClient) ExecComponentShell(ctx context.Context, in *ComponentShellRequest, opts ...grpc.CallOption) (*AppDTOExecComponentShellScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOExecComponentShellScriptResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ExecComponentShell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) StreamComponentShell(ctx context.Context, in *ComponentShellRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComponentShellEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[2], ApplicationService_StreamComponentShell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ComponentShellRequest, ComponentShellEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_StreamComponentShellClient = grpc.ServerStreamingClient[ComponentShellEvent]

func (c *applicationServiceClient) DeleteApplication(ctx context.Context, in *DeleteApplicationRPCRequest, opts ...grpc.CallOption) (*AppDTODeleteApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTODeleteApplicationResponse)
	err := c.cc.Invoke(ctx, ApplicationService_DeleteApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) UpdateApplicationWorkflow(ctx context.Context, in *UpdateApplicationWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOUpdateWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOUpdateWorkflowResponse)
	err := c.cc.Invoke(ctx, ApplicationService_UpdateApplicationWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListWorkflowSchedules(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOListWorkflowSchedulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOListWorkflowSchedulesResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListWorkflowSchedules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) UpsertWorkflowSchedule(ctx context.Context, in *UpsertWorkflowScheduleRPCRequest, opts ...grpc.CallOption) (*AppDTOUpsertWorkflowScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOUpsertWorkflowScheduleResponse)
	err := c.cc.Invoke(ctx, ApplicationService_UpsertWorkflowSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) DeleteWorkflowSchedule(ctx context.Context, in *ApplicationWorkflowRequest, opts ...grpc.CallOption) (*AppDTODeleteWorkflowScheduleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTODeleteWorkflowScheduleResponse)
	err := c.cc.Invoke(ctx, ApplicationService_DeleteWorkflowSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) PlanApplicationResourceCleanup(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOCleanupApplicationResourcesPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOCleanupApplicationResourcesPlanResponse)
	err := c.cc.Invoke(ctx, ApplicationService_PlanApplicationResourceCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ApplyApplicationResourceCleanup(ctx context.Context, in *CleanupApplicationRPCRequest, opts ...grpc.CallOption) (*AppDTOCleanupApplicationResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOCleanupApplicationResourcesResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ApplyApplicationResourceCleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ResetApplicationDatabases(ctx context.Context, in *ResetApplicationDatabasesRPCRequest, opts ...grpc.CallOption) (*AppDTODatabaseResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTODatabaseResetResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ResetApplicationDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) DownloadLogArchive(ctx context.Context, in *LogArchiveRPCRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ComponentFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ApplicationService_ServiceDesc.Streams[3], ApplicationService_DownloadLogArchive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogArchiveRPCRequest, ComponentFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_DownloadLogArchiveClient = grpc.ServerStreamingClient[ComponentFileChunk]

func (c *applicationServiceClient) RestartApplicationWorkloads(ctx context.Context, in *ApplicationLifecycleRPCRequest, opts ...grpc.CallOption) (*AppDTORestartApplicationWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTORestartApplicationWorkloadsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_RestartApplicationWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) StopApplicationDeployments(ctx context.Context, in *ApplicationLifecycleRPCRequest, opts ...grpc.CallOption) (*AppDTOStopApplicationDeploymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOStopApplicationDeploymentsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_StopApplicationDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) StartApplicationDeployments(ctx context.Context, in *ApplicationLifecycleRPCRequest, opts ...grpc.CallOption) (*AppDTOStartApplicationDeploymentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOStartApplicationDeploymentsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_StartApplicationDeployments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ExecApplicationWorkflow(ctx context.Context, in *ExecWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOExecWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOExecWorkflowResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ExecApplicationWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) CancelApplicationWorkflow(ctx context.Context, in *CancelWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOCancelWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOCancelWorkflowResponse)
	err := c.cc.Invoke(ctx, ApplicationService_CancelApplicationWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) CancelAllApplicationWorkflows(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOCancelAllApplicationWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOCancelAllApplicationWorkflowsResponse)
	err := c.cc.Invoke(ctx, ApplicationService_CancelAllApplicationWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ListApplicationTasks(ctx context.Context, in *ApplicationIDRequest, opts ...grpc.CallOption) (*AppDTOListApplicationTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOListApplicationTasksResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ListApplicationTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) ApproveWorkflowTask(ctx context.Context, in *TaskApprovalRPCRequest, opts ...grpc.CallOption) (*AppDTOTaskApprovalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOTaskApprovalResponse)
	err := c.cc.Invoke(ctx, ApplicationService_ApproveWorkflowTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetWorkflowTaskStatus(ctx context.Context, in *WorkflowTaskIDRequest, opts ...grpc.CallOption) (*AppDTOTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOTaskStatusResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetWorkflowTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) GetWorkflowTaskStages(ctx context.Context, in *WorkflowTaskIDRequest, opts ...grpc.CallOption) (*AppDTOTaskStagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOTaskStagesResponse)
	err := c.cc.Invoke(ctx, ApplicationService_GetWorkflowTaskStages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) UpdateApplicationVersion(ctx context.Context, in *UpdateVersionRPCRequest, opts ...grpc.CallOption) (*AppDTOUpdateVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOUpdateVersionResponse)
	err := c.cc.Invoke(ctx, ApplicationService_UpdateApplicationVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) DiffUpdateApplicationVersion(ctx context.Context, in *DiffUpdateVersionRPCRequest, opts ...grpc.CallOption) (*AppDTODiffUpdateVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTODiffUpdateVersionResponse)
	err := c.cc.Invoke(ctx, ApplicationService_DiffUpdateApplicationVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) CancelDelayedVersionUpdate(ctx context.Context, in *CancelWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOCancelWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOCancelWorkflowResponse)
	err := c.cc.Invoke(ctx, ApplicationService_CancelDelayedVersionUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) TryApplication(ctx context.Context, in *AppDTOCreateApplicationsRequest, opts ...grpc.CallOption) (*AppDTOTryApplicationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOTryApplicationResponse)
	err := c.cc.Invoke(ctx, ApplicationService_TryApplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServiceClient) TryWorkflow(ctx context.Context, in *UpdateApplicationWorkflowRPCRequest, opts ...grpc.CallOption) (*AppDTOTryWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppDTOTryWorkflowResponse)
	err := c.cc.Invoke(ctx, ApplicationService_TryWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServiceServer is the server API for ApplicationService service.
// All implementations must embed UnimplementedApplicationServiceServer
// for forward compatibility.
//
// ApplicationService mirrors the user-facing application and Workflow routes.
type ApplicationServiceServer interface {
	GetCanonicalJSONSchema(context.Context, *emptypb.Empty) (*CanonicalJSONSchema, error)
	ListApplications(context.Context, *ApplicationListRequest) (*AppDTOListApplicationResponse, error)
	ListTemplateApplications(context.Context, *ApplicationListRequest) (*AppDTOListApplicationResponse, error)
	ListCronJobs(context.Context, *emptypb.Empty) (*ApplicationCronJobs, error)
	ListScheduledJobs(context.Context, *emptypb.Empty) (*ApplicationScheduledJobs, error)
	CreateApplications(context.Context, *AppDTOCreateApplicationsRequest) (*AppDTOApplicationBase, error)
	CreateAndExecApplications(context.Context, *AppDTOCreateAndExecApplicationRequest) (*AppDTOCreateAndExecApplicationResponse, error)
	BatchGetApplications(context.Context, *AppDTOBatchGetApplicationsRequest) (*AppDTOBatchGetApplicationsResponse, error)
	ConvertApplications(context.Context, *AppDTOConvertApplicationsRequest) (*AppDTOConvertApplicationsResponse, error)
	ImportNamespaceApplications(context.Context, *AppDTOImportNamespaceApplicationsRequest) (*AppDTOImportNamespaceApplicationsResponse, error)
	TryImportNamespaceApplications(context.Context, *AppDTOTryImportNamespaceApplicationsRequest) (*AppDTOTryImportNamespaceApplicationsResponse, error)
	ListApplicationWorkflows(context.Context, *ApplicationIDRequest) (*AppDTOListApplicationWorkflowsResponse, error)
	GetApplicationSpec(context.Context, *ApplicationIDRequest) (*AppDTOCreateApplicationsRequest, error)
	GetApplicationStatus(context.Context, *ApplicationIDRequest) (*AppDTOApplicationStatusResponse, error)
	ListApplicationComponents(context.Context, *ApplicationIDRequest) (*AppDTOListApplicationComponentsResponse, error)
	GetApplicationComponentStatus(context.Context, *ApplicationIDRequest) (*AppDTOApplicationComponentStatusResponse, error)
	ListComponentContainers(context.Context, *ApplicationComponentRequest) (*AppDTOComponentContainersResponse, error)
	BatchApplicationComponentStatus(context.Context, *AppDTOBatchApplicationComponentStatusRequest) (*AppDTOBatchApplicationComponentStatusResponse, error)
	StreamComponentLogs(*ComponentLogsRequest, grpc.ServerStreamingServer[ComponentLogLine]) error
	ExportComponentFiles(*ComponentFilesRequest, grpc.ServerStreamingServer[ComponentFileChunk]) error
	ExecComponentShell(context.Context, *ComponentShellRequest) (*AppDTOExecComponentShellScriptResponse, error)
	StreamComponentShell(*ComponentShellRequest, grpc.ServerStreamingServer[ComponentShellEvent]) error
	DeleteApplication(context.Context, *DeleteApplicationRPCRequest) (*AppDTODeleteApplicationResponse, error)
	UpdateApplicationWorkflow(context.Context, *UpdateApplicationWorkflowRPCRequest) (*AppDTOUpdateWorkflowResponse, error)
	ListWorkflowSchedules(context.Context, *ApplicationIDRequest) (*AppDTOListWorkflowSchedulesResponse, error)
	UpsertWorkflowSchedule(context.Context, *UpsertWorkflowScheduleRPCRequest) (*AppDTOUpsertWorkflowScheduleResponse, error)
	DeleteWorkflowSchedule(context.Context, *ApplicationWorkflowRequest) (*AppDTODeleteWorkflowScheduleResponse, error)
	PlanApplicationResourceCleanup(context.Context, *ApplicationIDRequest) (*AppDTOCleanupApplicationResourcesPlanResponse, error)
	ApplyApplicationResourceCleanup(context.Context, *CleanupApplicationRPCRequest) (*AppDTOCleanupApplicationResourcesResponse, error)
	ResetApplicationDatabases(context.Context, *ResetApplicationDatabasesRPCRequest) (*AppDTODatabaseResetResponse, error)
	DownloadLogArchive(*LogArchiveRPCRequest, grpc.ServerStreamingServer[ComponentFileChunk]) error
	RestartApplicationWorkloads(context.Context, *ApplicationLifecycleRPCRequest) (*AppDTORestartApplicationWorkloadsResponse, error)
	StopApplicationDeployments(context.Context, *ApplicationLifecycleRPCRequest) (*AppDTOStopApplicationDeploymentsResponse, error)
	StartApplicationDeployments(context.Context, *ApplicationLifecycleRPCRequest) (*AppDTOStartApplicationDeploymentsResponse, error)
	ExecApplicationWorkflow(context.Context, *ExecWorkflowRPCRequest) (*AppDTOExecWorkflowResponse, error)
	CancelApplicationWorkflow(context.Context, *CancelWorkflowRPCRequest) (*AppDTOCancelWorkflowResponse, error)
	CancelAllApplicationWorkflows(context.Context, *ApplicationIDRequest) (*AppDTOCancelAllApplicationWorkflowsResponse, error)
	ListApplicationTasks(context.Context, *ApplicationIDRequest) (*AppDTOListApplicationTasksResponse, error)
	ApproveWorkflowTask(context.Context, *TaskApprovalRPCRequest) (*AppDTOTaskApprovalResponse, error)
	GetWorkflowTaskStatus(context.Context, *WorkflowTaskIDRequest) (*AppDTOTaskStatusResponse, error)
	GetWorkflowTaskStages(context.Context, *WorkflowTaskIDRequest) (*AppDTOTaskStagesResponse, error)
	UpdateApplicationVersion(context.Context, *UpdateVersionRPCRequest) (*AppDTOUpdateVersionResponse, error)
	DiffUpdateApplicationVersion(context.Context, *DiffUpdateVersionRPCRequest) (*AppDTODiffUpdateVersionResponse, error)
	CancelDelayedVersionUpdate(context.Context, *CancelWorkflowRPCRequest) (*AppDTOCancelWorkflowResponse, error)
	TryApplication(context.Context, *AppDTOCreateApplicationsRequest) (*AppDTOTryApplicationResponse, error)
	TryWorkflow(context.Context, *UpdateApplicationWorkflowRPCRequest) (*AppDTOTryWorkflowResponse, error)
	mustEmbedUnimplementedApplicationServiceServer()
}

// UnimplementedApplicationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApplicationServiceServer struct{}

func (UnimplementedApplicationServiceServer) GetCanonicalJSONSchema(context.Context, *emptypb.Empty) (*CanonicalJSONSchema, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCanonicalJSONSchema not implemented")
}
func (UnimplementedApplicationServiceServer) ListApplications(context.Context, *ApplicationListRequest) (*AppDTOListApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplications not implemented")
}
func (UnimplementedApplicationServiceServer) ListTemplateApplications(context.Context, *ApplicationListRequest) (*AppDTOListApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTemplateApplications not implemented")
}
func (UnimplementedApplicationServiceServer) ListCronJobs(context.Context, *emptypb.Empty) (*ApplicationCronJobs, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCronJobs not implemented")
}
func (UnimplementedApplicationServiceServer) ListScheduledJobs(context.Context, *emptypb.Empty) (*ApplicationScheduledJobs, error) {
	return nil, status.Error(codes.Unimplemented, "method ListScheduledJobs not implemented")
}
func (UnimplementedApplicationServiceServer) CreateApplications(context.Context, *AppDTOCreateApplicationsRequest) (*AppDTOApplicationBase, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateApplications not implemented")
}
func (UnimplementedApplicationServiceServer) CreateAndExecApplications(context.Context, *AppDTOCreateAndExecApplicationRequest) (*AppDTOCreateAndExecApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAndExecApplications not implemented")
}
func (UnimplementedApplicationServiceServer) BatchGetApplications(context.Context, *AppDTOBatchGetApplicationsRequest) (*AppDTOBatchGetApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetApplications not implemented")
}
func (UnimplementedApplicationServiceServer) ConvertApplications(context.Context, *AppDTOConvertApplicationsRequest) (*AppDTOConvertApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertApplications not implemented")
}
func (UnimplementedApplicationServiceServer) ImportNamespaceApplications(context.Context, *AppDTOImportNamespaceApplicationsRequest) (*AppDTOImportNamespaceApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportNamespaceApplications not implemented")
}
func (UnimplementedApplicationServiceServer) TryImportNamespaceApplications(context.Context, *AppDTOTryImportNamespaceApplicationsRequest) (*AppDTOTryImportNamespaceApplicationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TryImportNamespaceApplications not implemented")
}
func (UnimplementedApplicationServiceServer) ListApplicationWorkflows(context.Context, *ApplicationIDRequest) (*AppDTOListApplicationWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplicationWorkflows not implemented")
}
func (UnimplementedApplicationServiceServer) GetApplicationSpec(context.Context, *ApplicationIDRequest) (*AppDTOCreateApplicationsRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationSpec not implemented")
}
func (UnimplementedApplicationServiceServer) GetApplicationStatus(context.Context, *ApplicationIDRequest) (*AppDTOApplicationStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationStatus not implemented")
}
func (UnimplementedApplicationServiceServer) ListApplicationComponents(context.Context, *ApplicationIDRequest) (*AppDTOListApplicationComponentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplicationComponents not implemented")
}
func (UnimplementedApplicationServiceServer) GetApplicationComponentStatus(context.Context, *ApplicationIDRequest) (*AppDTOApplicationComponentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplicationComponentStatus not implemented")
}
func (UnimplementedApplicationServiceServer) ListComponentContainers(context.Context, *ApplicationComponentRequest) (*AppDTOComponentContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComponentContainers not implemented")
}
func (UnimplementedApplicationServiceServer) BatchApplicationComponentStatus(context.Context, *AppDTOBatchApplicationComponentStatusRequest) (*AppDTOBatchApplicationComponentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchApplicationComponentStatus not implemented")
}
func (UnimplementedApplicationServiceServer) StreamComponentLogs(*ComponentLogsRequest, grpc.ServerStreamingServer[ComponentLogLine]) error {
	return status.Error(codes.Unimplemented, "method StreamComponentLogs not implemented")
}
func (UnimplementedApplicationServiceServer) ExportComponentFiles(*ComponentFilesRequest, grpc.ServerStreamingServer[ComponentFileChunk]) error {
	return status.Error(codes.Unimplemented, "method ExportComponentFiles not implemented")
}
func (UnimplementedApplicationServiceServer) ExecComponentShell(context.Context, *ComponentShellRequest) (*AppDTOExecComponentShellScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecComponentShell not implemented")
}
func (UnimplementedApplicationServiceServer) StreamComponentShell(*ComponentShellRequest, grpc.ServerStreamingServer[ComponentShellEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamComponentShell not implemented")
}
func (UnimplementedApplicationServiceServer) DeleteApplication(context.Context, *DeleteApplicationRPCRequest) (*AppDTODeleteApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteApplication not implemented")
}
func (UnimplementedApplicationServiceServer) UpdateApplicationWorkflow(context.Context, *UpdateApplicationWorkflowRPCRequest) (*AppDTOUpdateWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApplicationWorkflow not implemented")
}
func (UnimplementedApplicationServiceServer) ListWorkflowSchedules(context.Context, *ApplicationIDRequest) (*AppDTOListWorkflowSchedulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflowSchedules not implemented")
}
func (UnimplementedApplicationServiceServer) UpsertWorkflowSchedule(context.Context, *UpsertWorkflowScheduleRPCRequest) (*AppDTOUpsertWorkflowScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertWorkflowSchedule not implemented")
}
func (UnimplementedApplicationServiceServer) DeleteWorkflowSchedule(context.Context, *ApplicationWorkflowRequest) (*AppDTODeleteWorkflowScheduleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkflowSchedule not implemented")
}
func (UnimplementedApplicationServiceServer) PlanApplicationResourceCleanup(context.Context, *ApplicationIDRequest) (*AppDTOCleanupApplicationResourcesPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanApplicationResourceCleanup not implemented")
}
func (UnimplementedApplicationServiceServer) ApplyApplicationResourceCleanup(context.Context, *CleanupApplicationRPCRequest) (*AppDTOCleanupApplicationResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyApplicationResourceCleanup not implemented")
}
func (UnimplementedApplicationServiceServer) ResetApplicationDatabases(context.Context, *ResetApplicationDatabasesRPCRequest) (*AppDTODatabaseResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetApplicationDatabases not implemented")
}
func (UnimplementedApplicationServiceServer) DownloadLogArchive(*LogArchiveRPCRequest, grpc.ServerStreamingServer[ComponentFileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadLogArchive not implemented")
}
func (UnimplementedApplicationServiceServer) RestartApplicationWorkloads(context.Context, *ApplicationLifecycleRPCRequest) (*AppDTORestartApplicationWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartApplicationWorkloads not implemented")
}
func (UnimplementedApplicationServiceServer) StopApplicationDeployments(context.Context, *ApplicationLifecycleRPCRequest) (*AppDTOStopApplicationDeploymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopApplicationDeployments not implemented")
}
func (UnimplementedApplicationServiceServer) StartApplicationDeployments(context.Context, *ApplicationLifecycleRPCRequest) (*AppDTOStartApplicationDeploymentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartApplicationDeployments not implemented")
}
func (UnimplementedApplicationServiceServer) ExecApplicationWorkflow(context.Context, *ExecWorkflowRPCRequest) (*AppDTOExecWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecApplicationWorkflow not implemented")
}
func (UnimplementedApplicationServiceServer) CancelApplicationWorkflow(context.Context, *CancelWorkflowRPCRequest) (*AppDTOCancelWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelApplicationWorkflow not implemented")
}
func (UnimplementedApplicationServiceServer) CancelAllApplicationWorkflows(context.Context, *ApplicationIDRequest) (*AppDTOCancelAllApplicationWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAllApplicationWorkflows not implemented")
}
func (UnimplementedApplicationServiceServer) ListApplicationTasks(context.Context, *ApplicationIDRequest) (*AppDTOListApplicationTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListApplicationTasks not implemented")
}
func (UnimplementedApplicationServiceServer) ApproveWorkflowTask(context.Context, *TaskApprovalRPCRequest) (*AppDTOTaskApprovalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveWorkflowTask not implemented")
}
func (UnimplementedApplicationServiceServer) GetWorkflowTaskStatus(context.Context, *WorkflowTaskIDRequest) (*AppDTOTaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowTaskStatus not implemented")
}
func (UnimplementedApplicationServiceServer) GetWorkflowTaskStages(context.Context, *WorkflowTaskIDRequest) (*AppDTOTaskStagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowTaskStages not implemented")
}
func (UnimplementedApplicationServiceServer) UpdateApplicationVersion(context.Context, *UpdateVersionRPCRequest) (*AppDTOUpdateVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateApplicationVersion not implemented")
}
func (UnimplementedApplicationServiceServer) DiffUpdateApplicationVersion(context.Context, *DiffUpdateVersionRPCRequest) (*AppDTODiffUpdateVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffUpdateApplicationVersion not implemented")
}
func (UnimplementedApplicationServiceServer) CancelDelayedVersionUpdate(context.Context, *CancelWorkflowRPCRequest) (*AppDTOCancelWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelDelayedVersionUpdate not implemented")
}
func (UnimplementedApplicationServiceServer) TryApplication(context.Context, *AppDTOCreateApplicationsRequest) (*AppDTOTryApplicationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TryApplication not implemented")
}
func (UnimplementedApplicationServiceServer) TryWorkflow(context.Context, *UpdateApplicationWorkflowRPCRequest) (*AppDTOTryWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TryWorkflow not implemented")
}
func (UnimplementedApplicationServiceServer) mustEmbedUnimplementedApplicationServiceServer() {}
func (UnimplementedApplicationServiceServer) testEmbeddedByValue()                            {}

// UnsafeApplicationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationServiceServer will
// result in compilation errors.
type UnsafeApplicationServiceServer interface {
	mustEmbedUnimplementedApplicationServiceServer()
}

func RegisterApplicationServiceServer(s grpc.ServiceRegistrar, srv ApplicationServiceServer) {
	// If the following call panics, it indicates UnimplementedApplicationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApplicationService_ServiceDesc, srv)
}

func _ApplicationService_GetCanonicalJSONSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetCanonicalJSONSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetCanonicalJSONSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetCanonicalJSONSchema(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListApplications(ctx, req.(*ApplicationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListTemplateApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListTemplateApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListTemplateApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListTemplateApplications(ctx, req.(*ApplicationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListCronJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListCronJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListCronJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListCronJobs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListScheduledJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListScheduledJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListScheduledJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListScheduledJobs(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_CreateApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppDTOCreateApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).CreateApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_CreateApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).CreateApplications(ctx, req.(*AppDTOCreateApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_CreateAndExecApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppDTOCreateAndExecApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).CreateAndExecApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_CreateAndExecApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).CreateAndExecApplications(ctx, req.(*AppDTOCreateAndExecApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_BatchGetApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppDTOBatchGetApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).BatchGetApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_BatchGetApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).BatchGetApplications(ctx, req.(*AppDTOBatchGetApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ConvertApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppDTOConvertApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ConvertApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ConvertApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ConvertApplications(ctx, req.(*AppDTOConvertApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ImportNamespaceApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppDTOImportNamespaceApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ImportNamespaceApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ImportNamespaceApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ImportNamespaceApplications(ctx, req.(*AppDTOImportNamespaceApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_TryImportNamespaceApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppDTOTryImportNamespaceApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).TryImportNamespaceApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_TryImportNamespaceApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).TryImportNamespaceApplications(ctx, req.(*AppDTOTryImportNamespaceApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListApplicationWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListApplicationWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListApplicationWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListApplicationWorkflows(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetApplicationSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetApplicationSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetApplicationSpec_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetApplicationSpec(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetApplicationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetApplicationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetApplicationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetApplicationStatus(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListApplicationComponents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListApplicationComponents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListApplicationComponents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListApplicationComponents(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetApplicationComponentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetApplicationComponentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetApplicationComponentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetApplicationComponentStatus(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListComponentContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationComponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListComponentContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListComponentContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListComponentContainers(ctx, req.(*ApplicationComponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_BatchApplicationComponentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppDTOBatchApplicationComponentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).BatchApplicationComponentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_BatchApplicationComponentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).BatchApplicationComponentStatus(ctx, req.(*AppDTOBatchApplicationComponentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_StreamComponentLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ComponentLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationServiceServer).StreamComponentLogs(m, &grpc.GenericServerStream[ComponentLogsRequest, ComponentLogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_StreamComponentLogsServer = grpc.ServerStreamingServer[ComponentLogLine]

func _ApplicationService_ExportComponentFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ComponentFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationServiceServer).ExportComponentFiles(m, &grpc.GenericServerStream[ComponentFilesRequest, ComponentFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_ExportComponentFilesServer = grpc.ServerStreamingServer[ComponentFileChunk]

func _ApplicationService_ExecComponentShell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComponentShellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ExecComponentShell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ExecComponentShell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ExecComponentShell(ctx, req.(*ComponentShellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_StreamComponentShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ComponentShellRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationServiceServer).StreamComponentShell(m, &grpc.GenericServerStream[ComponentShellRequest, ComponentShellEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_StreamComponentShellServer = grpc.ServerStreamingServer[ComponentShellEvent]

func _ApplicationService_DeleteApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplicationRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).DeleteApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_DeleteApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).DeleteApplication(ctx, req.(*DeleteApplicationRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_UpdateApplicationWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationWorkflowRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).UpdateApplicationWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_UpdateApplicationWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).UpdateApplicationWorkflow(ctx, req.(*UpdateApplicationWorkflowRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListWorkflowSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListWorkflowSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListWorkflowSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListWorkflowSchedules(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_UpsertWorkflowSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertWorkflowScheduleRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).UpsertWorkflowSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_UpsertWorkflowSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).UpsertWorkflowSchedule(ctx, req.(*UpsertWorkflowScheduleRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_DeleteWorkflowSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).DeleteWorkflowSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_DeleteWorkflowSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).DeleteWorkflowSchedule(ctx, req.(*ApplicationWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_PlanApplicationResourceCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).PlanApplicationResourceCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_PlanApplicationResourceCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).PlanApplicationResourceCleanup(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ApplyApplicationResourceCleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupApplicationRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ApplyApplicationResourceCleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ApplyApplicationResourceCleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ApplyApplicationResourceCleanup(ctx, req.(*CleanupApplicationRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ResetApplicationDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetApplicationDatabasesRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ResetApplicationDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ResetApplicationDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ResetApplicationDatabases(ctx, req.(*ResetApplicationDatabasesRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_DownloadLogArchive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogArchiveRPCRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ApplicationServiceServer).DownloadLogArchive(m, &grpc.GenericServerStream[LogArchiveRPCRequest, ComponentFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ApplicationService_DownloadLogArchiveServer = grpc.ServerStreamingServer[ComponentFileChunk]

func _ApplicationService_RestartApplicationWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationLifecycleRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).RestartApplicationWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_RestartApplicationWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).RestartApplicationWorkloads(ctx, req.(*ApplicationLifecycleRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_StopApplicationDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationLifecycleRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).StopApplicationDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_StopApplicationDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).StopApplicationDeployments(ctx, req.(*ApplicationLifecycleRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_StartApplicationDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationLifecycleRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).StartApplicationDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_StartApplicationDeployments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).StartApplicationDeployments(ctx, req.(*ApplicationLifecycleRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ExecApplicationWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecWorkflowRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ExecApplicationWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ExecApplicationWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ExecApplicationWorkflow(ctx, req.(*ExecWorkflowRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_CancelApplicationWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).CancelApplicationWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_CancelApplicationWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).CancelApplicationWorkflow(ctx, req.(*CancelWorkflowRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_CancelAllApplicationWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).CancelAllApplicationWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_CancelAllApplicationWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).CancelAllApplicationWorkflows(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ListApplicationTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicationIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ListApplicationTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ListApplicationTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ListApplicationTasks(ctx, req.(*ApplicationIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_ApproveWorkflowTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskApprovalRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).ApproveWorkflowTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_ApproveWorkflowTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).ApproveWorkflowTask(ctx, req.(*TaskApprovalRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetWorkflowTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowTaskIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetWorkflowTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetWorkflowTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetWorkflowTaskStatus(ctx, req.(*WorkflowTaskIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_GetWorkflowTaskStages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkflowTaskIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).GetWorkflowTaskStages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_GetWorkflowTaskStages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).GetWorkflowTaskStages(ctx, req.(*WorkflowTaskIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_UpdateApplicationVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVersionRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).UpdateApplicationVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_UpdateApplicationVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).UpdateApplicationVersion(ctx, req.(*UpdateVersionRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_DiffUpdateApplicationVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffUpdateVersionRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).DiffUpdateApplicationVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_DiffUpdateApplicationVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).DiffUpdateApplicationVersion(ctx, req.(*DiffUpdateVersionRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_CancelDelayedVersionUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).CancelDelayedVersionUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_CancelDelayedVersionUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).CancelDelayedVersionUpdate(ctx, req.(*CancelWorkflowRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_TryApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppDTOCreateApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).TryApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_TryApplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).TryApplication(ctx, req.(*AppDTOCreateApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationService_TryWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApplicationWorkflowRPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServiceServer).TryWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationService_TryWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServiceServer).TryWorkflow(ctx, req.(*UpdateApplicationWorkflowRPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationService_ServiceDesc is the grpc.ServiceDesc for ApplicationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eruun.v1.ApplicationService",
	HandlerType: (*ApplicationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCanonicalJSONSchema",
			Handler:    _ApplicationService_GetCanonicalJSONSchema_Handler,
		},
		{
			MethodName: "ListApplications",
			Handler:    _ApplicationService_ListApplications_Handler,
		},
		{
			MethodName: "ListTemplateApplications",
			Handler:    _ApplicationService_ListTemplateApplications_Handler,
		},
		{
			MethodName: "ListCronJobs",
			Handler:    _ApplicationService_ListCronJobs_Handler,
		},
		{
			MethodName: "ListScheduledJobs",
			Handler:    _ApplicationService_ListScheduledJobs_Handler,
		},
		{
			MethodName: "CreateApplications",
			Handler:    _ApplicationService_CreateApplications_Handler,
		},
		{
			MethodName: "CreateAndExecApplications",
			Handler:    _ApplicationService_CreateAndExecApplications_Handler,
		},
		{
			MethodName: "BatchGetApplications",
			Handler:    _ApplicationService_BatchGetApplications_Handler,
		},
		{
			MethodName: "ConvertApplications",
			Handler:    _ApplicationService_ConvertApplications_Handler,
		},
		{
			MethodName: "ImportNamespaceApplications",
			Handler:    _ApplicationService_ImportNamespaceApplications_Handler,
		},
		{
			MethodName: "TryImportNamespaceApplications",
			Handler:    _ApplicationService_TryImportNamespaceApplications_Handler,
		},
		{
			MethodName: "ListApplicationWorkflows",
			Handler:    _ApplicationService_ListApplicationWorkflows_Handler,
		},
		{
			MethodName: "GetApplicationSpec",
			Handler:    _ApplicationService_GetApplicationSpec_Handler,
		},
		{
			MethodName: "GetApplicationStatus",
			Handler:    _ApplicationService_GetApplicationStatus_Handler,
		},
		{
			MethodName: "ListApplicationComponents",
			Handler:    _ApplicationService_ListApplicationComponents_Handler,
		},
		{
			MethodName: "GetApplicationComponentStatus",
			Handler:    _ApplicationService_GetApplicationComponentStatus_Handler,
		},
		{
			MethodName: "ListComponentContainers",
			Handler:    _ApplicationService_ListComponentContainers_Handler,
		},
		{
			MethodName: "BatchApplicationComponentStatus",
			Handler:    _ApplicationService_BatchApplicationComponentStatus_Handler,
		},
		{
			MethodName: "ExecComponentShell",
			Handler:    _ApplicationService_ExecComponentShell_Handler,
		},
		{
			MethodName: "DeleteApplication",
			Handler:    _ApplicationService_DeleteApplication_Handler,
		},
		{
			MethodName: "UpdateApplicationWorkflow",
			Handler:    _ApplicationService_UpdateApplicationWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflowSchedules",
			Handler:    _ApplicationService_ListWorkflowSchedules_Handler,
		},
		{
			MethodName: "UpsertWorkflowSchedule",
			Handler:    _ApplicationService_UpsertWorkflowSchedule_Handler,
		},
		{
			MethodName: "DeleteWorkflowSchedule",
			Handler:    _ApplicationService_DeleteWorkflowSchedule_Handler,
		},
		{
			MethodName: "PlanApplicationResourceCleanup",
			Handler:    _ApplicationService_PlanApplicationResourceCleanup_Handler,
		},
		{
			MethodName: "ApplyApplicationResourceCleanup",
			Handler:    _ApplicationService_ApplyApplicationResourceCleanup_Handler,
		},
		{
			MethodName: "ResetApplicationDatabases",
			Handler:    _ApplicationService_ResetApplicationDatabases_Handler,
		},
		{
			MethodName: "RestartApplicationWorkloads",
			Handler:    _ApplicationService_RestartApplicationWorkloads_Handler,
		},
		{
			MethodName: "StopApplicationDeployments",
			Handler:    _ApplicationService_StopApplicationDeployments_Handler,
		},
		{
			MethodName: "StartApplicationDeployments",
			Handler:    _ApplicationService_StartApplicationDeployments_Handler,
		},
		{
			MethodName: "ExecApplicationWorkflow",
			Handler:    _ApplicationService_ExecApplicationWorkflow_Handler,
		},
		{
			MethodName: "CancelApplicationWorkflow",
			Handler:    _ApplicationService_CancelApplicationWorkflow_Handler,
		},
		{
			MethodName: "CancelAllApplicationWorkflows",
			Handler:    _ApplicationService_CancelAllApplicationWorkflows_Handler,
		},
		{
			MethodName: "ListApplicationTasks",
			Handler:    _ApplicationService_ListApplicationTasks_Handler,
		},
		{
			MethodName: "ApproveWorkflowTask",
			Handler:    _ApplicationService_ApproveWorkflowTask_Handler,
		},
		{
			MethodName: "GetWorkflowTaskStatus",
			Handler:    _ApplicationService_GetWorkflowTaskStatus_Handler,
		},
		{
			MethodName: "GetWorkflowTaskStages",
			Handler:    _ApplicationService_GetWorkflowTaskStages_Handler,
		},
		{
			MethodName: "UpdateApplicationVersion",
			Handler:    _ApplicationService_UpdateApplicationVersion_Handler,
		},
		{
			MethodName: "DiffUpdateApplicationVersion",
			Handler:    _ApplicationService_DiffUpdateApplicationVersion_Handler,
		},
		{
			MethodName: "CancelDelayedVersionUpdate",
			Handler:    _ApplicationService_CancelDelayedVersionUpdate_Handler,
		},
		{
			MethodName: "TryApplication",
			Handler:    _ApplicationService_TryApplication_Handler,
		},
		{
			MethodName: "TryWorkflow",
			Handler:    _ApplicationService_TryWorkflow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamComponentLogs",
			Handler:       _ApplicationService_StreamComponentLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExportComponentFiles",
			Handler:       _ApplicationService_ExportComponentFiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamComponentShell",
			Handler:       _ApplicationService_StreamComponentShell_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadLogArchive",
			Handler:       _ApplicationService_DownloadLogArchive_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eruun/v1/applications.proto",
}
