// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: eruun/v1/jobs.proto

package eruunv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobsService_SubmitJob_FullMethodName           = "/eruun.v1.JobsService/SubmitJob"
	JobsService_GetJob_FullMethodName              = "/eruun.v1.JobsService/GetJob"
	JobsService_CancelJob_FullMethodName           = "/eruun.v1.JobsService/CancelJob"
	JobsService_GetJobResults_FullMethodName       = "/eruun.v1.JobsService/GetJobResults"
	JobsService_DownloadJobResult_FullMethodName   = "/eruun.v1.JobsService/DownloadJobResult"
	JobsService_DownloadJobDelivery_FullMethodName = "/eruun.v1.JobsService/DownloadJobDelivery"
	JobsService_RetryJobDelivery_FullMethodName    = "/eruun.v1.JobsService/RetryJobDelivery"
	JobsService_SetJobRetention_FullMethodName     = "/eruun.v1.JobsService/SetJobRetention"
	JobsService_GetJobStoragePolicy_FullMethodName = "/eruun.v1.JobsService/GetJobStoragePolicy"
	JobsService_SetJobStoragePolicy_FullMethodName = "/eruun.v1.JobsService/SetJobStoragePolicy"
	JobsService_UploadJobDataset_FullMethodName    = "/eruun.v1.JobsService/UploadJobDataset"
	JobsService_ListJobDatasets_FullMethodName     = "/eruun.v1.JobsService/ListJobDatasets"
	JobsService_GetJobDataset_FullMethodName       = "/eruun.v1.JobsService/GetJobDataset"
	JobsService_DownloadJobDataset_FullMethodName  = "/eruun.v1.JobsService/DownloadJobDataset"
)

// JobsServiceClient is the client API for JobsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobsService is the user-session API. Runner capability callbacks are HTTP-only.
type JobsServiceClient interface {
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*JobAccepted, error)
	GetJob(ctx context.Context, in *JobTaskRequest, opts ...grpc.CallOption) (*JobDetail, error)
	CancelJob(ctx context.Context, in *JobTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetJobResults(ctx context.Context, in *JobTaskRequest, opts ...grpc.CallOption) (*JobResults, error)
	DownloadJobResult(ctx context.Context, in *JobArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArchiveChunk], error)
	DownloadJobDelivery(ctx context.Context, in *JobDeliveryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArchiveChunk], error)
	RetryJobDelivery(ctx context.Context, in *JobDeliveryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetJobRetention(ctx context.Context, in *SetJobRetentionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetJobStoragePolicy(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JobStoragePolicy, error)
	SetJobStoragePolicy(ctx context.Context, in *JobResultPolicy, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UploadJobDataset(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadDatasetPart, JobArtifact], error)
	ListJobDatasets(ctx context.Context, in *ListJobDatasetsRequest, opts ...grpc.CallOption) (*JobArtifacts, error)
	GetJobDataset(ctx context.Context, in *JobDatasetRequest, opts ...grpc.CallOption) (*JobArtifact, error)
	DownloadJobDataset(ctx context.Context, in *JobDatasetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArchiveChunk], error)
}

type jobsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobsServiceClient(cc grpc.ClientConnInterface) JobsServiceClient {
	return &jobsServiceClient{cc}
}

func (c *jobsServiceClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*JobAccepted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobAccepted)
	err := c.cc.Invoke(ctx, JobsService_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) GetJob(ctx context.Context, in *JobTaskRequest, opts ...grpc.CallOption) (*JobDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobDetail)
	err := c.cc.Invoke(ctx, JobsService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) CancelJob(ctx context.Context, in *JobTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobsService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) GetJobResults(ctx context.Context, in *JobTaskRequest, opts ...grpc.CallOption) (*JobResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResults)
	err := c.cc.Invoke(ctx, JobsService_GetJobResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) DownloadJobResult(ctx context.Context, in *JobArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArchiveChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobsService_ServiceDesc.Streams[0], JobsService_DownloadJobResult_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobArtifactRequest, ArchiveChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobsService_DownloadJobResultClient = grpc.ServerStreamingClient[ArchiveChunk]

func (c *jobsServiceClient) DownloadJobDelivery(ctx context.Context, in *JobDeliveryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArchiveChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobsService_ServiceDesc.Streams[1], JobsService_DownloadJobDelivery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobDeliveryRequest, ArchiveChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobsService_DownloadJobDeliveryClient = grpc.ServerStreamingClient[ArchiveChunk]

func (c *jobsServiceClient) RetryJobDelivery(ctx context.Context, in *JobDeliveryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobsService_RetryJobDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) SetJobRetention(ctx context.Context, in *SetJobRetentionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobsService_SetJobRetention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) GetJobStoragePolicy(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*JobStoragePolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStoragePolicy)
	err := c.cc.Invoke(ctx, JobsService_GetJobStoragePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) SetJobStoragePolicy(ctx context.Context, in *JobResultPolicy, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, JobsService_SetJobStoragePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) UploadJobDataset(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadDatasetPart, JobArtifact], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobsService_ServiceDesc.Streams[2], JobsService_UploadJobDataset_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadDatasetPart, JobArtifact]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobsService_UploadJobDatasetClient = grpc.ClientStreamingClient[UploadDatasetPart, JobArtifact]

func (c *jobsServiceClient) ListJobDatasets(ctx context.Context, in *ListJobDatasetsRequest, opts ...grpc.CallOption) (*JobArtifacts, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobArtifacts)
	err := c.cc.Invoke(ctx, JobsService_ListJobDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) GetJobDataset(ctx context.Context, in *JobDatasetRequest, opts ...grpc.CallOption) (*JobArtifact, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobArtifact)
	err := c.cc.Invoke(ctx, JobsService_GetJobDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobsServiceClient) DownloadJobDataset(ctx context.Context, in *JobDatasetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArchiveChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobsService_ServiceDesc.Streams[3], JobsService_DownloadJobDataset_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobDatasetRequest, ArchiveChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobsService_DownloadJobDatasetClient = grpc.ServerStreamingClient[ArchiveChunk]

// JobsServiceServer is the server API for JobsService service.
// All implementations must embed UnimplementedJobsServiceServer
// for forward compatibility.
//
// JobsService is the user-session API. Runner capability callbacks are HTTP-only.
type JobsServiceServer interface {
	SubmitJob(context.Context, *SubmitJobRequest) (*JobAccepted, error)
	GetJob(context.Context, *JobTaskRequest) (*JobDetail, error)
	CancelJob(context.Context, *JobTaskRequest) (*emptypb.Empty, error)
	GetJobResults(context.Context, *JobTaskRequest) (*JobResults, error)
	DownloadJobResult(*JobArtifactRequest, grpc.ServerStreamingServer[ArchiveChunk]) error
	DownloadJobDelivery(*JobDeliveryRequest, grpc.ServerStreamingServer[ArchiveChunk]) error
	RetryJobDelivery(context.Context, *JobDeliveryRequest) (*emptypb.Empty, error)
	SetJobRetention(context.Context, *SetJobRetentionRequest) (*emptypb.Empty, error)
	GetJobStoragePolicy(context.Context, *emptypb.Empty) (*JobStoragePolicy, error)
	SetJobStoragePolicy(context.Context, *JobResultPolicy) (*emptypb.Empty, error)
	UploadJobDataset(grpc.ClientStreamingServer[UploadDatasetPart, JobArtifact]) error
	ListJobDatasets(context.Context, *ListJobDatasetsRequest) (*JobArtifacts, error)
	GetJobDataset(context.Context, *JobDatasetRequest) (*JobArtifact, error)
	DownloadJobDataset(*JobDatasetRequest, grpc.ServerStreamingServer[ArchiveChunk]) error
	mustEmbedUnimplementedJobsServiceServer()
}

// UnimplementedJobsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobsServiceServer struct{}

func (UnimplementedJobsServiceServer) SubmitJob(context.Context, *SubmitJobRequest) (*JobAccepted, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedJobsServiceServer) GetJob(context.Context, *JobTaskRequest) (*JobDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedJobsServiceServer) CancelJob(context.Context, *JobTaskRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedJobsServiceServer) GetJobResults(context.Context, *JobTaskRequest) (*JobResults, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobResults not implemented")
}
func (UnimplementedJobsServiceServer) DownloadJobResult(*JobArtifactRequest, grpc.ServerStreamingServer[ArchiveChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadJobResult not implemented")
}
func (UnimplementedJobsServiceServer) DownloadJobDelivery(*JobDeliveryRequest, grpc.ServerStreamingServer[ArchiveChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadJobDelivery not implemented")
}
func (UnimplementedJobsServiceServer) RetryJobDelivery(context.Context, *JobDeliveryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryJobDelivery not implemented")
}
func (UnimplementedJobsServiceServer) SetJobRetention(context.Context, *SetJobRetentionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetJobRetention not implemented")
}
func (UnimplementedJobsServiceServer) GetJobStoragePolicy(context.Context, *emptypb.Empty) (*JobStoragePolicy, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStoragePolicy not implemented")
}
func (UnimplementedJobsServiceServer) SetJobStoragePolicy(context.Context, *JobResultPolicy) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetJobStoragePolicy not implemented")
}
func (UnimplementedJobsServiceServer) UploadJobDataset(grpc.ClientStreamingServer[UploadDatasetPart, JobArtifact]) error {
	return status.Error(codes.Unimplemented, "method UploadJobDataset not implemented")
}
func (UnimplementedJobsServiceServer) ListJobDatasets(context.Context, *ListJobDatasetsRequest) (*JobArtifacts, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobDatasets not implemented")
}
func (UnimplementedJobsServiceServer) GetJobDataset(context.Context, *JobDatasetRequest) (*JobArtifact, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobDataset not implemented")
}
func (UnimplementedJobsServiceServer) DownloadJobDataset(*JobDatasetRequest, grpc.ServerStreamingServer[ArchiveChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadJobDataset not implemented")
}
func (UnimplementedJobsServiceServer) mustEmbedUnimplementedJobsServiceServer() {}
func (UnimplementedJobsServiceServer) testEmbeddedByValue()                     {}

// UnsafeJobsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobsServiceServer will
// result in compilation errors.
type UnsafeJobsServiceServer interface {
	mustEmbedUnimplementedJobsServiceServer()
}

func RegisterJobsServiceServer(s grpc.ServiceRegistrar, srv JobsServiceServer) {
	// If the following call panics, it indicates UnimplementedJobsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobsService_ServiceDesc, srv)
}

func _JobsService_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).GetJob(ctx, req.(*JobTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).CancelJob(ctx, req.(*JobTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_GetJobResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).GetJobResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_GetJobResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).GetJobResults(ctx, req.(*JobTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_DownloadJobResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServiceServer).DownloadJobResult(m, &grpc.GenericServerStream[JobArtifactRequest, ArchiveChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobsService_DownloadJobResultServer = grpc.ServerStreamingServer[ArchiveChunk]

func _JobsService_DownloadJobDelivery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobDeliveryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServiceServer).DownloadJobDelivery(m, &grpc.GenericServerStream[JobDeliveryRequest, ArchiveChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobsService_DownloadJobDeliveryServer = grpc.ServerStreamingServer[ArchiveChunk]

func _JobsService_RetryJobDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).RetryJobDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_RetryJobDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).RetryJobDelivery(ctx, req.(*JobDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_SetJobRetention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetJobRetentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).SetJobRetention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_SetJobRetention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).SetJobRetention(ctx, req.(*SetJobRetentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_GetJobStoragePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).GetJobStoragePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_GetJobStoragePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).GetJobStoragePolicy(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_SetJobStoragePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobResultPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).SetJobStoragePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_SetJobStoragePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).SetJobStoragePolicy(ctx, req.(*JobResultPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_UploadJobDataset_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JobsServiceServer).UploadJobDataset(&grpc.GenericServerStream[UploadDatasetPart, JobArtifact]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobsService_UploadJobDatasetServer = grpc.ClientStreamingServer[UploadDatasetPart, JobArtifact]

func _JobsService_ListJobDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).ListJobDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_ListJobDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).ListJobDatasets(ctx, req.(*ListJobDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_GetJobDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobsServiceServer).GetJobDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobsService_GetJobDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobsServiceServer).GetJobDataset(ctx, req.(*JobDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobsService_DownloadJobDataset_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobDatasetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobsServiceServer).DownloadJobDataset(m, &grpc.GenericServerStream[JobDatasetRequest, ArchiveChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobsService_DownloadJobDatasetServer = grpc.ServerStreamingServer[ArchiveChunk]

// JobsService_ServiceDesc is the grpc.ServiceDesc for JobsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eruun.v1.JobsService",
	HandlerType: (*JobsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _JobsService_SubmitJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _JobsService_GetJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _JobsService_CancelJob_Handler,
		},
		{
			MethodName: "GetJobResults",
			Handler:    _JobsService_GetJobResults_Handler,
		},
		{
			MethodName: "RetryJobDelivery",
			Handler:    _JobsService_RetryJobDelivery_Handler,
		},
		{
			MethodName: "SetJobRetention",
			Handler:    _JobsService_SetJobRetention_Handler,
		},
		{
			MethodName: "GetJobStoragePolicy",
			Handler:    _JobsService_GetJobStoragePolicy_Handler,
		},
		{
			MethodName: "SetJobStoragePolicy",
			Handler:    _JobsService_SetJobStoragePolicy_Handler,
		},
		{
			MethodName: "ListJobDatasets",
			Handler:    _JobsService_ListJobDatasets_Handler,
		},
		{
			MethodName: "GetJobDataset",
			Handler:    _JobsService_GetJobDataset_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadJobResult",
			Handler:       _JobsService_DownloadJobResult_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadJobDelivery",
			Handler:       _JobsService_DownloadJobDelivery_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadJobDataset",
			Handler:       _JobsService_UploadJobDataset_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadJobDataset",
			Handler:       _JobsService_DownloadJobDataset_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eruun/v1/jobs.proto",
}
