// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: eruun/v1/jobs.proto

package eruunv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// execution_key is required for Application workflow evaluation results.
// Standalone Jobs can omit it; CancelJob accepts only the parent task_id.
type JobTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecutionKey  string                 `protobuf:"bytes,2,opt,name=execution_key,json=executionKey,proto3" json:"execution_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobTaskRequest) Reset() {
	*x = JobTaskRequest{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTaskRequest) ProtoMessage() {}

func (x *JobTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTaskRequest.ProtoReflect.Descriptor instead.
func (*JobTaskRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *JobTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobTaskRequest) GetExecutionKey() string {
	if x != nil {
		return x.ExecutionKey
	}
	return ""
}

type JobArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ExecutionKey  string                 `protobuf:"bytes,3,opt,name=execution_key,json=executionKey,proto3" json:"execution_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobArtifactRequest) Reset() {
	*x = JobArtifactRequest{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobArtifactRequest) ProtoMessage() {}

func (x *JobArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobArtifactRequest.ProtoReflect.Descriptor instead.
func (*JobArtifactRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *JobArtifactRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *JobArtifactRequest) GetExecutionKey() string {
	if x != nil {
		return x.ExecutionKey
	}
	return ""
}

type JobDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	ExecutionKey  string                 `protobuf:"bytes,3,opt,name=execution_key,json=executionKey,proto3" json:"execution_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDeliveryRequest) Reset() {
	*x = JobDeliveryRequest{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDeliveryRequest) ProtoMessage() {}

func (x *JobDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDeliveryRequest.ProtoReflect.Descriptor instead.
func (*JobDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *JobDeliveryRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobDeliveryRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *JobDeliveryRequest) GetExecutionKey() string {
	if x != nil {
		return x.ExecutionKey
	}
	return ""
}

type JobDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetId     string                 `protobuf:"bytes,1,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDatasetRequest) Reset() {
	*x = JobDatasetRequest{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDatasetRequest) ProtoMessage() {}

func (x *JobDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDatasetRequest.ProtoReflect.Descriptor instead.
func (*JobDatasetRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *JobDatasetRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type SetJobRetentionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	RetentionDays int32                  `protobuf:"varint,2,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	ExecutionKey  string                 `protobuf:"bytes,3,opt,name=execution_key,json=executionKey,proto3" json:"execution_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJobRetentionRequest) Reset() {
	*x = SetJobRetentionRequest{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJobRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJobRetentionRequest) ProtoMessage() {}

func (x *SetJobRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJobRetentionRequest.ProtoReflect.Descriptor instead.
func (*SetJobRetentionRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{4}
}

func (x *SetJobRetentionRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SetJobRetentionRequest) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

func (x *SetJobRetentionRequest) GetExecutionKey() string {
	if x != nil {
		return x.ExecutionKey
	}
	return ""
}

type ListJobDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *int32                 `protobuf:"varint,1,opt,name=page,proto3,oneof" json:"page,omitempty"`
	PageSize      *int32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobDatasetsRequest) Reset() {
	*x = ListJobDatasetsRequest{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobDatasetsRequest) ProtoMessage() {}

func (x *ListJobDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListJobDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobDatasetsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ListJobDatasetsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type JobStoragePolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AvailableTargets []string               `protobuf:"bytes,1,rep,name=available_targets,json=availableTargets,proto3" json:"available_targets,omitempty"`
	Policy           *JobResultPolicy       `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *JobStoragePolicy) Reset() {
	*x = JobStoragePolicy{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStoragePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStoragePolicy) ProtoMessage() {}

func (x *JobStoragePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStoragePolicy.ProtoReflect.Descriptor instead.
func (*JobStoragePolicy) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{6}
}

func (x *JobStoragePolicy) GetAvailableTargets() []string {
	if x != nil {
		return x.AvailableTargets
	}
	return nil
}

func (x *JobStoragePolicy) GetPolicy() *JobResultPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type JobStorageTrait struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MountPath     string                 `protobuf:"bytes,3,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	SubPath       string                 `protobuf:"bytes,4,opt,name=sub_path,json=subPath,proto3" json:"sub_path,omitempty"`
	SubPathExpr   string                 `protobuf:"bytes,5,opt,name=sub_path_expr,json=subPathExpr,proto3" json:"sub_path_expr,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,6,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	SourceName    string                 `protobuf:"bytes,7,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	TmpCreate     bool                   `protobuf:"varint,8,opt,name=tmp_create,json=tmpCreate,proto3" json:"tmp_create,omitempty"`
	Size          string                 `protobuf:"bytes,9,opt,name=size,proto3" json:"size,omitempty"`
	ClaimName     string                 `protobuf:"bytes,10,opt,name=claim_name,json=claimName,proto3" json:"claim_name,omitempty"`
	StorageClass  string                 `protobuf:"bytes,11,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStorageTrait) Reset() {
	*x = JobStorageTrait{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStorageTrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStorageTrait) ProtoMessage() {}

func (x *JobStorageTrait) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStorageTrait.ProtoReflect.Descriptor instead.
func (*JobStorageTrait) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{7}
}

func (x *JobStorageTrait) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobStorageTrait) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobStorageTrait) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *JobStorageTrait) GetSubPath() string {
	if x != nil {
		return x.SubPath
	}
	return ""
}

func (x *JobStorageTrait) GetSubPathExpr() string {
	if x != nil {
		return x.SubPathExpr
	}
	return ""
}

func (x *JobStorageTrait) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *JobStorageTrait) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *JobStorageTrait) GetTmpCreate() bool {
	if x != nil {
		return x.TmpCreate
	}
	return false
}

func (x *JobStorageTrait) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *JobStorageTrait) GetClaimName() string {
	if x != nil {
		return x.ClaimName
	}
	return ""
}

func (x *JobStorageTrait) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

type JobResourceTrait struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu           string                 `protobuf:"bytes,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	CpuLimit      string                 `protobuf:"bytes,4,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   string                 `protobuf:"bytes,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResourceTrait) Reset() {
	*x = JobResourceTrait{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResourceTrait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResourceTrait) ProtoMessage() {}

func (x *JobResourceTrait) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResourceTrait.ProtoReflect.Descriptor instead.
func (*JobResourceTrait) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{8}
}

func (x *JobResourceTrait) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *JobResourceTrait) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *JobResourceTrait) GetGpu() string {
	if x != nil {
		return x.Gpu
	}
	return ""
}

func (x *JobResourceTrait) GetCpuLimit() string {
	if x != nil {
		return x.CpuLimit
	}
	return ""
}

func (x *JobResourceTrait) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

type JobSecretSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSecretSelector) Reset() {
	*x = JobSecretSelector{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSecretSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSecretSelector) ProtoMessage() {}

func (x *JobSecretSelector) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSecretSelector.ProtoReflect.Descriptor instead.
func (*JobSecretSelector) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{9}
}

func (x *JobSecretSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobSecretSelector) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type JobConfigSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobConfigSelector) Reset() {
	*x = JobConfigSelector{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobConfigSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobConfigSelector) ProtoMessage() {}

func (x *JobConfigSelector) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobConfigSelector.ProtoReflect.Descriptor instead.
func (*JobConfigSelector) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{10}
}

func (x *JobConfigSelector) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobConfigSelector) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type JobValueSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Static        *string                `protobuf:"bytes,1,opt,name=static,proto3,oneof" json:"static,omitempty"`
	Secret        *JobSecretSelector     `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Config        *JobConfigSelector     `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Field         *string                `protobuf:"bytes,4,opt,name=field,proto3,oneof" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobValueSource) Reset() {
	*x = JobValueSource{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobValueSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobValueSource) ProtoMessage() {}

func (x *JobValueSource) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobValueSource.ProtoReflect.Descriptor instead.
func (*JobValueSource) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{11}
}

func (x *JobValueSource) GetStatic() string {
	if x != nil && x.Static != nil {
		return *x.Static
	}
	return ""
}

func (x *JobValueSource) GetSecret() *JobSecretSelector {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *JobValueSource) GetConfig() *JobConfigSelector {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *JobValueSource) GetField() string {
	if x != nil && x.Field != nil {
		return *x.Field
	}
	return ""
}

type JobEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ValueFrom     *JobValueSource        `protobuf:"bytes,2,opt,name=value_from,json=valueFrom,proto3" json:"value_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEnv) Reset() {
	*x = JobEnv{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEnv) ProtoMessage() {}

func (x *JobEnv) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEnv.ProtoReflect.Descriptor instead.
func (*JobEnv) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{12}
}

func (x *JobEnv) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobEnv) GetValueFrom() *JobValueSource {
	if x != nil {
		return x.ValueFrom
	}
	return nil
}

type JobEnvFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	SourceName    string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobEnvFrom) Reset() {
	*x = JobEnvFrom{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEnvFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEnvFrom) ProtoMessage() {}

func (x *JobEnvFrom) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEnvFrom.ProtoReflect.Descriptor instead.
func (*JobEnvFrom) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{13}
}

func (x *JobEnvFrom) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobEnvFrom) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

type JobTraits struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Storage        []*JobStorageTrait          `protobuf:"bytes,1,rep,name=storage,proto3" json:"storage,omitempty"`
	EnvFrom        []*JobEnvFrom               `protobuf:"bytes,2,rep,name=env_from,json=envFrom,proto3" json:"env_from,omitempty"`
	Envs           []*JobEnv                   `protobuf:"bytes,3,rep,name=envs,proto3" json:"envs,omitempty"`
	TargetWorkEnv  map[string]string           `protobuf:"bytes,4,rep,name=target_work_env,json=targetWorkEnv,proto3" json:"target_work_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources      *JobResourceTrait           `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	SecurityPolicy *AppKubeCoreSecurityContext `protobuf:"bytes,6,opt,name=security_policy,json=securityPolicy,proto3" json:"security_policy,omitempty"`
	Eval           *EvaluationTrait            `protobuf:"bytes,7,opt,name=eval,proto3" json:"eval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JobTraits) Reset() {
	*x = JobTraits{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTraits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTraits) ProtoMessage() {}

func (x *JobTraits) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTraits.ProtoReflect.Descriptor instead.
func (*JobTraits) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{14}
}

func (x *JobTraits) GetStorage() []*JobStorageTrait {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *JobTraits) GetEnvFrom() []*JobEnvFrom {
	if x != nil {
		return x.EnvFrom
	}
	return nil
}

func (x *JobTraits) GetEnvs() []*JobEnv {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *JobTraits) GetTargetWorkEnv() map[string]string {
	if x != nil {
		return x.TargetWorkEnv
	}
	return nil
}

func (x *JobTraits) GetResources() *JobResourceTrait {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *JobTraits) GetSecurityPolicy() *AppKubeCoreSecurityContext {
	if x != nil {
		return x.SecurityPolicy
	}
	return nil
}

func (x *JobTraits) GetEval() *EvaluationTrait {
	if x != nil {
		return x.Eval
	}
	return nil
}

type SubmitJobRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type        string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Command inputs only. Evaluation Jobs use traits.eval and omit spec.
	Spec          *structpb.Value `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Traits        *JobTraits      `protobuf:"bytes,5,opt,name=traits,proto3" json:"traits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitJobRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *SubmitJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitJobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubmitJobRequest) GetSpec() *structpb.Value {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *SubmitJobRequest) GetTraits() *JobTraits {
	if x != nil {
		return x.Traits
	}
	return nil
}

type JobSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Spec          *structpb.Value        `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Traits        *JobTraits             `protobuf:"bytes,4,opt,name=traits,proto3" json:"traits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{16}
}

func (x *JobSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobSpec) GetSpec() *structpb.Value {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *JobSpec) GetTraits() *JobTraits {
	if x != nil {
		return x.Traits
	}
	return nil
}

type JobAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAccepted) Reset() {
	*x = JobAccepted{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAccepted) ProtoMessage() {}

func (x *JobAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAccepted.ProtoReflect.Descriptor instead.
func (*JobAccepted) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{17}
}

func (x *JobAccepted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobAccepted) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *JobAccepted) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobAccepted) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type JobExecution struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	WorkflowId         string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ProductId          string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	WorkspaceId        string                 `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	AppId              string                 `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	TaskId             string                 `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	StartTime          int64                  `protobuf:"varint,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            int64                  `protobuf:"varint,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Info               string                 `protobuf:"bytes,11,opt,name=info,proto3" json:"info,omitempty"`
	ServiceName        string                 `protobuf:"bytes,12,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Error              string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	Production         bool                   `protobuf:"varint,14,opt,name=production,proto3" json:"production,omitempty"`
	TargetEnv          string                 `protobuf:"bytes,15,opt,name=target_env,json=targetEnv,proto3" json:"target_env,omitempty"`
	ExecutionKey       *string                `protobuf:"bytes,16,opt,name=execution_key,json=executionKey,proto3,oneof" json:"execution_key,omitempty"`
	RunGeneration      uint64                 `protobuf:"varint,17,opt,name=run_generation,json=runGeneration,proto3" json:"run_generation,omitempty"`
	Attempt            uint32                 `protobuf:"varint,18,opt,name=attempt,proto3" json:"attempt,omitempty"`
	SchedulingState    string                 `protobuf:"bytes,19,opt,name=scheduling_state,json=schedulingState,proto3" json:"scheduling_state,omitempty"`
	SchedulingClass    string                 `protobuf:"bytes,20,opt,name=scheduling_class,json=schedulingClass,proto3" json:"scheduling_class,omitempty"`
	SchedulingPriority int32                  `protobuf:"varint,21,opt,name=scheduling_priority,json=schedulingPriority,proto3" json:"scheduling_priority,omitempty"`
	SchedulingQueuedAt *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=scheduling_queued_at,json=schedulingQueuedAt,proto3" json:"scheduling_queued_at,omitempty"`
	SchedulingReason   string                 `protobuf:"bytes,23,opt,name=scheduling_reason,json=schedulingReason,proto3" json:"scheduling_reason,omitempty"`
	CreateTime         *timestamppb.Timestamp `protobuf:"bytes,24,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime         *timestamppb.Timestamp `protobuf:"bytes,25,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobExecution) Reset() {
	*x = JobExecution{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobExecution) ProtoMessage() {}

func (x *JobExecution) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobExecution.ProtoReflect.Descriptor instead.
func (*JobExecution) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{18}
}

func (x *JobExecution) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobExecution) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobExecution) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *JobExecution) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *JobExecution) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *JobExecution) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *JobExecution) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobExecution) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *JobExecution) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *JobExecution) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *JobExecution) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *JobExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobExecution) GetProduction() bool {
	if x != nil {
		return x.Production
	}
	return false
}

func (x *JobExecution) GetTargetEnv() string {
	if x != nil {
		return x.TargetEnv
	}
	return ""
}

func (x *JobExecution) GetExecutionKey() string {
	if x != nil && x.ExecutionKey != nil {
		return *x.ExecutionKey
	}
	return ""
}

func (x *JobExecution) GetRunGeneration() uint64 {
	if x != nil {
		return x.RunGeneration
	}
	return 0
}

func (x *JobExecution) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobExecution) GetSchedulingState() string {
	if x != nil {
		return x.SchedulingState
	}
	return ""
}

func (x *JobExecution) GetSchedulingClass() string {
	if x != nil {
		return x.SchedulingClass
	}
	return ""
}

func (x *JobExecution) GetSchedulingPriority() int32 {
	if x != nil {
		return x.SchedulingPriority
	}
	return 0
}

func (x *JobExecution) GetSchedulingQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SchedulingQueuedAt
	}
	return nil
}

func (x *JobExecution) GetSchedulingReason() string {
	if x != nil {
		return x.SchedulingReason
	}
	return ""
}

func (x *JobExecution) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *JobExecution) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type JobArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Digest        string                 `protobuf:"bytes,6,opt,name=digest,proto3" json:"digest,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Manifest      *structpb.Value        `protobuf:"bytes,8,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Summary       *structpb.Value        `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	Reference     string                 `protobuf:"bytes,10,opt,name=reference,proto3" json:"reference,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Expired       bool                   `protobuf:"varint,12,opt,name=expired,proto3" json:"expired,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ExecutionKey  string                 `protobuf:"bytes,15,opt,name=execution_key,json=executionKey,proto3" json:"execution_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobArtifact) Reset() {
	*x = JobArtifact{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobArtifact) ProtoMessage() {}

func (x *JobArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobArtifact.ProtoReflect.Descriptor instead.
func (*JobArtifact) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{19}
}

func (x *JobArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobArtifact) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *JobArtifact) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobArtifact) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *JobArtifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobArtifact) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *JobArtifact) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *JobArtifact) GetManifest() *structpb.Value {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *JobArtifact) GetSummary() *structpb.Value {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *JobArtifact) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *JobArtifact) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *JobArtifact) GetExpired() bool {
	if x != nil {
		return x.Expired
	}
	return false
}

func (x *JobArtifact) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *JobArtifact) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *JobArtifact) GetExecutionKey() string {
	if x != nil {
		return x.ExecutionKey
	}
	return ""
}

type JobDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Attempts      int32                  `protobuf:"varint,8,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	Reference     string                 `protobuf:"bytes,10,opt,name=reference,proto3" json:"reference,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	ExecutionKey  string                 `protobuf:"bytes,13,opt,name=execution_key,json=executionKey,proto3" json:"execution_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDelivery) Reset() {
	*x = JobDelivery{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDelivery) ProtoMessage() {}

func (x *JobDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDelivery.ProtoReflect.Descriptor instead.
func (*JobDelivery) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{20}
}

func (x *JobDelivery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobDelivery) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *JobDelivery) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *JobDelivery) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *JobDelivery) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *JobDelivery) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *JobDelivery) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobDelivery) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *JobDelivery) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobDelivery) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *JobDelivery) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *JobDelivery) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *JobDelivery) GetExecutionKey() string {
	if x != nil {
		return x.ExecutionKey
	}
	return ""
}

type JobRunnerProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompletedTrials int32                  `protobuf:"varint,1,opt,name=completed_trials,json=completedTrials,proto3" json:"completed_trials,omitempty"`
	TotalTrials     int32                  `protobuf:"varint,2,opt,name=total_trials,json=totalTrials,proto3" json:"total_trials,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobRunnerProgress) Reset() {
	*x = JobRunnerProgress{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRunnerProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRunnerProgress) ProtoMessage() {}

func (x *JobRunnerProgress) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRunnerProgress.ProtoReflect.Descriptor instead.
func (*JobRunnerProgress) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{21}
}

func (x *JobRunnerProgress) GetCompletedTrials() int32 {
	if x != nil {
		return x.CompletedTrials
	}
	return 0
}

func (x *JobRunnerProgress) GetTotalTrials() int32 {
	if x != nil {
		return x.TotalTrials
	}
	return 0
}

type JobRunnerTerminal struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Outcome            string                 `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	ExitCode           *int32                 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Signal             string                 `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	ArtifactId         string                 `protobuf:"bytes,4,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ArtifactDigest     string                 `protobuf:"bytes,5,opt,name=artifact_digest,json=artifactDigest,proto3" json:"artifact_digest,omitempty"`
	CollectionComplete bool                   `protobuf:"varint,6,opt,name=collection_complete,json=collectionComplete,proto3" json:"collection_complete,omitempty"`
	Reason             string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobRunnerTerminal) Reset() {
	*x = JobRunnerTerminal{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRunnerTerminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRunnerTerminal) ProtoMessage() {}

func (x *JobRunnerTerminal) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRunnerTerminal.ProtoReflect.Descriptor instead.
func (*JobRunnerTerminal) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{22}
}

func (x *JobRunnerTerminal) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *JobRunnerTerminal) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *JobRunnerTerminal) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *JobRunnerTerminal) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *JobRunnerTerminal) GetArtifactDigest() string {
	if x != nil {
		return x.ArtifactDigest
	}
	return ""
}

func (x *JobRunnerTerminal) GetCollectionComplete() bool {
	if x != nil {
		return x.CollectionComplete
	}
	return false
}

func (x *JobRunnerTerminal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *JobRunnerTerminal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JobRunnerStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Phase           string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Sequence        uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	Stale           bool                   `protobuf:"varint,4,opt,name=stale,proto3" json:"stale,omitempty"`
	Progress        *JobRunnerProgress     `protobuf:"bytes,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Terminal        *JobRunnerTerminal     `protobuf:"bytes,6,opt,name=terminal,proto3" json:"terminal,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobRunnerStatus) Reset() {
	*x = JobRunnerStatus{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRunnerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRunnerStatus) ProtoMessage() {}

func (x *JobRunnerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRunnerStatus.ProtoReflect.Descriptor instead.
func (*JobRunnerStatus) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{23}
}

func (x *JobRunnerStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *JobRunnerStatus) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *JobRunnerStatus) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *JobRunnerStatus) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

func (x *JobRunnerStatus) GetProgress() *JobRunnerProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *JobRunnerStatus) GetTerminal() *JobRunnerTerminal {
	if x != nil {
		return x.Terminal
	}
	return nil
}

// Sandbox lifecycle observation; ready is not proof that a trial executed.
type JobSandboxStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrialId       string                 `protobuf:"bytes,1,opt,name=trial_id,json=trialId,proto3" json:"trial_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Admitted      bool                   `protobuf:"varint,3,opt,name=admitted,proto3" json:"admitted,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SandboxName   string                 `protobuf:"bytes,5,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	SandboxUid    string                 `protobuf:"bytes,6,opt,name=sandbox_uid,json=sandboxUID,proto3" json:"sandbox_uid,omitempty"`
	PodName       string                 `protobuf:"bytes,7,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid        string                 `protobuf:"bytes,8,opt,name=pod_uid,json=podUID,proto3" json:"pod_uid,omitempty"`
	ContainerName string                 `protobuf:"bytes,9,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	RetainUntil   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=retain_until,json=retainUntil,proto3" json:"retain_until,omitempty"`
	Reason        string                 `protobuf:"bytes,11,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSandboxStatus) Reset() {
	*x = JobSandboxStatus{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSandboxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSandboxStatus) ProtoMessage() {}

func (x *JobSandboxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSandboxStatus.ProtoReflect.Descriptor instead.
func (*JobSandboxStatus) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{24}
}

func (x *JobSandboxStatus) GetTrialId() string {
	if x != nil {
		return x.TrialId
	}
	return ""
}

func (x *JobSandboxStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobSandboxStatus) GetAdmitted() bool {
	if x != nil {
		return x.Admitted
	}
	return false
}

func (x *JobSandboxStatus) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *JobSandboxStatus) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *JobSandboxStatus) GetSandboxUid() string {
	if x != nil {
		return x.SandboxUid
	}
	return ""
}

func (x *JobSandboxStatus) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *JobSandboxStatus) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *JobSandboxStatus) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *JobSandboxStatus) GetRetainUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.RetainUntil
	}
	return nil
}

func (x *JobSandboxStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type JobDetail struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Accepted           *JobAccepted           `protobuf:"bytes,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Job                *JobSpec               `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Executions         []*JobExecution        `protobuf:"bytes,3,rep,name=executions,proto3" json:"executions,omitempty"`
	Results            []*JobArtifact         `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	Deliveries         []*JobDelivery         `protobuf:"bytes,5,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	CollectionState    string                 `protobuf:"bytes,6,opt,name=collection_state,json=collectionState,proto3" json:"collection_state,omitempty"`
	RunnerStatus       *JobRunnerStatus       `protobuf:"bytes,7,opt,name=runner_status,json=runnerStatus,proto3" json:"runner_status,omitempty"`
	ExecutionKey       string                 `protobuf:"bytes,8,opt,name=execution_key,json=executionKey,proto3" json:"execution_key,omitempty"`
	FrameworkVersion   string                 `protobuf:"bytes,9,opt,name=framework_version,json=frameworkVersion,proto3" json:"framework_version,omitempty"`
	Sandboxes          []*JobSandboxStatus    `protobuf:"bytes,10,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	SandboxesTruncated bool                   `protobuf:"varint,11,opt,name=sandboxes_truncated,json=sandboxesTruncated,proto3" json:"sandboxes_truncated,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobDetail) Reset() {
	*x = JobDetail{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetail) ProtoMessage() {}

func (x *JobDetail) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetail.ProtoReflect.Descriptor instead.
func (*JobDetail) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{25}
}

func (x *JobDetail) GetAccepted() *JobAccepted {
	if x != nil {
		return x.Accepted
	}
	return nil
}

func (x *JobDetail) GetJob() *JobSpec {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *JobDetail) GetExecutions() []*JobExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *JobDetail) GetResults() []*JobArtifact {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *JobDetail) GetDeliveries() []*JobDelivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *JobDetail) GetCollectionState() string {
	if x != nil {
		return x.CollectionState
	}
	return ""
}

func (x *JobDetail) GetRunnerStatus() *JobRunnerStatus {
	if x != nil {
		return x.RunnerStatus
	}
	return nil
}

func (x *JobDetail) GetExecutionKey() string {
	if x != nil {
		return x.ExecutionKey
	}
	return ""
}

func (x *JobDetail) GetFrameworkVersion() string {
	if x != nil {
		return x.FrameworkVersion
	}
	return ""
}

func (x *JobDetail) GetSandboxes() []*JobSandboxStatus {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

func (x *JobDetail) GetSandboxesTruncated() bool {
	if x != nil {
		return x.SandboxesTruncated
	}
	return false
}

type JobResults struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CollectionState string                 `protobuf:"bytes,1,opt,name=collection_state,json=collectionState,proto3" json:"collection_state,omitempty"`
	Artifacts       []*JobArtifact         `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Deliveries      []*JobDelivery         `protobuf:"bytes,3,rep,name=deliveries,proto3" json:"deliveries,omitempty"`
	ExecutionKey    string                 `protobuf:"bytes,4,opt,name=execution_key,json=executionKey,proto3" json:"execution_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobResults) Reset() {
	*x = JobResults{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResults) ProtoMessage() {}

func (x *JobResults) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResults.ProtoReflect.Descriptor instead.
func (*JobResults) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{26}
}

func (x *JobResults) GetCollectionState() string {
	if x != nil {
		return x.CollectionState
	}
	return ""
}

func (x *JobResults) GetArtifacts() []*JobArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *JobResults) GetDeliveries() []*JobDelivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

func (x *JobResults) GetExecutionKey() string {
	if x != nil {
		return x.ExecutionKey
	}
	return ""
}

type JobArtifacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*JobArtifact         `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobArtifacts) Reset() {
	*x = JobArtifacts{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobArtifacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobArtifacts) ProtoMessage() {}

func (x *JobArtifacts) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobArtifacts.ProtoReflect.Descriptor instead.
func (*JobArtifacts) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{27}
}

func (x *JobArtifacts) GetArtifacts() []*JobArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type UploadDatasetHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDatasetHeader) Reset() {
	*x = UploadDatasetHeader{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDatasetHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDatasetHeader) ProtoMessage() {}

func (x *UploadDatasetHeader) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDatasetHeader.ProtoReflect.Descriptor instead.
func (*UploadDatasetHeader) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{28}
}

func (x *UploadDatasetHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UploadDatasetPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Part:
	//
	//	*UploadDatasetPart_Header
	//	*UploadDatasetPart_Chunk
	Part          isUploadDatasetPart_Part `protobuf_oneof:"part"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDatasetPart) Reset() {
	*x = UploadDatasetPart{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDatasetPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDatasetPart) ProtoMessage() {}

func (x *UploadDatasetPart) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDatasetPart.ProtoReflect.Descriptor instead.
func (*UploadDatasetPart) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{29}
}

func (x *UploadDatasetPart) GetPart() isUploadDatasetPart_Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *UploadDatasetPart) GetHeader() *UploadDatasetHeader {
	if x != nil {
		if x, ok := x.Part.(*UploadDatasetPart_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *UploadDatasetPart) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Part.(*UploadDatasetPart_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadDatasetPart_Part interface {
	isUploadDatasetPart_Part()
}

type UploadDatasetPart_Header struct {
	Header *UploadDatasetHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type UploadDatasetPart_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadDatasetPart_Header) isUploadDatasetPart_Part() {}

func (*UploadDatasetPart_Chunk) isUploadDatasetPart_Part() {}

type ArchiveChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveChunk) Reset() {
	*x = ArchiveChunk{}
	mi := &file_eruun_v1_jobs_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveChunk) ProtoMessage() {}

func (x *ArchiveChunk) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_jobs_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveChunk.ProtoReflect.Descriptor instead.
func (*ArchiveChunk) Descriptor() ([]byte, []int) {
	return file_eruun_v1_jobs_proto_rawDescGZIP(), []int{30}
}

func (x *ArchiveChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_eruun_v1_jobs_proto protoreflect.FileDescriptor

const file_eruun_v1_jobs_proto_rawDesc = "" +
	"\n" +
	"\x13eruun/v1/jobs.proto\x12\beruun.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1beruun/v1/applications.proto\"N\n" +
	"\x0eJobTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rexecution_key\x18\x02 \x01(\tR\fexecutionKey\"s\n" +
	"\x12JobArtifactRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12#\n" +
	"\rexecution_key\x18\x03 \x01(\tR\fexecutionKey\"j\n" +
	"\x12JobDeliveryRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12#\n" +
	"\rexecution_key\x18\x03 \x01(\tR\fexecutionKey\"2\n" +
	"\x11JobDatasetRequest\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x01 \x01(\tR\tdatasetId\"}\n" +
	"\x16SetJobRetentionRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x0eretention_days\x18\x02 \x01(\x05R\rretentionDays\x12#\n" +
	"\rexecution_key\x18\x03 \x01(\tR\fexecutionKey\"j\n" +
	"\x16ListJobDatasetsRequest\x12\x17\n" +
	"\x04page\x18\x01 \x01(\x05H\x00R\x04page\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x02 \x01(\x05H\x01R\bpageSize\x88\x01\x01B\a\n" +
	"\x05_pageB\f\n" +
	"\n" +
	"_page_size\"r\n" +
	"\x10JobStoragePolicy\x12+\n" +
	"\x11available_targets\x18\x01 \x03(\tR\x10availableTargets\x121\n" +
	"\x06policy\x18\x02 \x01(\v2\x19.eruun.v1.JobResultPolicyR\x06policy\"\xcc\x02\n" +
	"\x0fJobStorageTrait\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x03 \x01(\tR\tmountPath\x12\x19\n" +
	"\bsub_path\x18\x04 \x01(\tR\asubPath\x12\"\n" +
	"\rsub_path_expr\x18\x05 \x01(\tR\vsubPathExpr\x12\x1b\n" +
	"\tread_only\x18\x06 \x01(\bR\breadOnly\x12\x1f\n" +
	"\vsource_name\x18\a \x01(\tR\n" +
	"sourceName\x12\x1d\n" +
	"\n" +
	"tmp_create\x18\b \x01(\bR\ttmpCreate\x12\x12\n" +
	"\x04size\x18\t \x01(\tR\x04size\x12\x1d\n" +
	"\n" +
	"claim_name\x18\n" +
	" \x01(\tR\tclaimName\x12#\n" +
	"\rstorage_class\x18\v \x01(\tR\fstorageClass\"\x8e\x01\n" +
	"\x10JobResourceTrait\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\tR\x03gpu\x12\x1b\n" +
	"\tcpu_limit\x18\x04 \x01(\tR\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\tR\vmemoryLimit\"9\n" +
	"\x11JobSecretSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"9\n" +
	"\x11JobConfigSelector\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xc7\x01\n" +
	"\x0eJobValueSource\x12\x1b\n" +
	"\x06static\x18\x01 \x01(\tH\x00R\x06static\x88\x01\x01\x123\n" +
	"\x06secret\x18\x02 \x01(\v2\x1b.eruun.v1.JobSecretSelectorR\x06secret\x123\n" +
	"\x06config\x18\x03 \x01(\v2\x1b.eruun.v1.JobConfigSelectorR\x06config\x12\x19\n" +
	"\x05field\x18\x04 \x01(\tH\x01R\x05field\x88\x01\x01B\t\n" +
	"\a_staticB\b\n" +
	"\x06_field\"U\n" +
	"\x06JobEnv\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\n" +
	"value_from\x18\x02 \x01(\v2\x18.eruun.v1.JobValueSourceR\tvalueFrom\"A\n" +
	"\n" +
	"JobEnvFrom\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\"\xe1\x03\n" +
	"\tJobTraits\x123\n" +
	"\astorage\x18\x01 \x03(\v2\x19.eruun.v1.JobStorageTraitR\astorage\x12/\n" +
	"\benv_from\x18\x02 \x03(\v2\x14.eruun.v1.JobEnvFromR\aenvFrom\x12$\n" +
	"\x04envs\x18\x03 \x03(\v2\x10.eruun.v1.JobEnvR\x04envs\x12N\n" +
	"\x0ftarget_work_env\x18\x04 \x03(\v2&.eruun.v1.JobTraits.TargetWorkEnvEntryR\rtargetWorkEnv\x128\n" +
	"\tresources\x18\x05 \x01(\v2\x1a.eruun.v1.JobResourceTraitR\tresources\x12M\n" +
	"\x0fsecurity_policy\x18\x06 \x01(\v2$.eruun.v1.AppKubeCoreSecurityContextR\x0esecurityPolicy\x12-\n" +
	"\x04eval\x18\a \x01(\v2\x19.eruun.v1.EvaluationTraitR\x04eval\x1a@\n" +
	"\x12TargetWorkEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x10SubmitJobRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12*\n" +
	"\x04spec\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x04spec\x12+\n" +
	"\x06traits\x18\x05 \x01(\v2\x13.eruun.v1.JobTraitsR\x06traitsJ\x04\b\x06\x10\aR\rresult_policy\"\x9f\x01\n" +
	"\aJobSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12*\n" +
	"\x04spec\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x04spec\x12+\n" +
	"\x06traits\x18\x04 \x01(\v2\x13.eruun.v1.JobTraitsR\x06traitsJ\x04\b\x05\x10\x06R\rresult_policy\"u\n" +
	"\vJobAccepted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x9c\a\n" +
	"\fJobExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\tR\vworkspaceId\x12\x15\n" +
	"\x06app_id\x18\x06 \x01(\tR\x05appId\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\n" +
	" \x01(\x03R\aendTime\x12\x12\n" +
	"\x04info\x18\v \x01(\tR\x04info\x12!\n" +
	"\fservice_name\x18\f \x01(\tR\vserviceName\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"production\x18\x0e \x01(\bR\n" +
	"production\x12\x1d\n" +
	"\n" +
	"target_env\x18\x0f \x01(\tR\ttargetEnv\x12(\n" +
	"\rexecution_key\x18\x10 \x01(\tH\x00R\fexecutionKey\x88\x01\x01\x12%\n" +
	"\x0erun_generation\x18\x11 \x01(\x04R\rrunGeneration\x12\x18\n" +
	"\aattempt\x18\x12 \x01(\rR\aattempt\x12)\n" +
	"\x10scheduling_state\x18\x13 \x01(\tR\x0fschedulingState\x12)\n" +
	"\x10scheduling_class\x18\x14 \x01(\tR\x0fschedulingClass\x12/\n" +
	"\x13scheduling_priority\x18\x15 \x01(\x05R\x12schedulingPriority\x12L\n" +
	"\x14scheduling_queued_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\x12schedulingQueuedAt\x12+\n" +
	"\x11scheduling_reason\x18\x17 \x01(\tR\x10schedulingReason\x12;\n" +
	"\vcreate_time\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTimeB\x10\n" +
	"\x0e_execution_key\"\xa5\x04\n" +
	"\vJobArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06digest\x18\x06 \x01(\tR\x06digest\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x122\n" +
	"\bmanifest\x18\b \x01(\v2\x16.google.protobuf.ValueR\bmanifest\x120\n" +
	"\asummary\x18\t \x01(\v2\x16.google.protobuf.ValueR\asummary\x12\x1c\n" +
	"\treference\x18\n" +
	" \x01(\tR\treference\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\aexpired\x18\f \x01(\bR\aexpired\x12;\n" +
	"\vcreate_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12#\n" +
	"\rexecution_key\x18\x0f \x01(\tR\fexecutionKey\"\xa7\x03\n" +
	"\vJobDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x1a\n" +
	"\battempts\x18\b \x01(\x05R\battempts\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12\x1c\n" +
	"\treference\x18\n" +
	" \x01(\tR\treference\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12#\n" +
	"\rexecution_key\x18\r \x01(\tR\fexecutionKey\"a\n" +
	"\x11JobRunnerProgress\x12)\n" +
	"\x10completed_trials\x18\x01 \x01(\x05R\x0fcompletedTrials\x12!\n" +
	"\ftotal_trials\x18\x02 \x01(\x05R\vtotalTrials\"\xa2\x02\n" +
	"\x11JobRunnerTerminal\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\x12 \n" +
	"\texit_code\x18\x02 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12\x16\n" +
	"\x06signal\x18\x03 \x01(\tR\x06signal\x12\x1f\n" +
	"\vartifact_id\x18\x04 \x01(\tR\n" +
	"artifactId\x12'\n" +
	"\x0fartifact_digest\x18\x05 \x01(\tR\x0eartifactDigest\x12/\n" +
	"\x13collection_complete\x18\x06 \x01(\bR\x12collectionComplete\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessageB\f\n" +
	"\n" +
	"_exit_code\"\x93\x02\n" +
	"\x0fJobRunnerStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12F\n" +
	"\x11last_heartbeat_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x12\x14\n" +
	"\x05stale\x18\x04 \x01(\bR\x05stale\x127\n" +
	"\bprogress\x18\x05 \x01(\v2\x1b.eruun.v1.JobRunnerProgressR\bprogress\x127\n" +
	"\bterminal\x18\x06 \x01(\v2\x1b.eruun.v1.JobRunnerTerminalR\bterminal\"\xf3\x02\n" +
	"\x10JobSandboxStatus\x12\x19\n" +
	"\btrial_id\x18\x01 \x01(\tR\atrialId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1a\n" +
	"\badmitted\x18\x03 \x01(\bR\badmitted\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12!\n" +
	"\fsandbox_name\x18\x05 \x01(\tR\vsandboxName\x12\x1f\n" +
	"\vsandbox_uid\x18\x06 \x01(\tR\n" +
	"sandboxUID\x12\x19\n" +
	"\bpod_name\x18\a \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\b \x01(\tR\x06podUID\x12%\n" +
	"\x0econtainer_name\x18\t \x01(\tR\rcontainerName\x12=\n" +
	"\fretain_until\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vretainUntil\x12\x16\n" +
	"\x06reason\x18\v \x01(\tR\x06reason\"\xab\x04\n" +
	"\tJobDetail\x121\n" +
	"\baccepted\x18\x01 \x01(\v2\x15.eruun.v1.JobAcceptedR\baccepted\x12#\n" +
	"\x03job\x18\x02 \x01(\v2\x11.eruun.v1.JobSpecR\x03job\x126\n" +
	"\n" +
	"executions\x18\x03 \x03(\v2\x16.eruun.v1.JobExecutionR\n" +
	"executions\x12/\n" +
	"\aresults\x18\x04 \x03(\v2\x15.eruun.v1.JobArtifactR\aresults\x125\n" +
	"\n" +
	"deliveries\x18\x05 \x03(\v2\x15.eruun.v1.JobDeliveryR\n" +
	"deliveries\x12)\n" +
	"\x10collection_state\x18\x06 \x01(\tR\x0fcollectionState\x12>\n" +
	"\rrunner_status\x18\a \x01(\v2\x19.eruun.v1.JobRunnerStatusR\frunnerStatus\x12#\n" +
	"\rexecution_key\x18\b \x01(\tR\fexecutionKey\x12+\n" +
	"\x11framework_version\x18\t \x01(\tR\x10frameworkVersion\x128\n" +
	"\tsandboxes\x18\n" +
	" \x03(\v2\x1a.eruun.v1.JobSandboxStatusR\tsandboxes\x12/\n" +
	"\x13sandboxes_truncated\x18\v \x01(\bR\x12sandboxesTruncated\"\xc8\x01\n" +
	"\n" +
	"JobResults\x12)\n" +
	"\x10collection_state\x18\x01 \x01(\tR\x0fcollectionState\x123\n" +
	"\tartifacts\x18\x02 \x03(\v2\x15.eruun.v1.JobArtifactR\tartifacts\x125\n" +
	"\n" +
	"deliveries\x18\x03 \x03(\v2\x15.eruun.v1.JobDeliveryR\n" +
	"deliveries\x12#\n" +
	"\rexecution_key\x18\x04 \x01(\tR\fexecutionKey\"C\n" +
	"\fJobArtifacts\x123\n" +
	"\tartifacts\x18\x01 \x03(\v2\x15.eruun.v1.JobArtifactR\tartifacts\")\n" +
	"\x13UploadDatasetHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"l\n" +
	"\x11UploadDatasetPart\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1d.eruun.v1.UploadDatasetHeaderH\x00R\x06header\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04part\"\"\n" +
	"\fArchiveChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2\xf7\a\n" +
	"\vJobsService\x12>\n" +
	"\tSubmitJob\x12\x1a.eruun.v1.SubmitJobRequest\x1a\x15.eruun.v1.JobAccepted\x127\n" +
	"\x06GetJob\x12\x18.eruun.v1.JobTaskRequest\x1a\x13.eruun.v1.JobDetail\x12=\n" +
	"\tCancelJob\x12\x18.eruun.v1.JobTaskRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rGetJobResults\x12\x18.eruun.v1.JobTaskRequest\x1a\x14.eruun.v1.JobResults\x12K\n" +
	"\x11DownloadJobResult\x12\x1c.eruun.v1.JobArtifactRequest\x1a\x16.eruun.v1.ArchiveChunk0\x01\x12M\n" +
	"\x13DownloadJobDelivery\x12\x1c.eruun.v1.JobDeliveryRequest\x1a\x16.eruun.v1.ArchiveChunk0\x01\x12H\n" +
	"\x10RetryJobDelivery\x12\x1c.eruun.v1.JobDeliveryRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x0fSetJobRetention\x12 .eruun.v1.SetJobRetentionRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x13GetJobStoragePolicy\x12\x16.google.protobuf.Empty\x1a\x1a.eruun.v1.JobStoragePolicy\x12H\n" +
	"\x13SetJobStoragePolicy\x12\x19.eruun.v1.JobResultPolicy\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x10UploadJobDataset\x12\x1b.eruun.v1.UploadDatasetPart\x1a\x15.eruun.v1.JobArtifact(\x01\x12K\n" +
	"\x0fListJobDatasets\x12 .eruun.v1.ListJobDatasetsRequest\x1a\x16.eruun.v1.JobArtifacts\x12C\n" +
	"\rGetJobDataset\x12\x1b.eruun.v1.JobDatasetRequest\x1a\x15.eruun.v1.JobArtifact\x12K\n" +
	"\x12DownloadJobDataset\x12\x1b.eruun.v1.JobDatasetRequest\x1a\x16.eruun.v1.ArchiveChunk0\x01BIZGgithub.com/PixelCores/Eruun/pkg/apiserver/interfaces/grpc/pb/v1;eruunv1b\x06proto3"

var (
	file_eruun_v1_jobs_proto_rawDescOnce sync.Once
	file_eruun_v1_jobs_proto_rawDescData []byte
)

func file_eruun_v1_jobs_proto_rawDescGZIP() []byte {
	file_eruun_v1_jobs_proto_rawDescOnce.Do(func() {
		file_eruun_v1_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eruun_v1_jobs_proto_rawDesc), len(file_eruun_v1_jobs_proto_rawDesc)))
	})
	return file_eruun_v1_jobs_proto_rawDescData
}

var file_eruun_v1_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_eruun_v1_jobs_proto_goTypes = []any{
	(*JobTaskRequest)(nil),             // 0: eruun.v1.JobTaskRequest
	(*JobArtifactRequest)(nil),         // 1: eruun.v1.JobArtifactRequest
	(*JobDeliveryRequest)(nil),         // 2: eruun.v1.JobDeliveryRequest
	(*JobDatasetRequest)(nil),          // 3: eruun.v1.JobDatasetRequest
	(*SetJobRetentionRequest)(nil),     // 4: eruun.v1.SetJobRetentionRequest
	(*ListJobDatasetsRequest)(nil),     // 5: eruun.v1.ListJobDatasetsRequest
	(*JobStoragePolicy)(nil),           // 6: eruun.v1.JobStoragePolicy
	(*JobStorageTrait)(nil),            // 7: eruun.v1.JobStorageTrait
	(*JobResourceTrait)(nil),           // 8: eruun.v1.JobResourceTrait
	(*JobSecretSelector)(nil),          // 9: eruun.v1.JobSecretSelector
	(*JobConfigSelector)(nil),          // 10: eruun.v1.JobConfigSelector
	(*JobValueSource)(nil),             // 11: eruun.v1.JobValueSource
	(*JobEnv)(nil),                     // 12: eruun.v1.JobEnv
	(*JobEnvFrom)(nil),                 // 13: eruun.v1.JobEnvFrom
	(*JobTraits)(nil),                  // 14: eruun.v1.JobTraits
	(*SubmitJobRequest)(nil),           // 15: eruun.v1.SubmitJobRequest
	(*JobSpec)(nil),                    // 16: eruun.v1.JobSpec
	(*JobAccepted)(nil),                // 17: eruun.v1.JobAccepted
	(*JobExecution)(nil),               // 18: eruun.v1.JobExecution
	(*JobArtifact)(nil),                // 19: eruun.v1.JobArtifact
	(*JobDelivery)(nil),                // 20: eruun.v1.JobDelivery
	(*JobRunnerProgress)(nil),          // 21: eruun.v1.JobRunnerProgress
	(*JobRunnerTerminal)(nil),          // 22: eruun.v1.JobRunnerTerminal
	(*JobRunnerStatus)(nil),            // 23: eruun.v1.JobRunnerStatus
	(*JobSandboxStatus)(nil),           // 24: eruun.v1.JobSandboxStatus
	(*JobDetail)(nil),                  // 25: eruun.v1.JobDetail
	(*JobResults)(nil),                 // 26: eruun.v1.JobResults
	(*JobArtifacts)(nil),               // 27: eruun.v1.JobArtifacts
	(*UploadDatasetHeader)(nil),        // 28: eruun.v1.UploadDatasetHeader
	(*UploadDatasetPart)(nil),          // 29: eruun.v1.UploadDatasetPart
	(*ArchiveChunk)(nil),               // 30: eruun.v1.ArchiveChunk
	nil,                                // 31: eruun.v1.JobTraits.TargetWorkEnvEntry
	(*JobResultPolicy)(nil),            // 32: eruun.v1.JobResultPolicy
	(*AppKubeCoreSecurityContext)(nil), // 33: eruun.v1.AppKubeCoreSecurityContext
	(*EvaluationTrait)(nil),            // 34: eruun.v1.EvaluationTrait
	(*structpb.Value)(nil),             // 35: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),      // 36: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 37: google.protobuf.Empty
}
var file_eruun_v1_jobs_proto_depIdxs = []int32{
	32, // 0: eruun.v1.JobStoragePolicy.policy:type_name -> eruun.v1.JobResultPolicy
	9,  // 1: eruun.v1.JobValueSource.secret:type_name -> eruun.v1.JobSecretSelector
	10, // 2: eruun.v1.JobValueSource.config:type_name -> eruun.v1.JobConfigSelector
	11, // 3: eruun.v1.JobEnv.value_from:type_name -> eruun.v1.JobValueSource
	7,  // 4: eruun.v1.JobTraits.storage:type_name -> eruun.v1.JobStorageTrait
	13, // 5: eruun.v1.JobTraits.env_from:type_name -> eruun.v1.JobEnvFrom
	12, // 6: eruun.v1.JobTraits.envs:type_name -> eruun.v1.JobEnv
	31, // 7: eruun.v1.JobTraits.target_work_env:type_name -> eruun.v1.JobTraits.TargetWorkEnvEntry
	8,  // 8: eruun.v1.JobTraits.resources:type_name -> eruun.v1.JobResourceTrait
	33, // 9: eruun.v1.JobTraits.security_policy:type_name -> eruun.v1.AppKubeCoreSecurityContext
	34, // 10: eruun.v1.JobTraits.eval:type_name -> eruun.v1.EvaluationTrait
	35, // 11: eruun.v1.SubmitJobRequest.spec:type_name -> google.protobuf.Value
	14, // 12: eruun.v1.SubmitJobRequest.traits:type_name -> eruun.v1.JobTraits
	35, // 13: eruun.v1.JobSpec.spec:type_name -> google.protobuf.Value
	14, // 14: eruun.v1.JobSpec.traits:type_name -> eruun.v1.JobTraits
	36, // 15: eruun.v1.JobExecution.scheduling_queued_at:type_name -> google.protobuf.Timestamp
	36, // 16: eruun.v1.JobExecution.create_time:type_name -> google.protobuf.Timestamp
	36, // 17: eruun.v1.JobExecution.update_time:type_name -> google.protobuf.Timestamp
	35, // 18: eruun.v1.JobArtifact.manifest:type_name -> google.protobuf.Value
	35, // 19: eruun.v1.JobArtifact.summary:type_name -> google.protobuf.Value
	36, // 20: eruun.v1.JobArtifact.expires_at:type_name -> google.protobuf.Timestamp
	36, // 21: eruun.v1.JobArtifact.create_time:type_name -> google.protobuf.Timestamp
	36, // 22: eruun.v1.JobArtifact.update_time:type_name -> google.protobuf.Timestamp
	36, // 23: eruun.v1.JobDelivery.create_time:type_name -> google.protobuf.Timestamp
	36, // 24: eruun.v1.JobDelivery.update_time:type_name -> google.protobuf.Timestamp
	36, // 25: eruun.v1.JobRunnerStatus.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	21, // 26: eruun.v1.JobRunnerStatus.progress:type_name -> eruun.v1.JobRunnerProgress
	22, // 27: eruun.v1.JobRunnerStatus.terminal:type_name -> eruun.v1.JobRunnerTerminal
	36, // 28: eruun.v1.JobSandboxStatus.retain_until:type_name -> google.protobuf.Timestamp
	17, // 29: eruun.v1.JobDetail.accepted:type_name -> eruun.v1.JobAccepted
	16, // 30: eruun.v1.JobDetail.job:type_name -> eruun.v1.JobSpec
	18, // 31: eruun.v1.JobDetail.executions:type_name -> eruun.v1.JobExecution
	19, // 32: eruun.v1.JobDetail.results:type_name -> eruun.v1.JobArtifact
	20, // 33: eruun.v1.JobDetail.deliveries:type_name -> eruun.v1.JobDelivery
	23, // 34: eruun.v1.JobDetail.runner_status:type_name -> eruun.v1.JobRunnerStatus
	24, // 35: eruun.v1.JobDetail.sandboxes:type_name -> eruun.v1.JobSandboxStatus
	19, // 36: eruun.v1.JobResults.artifacts:type_name -> eruun.v1.JobArtifact
	20, // 37: eruun.v1.JobResults.deliveries:type_name -> eruun.v1.JobDelivery
	19, // 38: eruun.v1.JobArtifacts.artifacts:type_name -> eruun.v1.JobArtifact
	28, // 39: eruun.v1.UploadDatasetPart.header:type_name -> eruun.v1.UploadDatasetHeader
	15, // 40: eruun.v1.JobsService.SubmitJob:input_type -> eruun.v1.SubmitJobRequest
	0,  // 41: eruun.v1.JobsService.GetJob:input_type -> eruun.v1.JobTaskRequest
	0,  // 42: eruun.v1.JobsService.CancelJob:input_type -> eruun.v1.JobTaskRequest
	0,  // 43: eruun.v1.JobsService.GetJobResults:input_type -> eruun.v1.JobTaskRequest
	1,  // 44: eruun.v1.JobsService.DownloadJobResult:input_type -> eruun.v1.JobArtifactRequest
	2,  // 45: eruun.v1.JobsService.DownloadJobDelivery:input_type -> eruun.v1.JobDeliveryRequest
	2,  // 46: eruun.v1.JobsService.RetryJobDelivery:input_type -> eruun.v1.JobDeliveryRequest
	4,  // 47: eruun.v1.JobsService.SetJobRetention:input_type -> eruun.v1.SetJobRetentionRequest
	37, // 48: eruun.v1.JobsService.GetJobStoragePolicy:input_type -> google.protobuf.Empty
	32, // 49: eruun.v1.JobsService.SetJobStoragePolicy:input_type -> eruun.v1.JobResultPolicy
	29, // 50: eruun.v1.JobsService.UploadJobDataset:input_type -> eruun.v1.UploadDatasetPart
	5,  // 51: eruun.v1.JobsService.ListJobDatasets:input_type -> eruun.v1.ListJobDatasetsRequest
	3,  // 52: eruun.v1.JobsService.GetJobDataset:input_type -> eruun.v1.JobDatasetRequest
	3,  // 53: eruun.v1.JobsService.DownloadJobDataset:input_type -> eruun.v1.JobDatasetRequest
	17, // 54: eruun.v1.JobsService.SubmitJob:output_type -> eruun.v1.JobAccepted
	25, // 55: eruun.v1.JobsService.GetJob:output_type -> eruun.v1.JobDetail
	37, // 56: eruun.v1.JobsService.CancelJob:output_type -> google.protobuf.Empty
	26, // 57: eruun.v1.JobsService.GetJobResults:output_type -> eruun.v1.JobResults
	30, // 58: eruun.v1.JobsService.DownloadJobResult:output_type -> eruun.v1.ArchiveChunk
	30, // 59: eruun.v1.JobsService.DownloadJobDelivery:output_type -> eruun.v1.ArchiveChunk
	37, // 60: eruun.v1.JobsService.RetryJobDelivery:output_type -> google.protobuf.Empty
	37, // 61: eruun.v1.JobsService.SetJobRetention:output_type -> google.protobuf.Empty
	6,  // 62: eruun.v1.JobsService.GetJobStoragePolicy:output_type -> eruun.v1.JobStoragePolicy
	37, // 63: eruun.v1.JobsService.SetJobStoragePolicy:output_type -> google.protobuf.Empty
	19, // 64: eruun.v1.JobsService.UploadJobDataset:output_type -> eruun.v1.JobArtifact
	27, // 65: eruun.v1.JobsService.ListJobDatasets:output_type -> eruun.v1.JobArtifacts
	19, // 66: eruun.v1.JobsService.GetJobDataset:output_type -> eruun.v1.JobArtifact
	30, // 67: eruun.v1.JobsService.DownloadJobDataset:output_type -> eruun.v1.ArchiveChunk
	54, // [54:68] is the sub-list for method output_type
	40, // [40:54] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_eruun_v1_jobs_proto_init() }
func file_eruun_v1_jobs_proto_init() {
	if File_eruun_v1_jobs_proto != nil {
		return
	}
	file_eruun_v1_applications_proto_init()
	file_eruun_v1_jobs_proto_msgTypes[5].OneofWrappers = []any{}
	file_eruun_v1_jobs_proto_msgTypes[11].OneofWrappers = []any{}
	file_eruun_v1_jobs_proto_msgTypes[18].OneofWrappers = []any{}
	file_eruun_v1_jobs_proto_msgTypes[22].OneofWrappers = []any{}
	file_eruun_v1_jobs_proto_msgTypes[29].OneofWrappers = []any{
		(*UploadDatasetPart_Header)(nil),
		(*UploadDatasetPart_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eruun_v1_jobs_proto_rawDesc), len(file_eruun_v1_jobs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eruun_v1_jobs_proto_goTypes,
		DependencyIndexes: file_eruun_v1_jobs_proto_depIdxs,
		MessageInfos:      file_eruun_v1_jobs_proto_msgTypes,
	}.Build()
	File_eruun_v1_jobs_proto = out.File
	file_eruun_v1_jobs_proto_goTypes = nil
	file_eruun_v1_jobs_proto_depIdxs = nil
}
