// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: eruun/v1/resource_import.proto

package eruunv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceImportScanRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kinds         []string               `protobuf:"bytes,1,rep,name=kinds,proto3" json:"kinds,omitempty"`
	NameRegex     string                 `protobuf:"bytes,2,opt,name=name_regex,json=nameRegex,proto3" json:"name_regex,omitempty"`
	LabelSelector string                 `protobuf:"bytes,3,opt,name=label_selector,json=labelSelector,proto3" json:"label_selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceImportScanRule) Reset() {
	*x = ResourceImportScanRule{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceImportScanRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceImportScanRule) ProtoMessage() {}

func (x *ResourceImportScanRule) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceImportScanRule.ProtoReflect.Descriptor instead.
func (*ResourceImportScanRule) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceImportScanRule) GetKinds() []string {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *ResourceImportScanRule) GetNameRegex() string {
	if x != nil {
		return x.NameRegex
	}
	return ""
}

func (x *ResourceImportScanRule) GetLabelSelector() string {
	if x != nil {
		return x.LabelSelector
	}
	return ""
}

type ResourceImportScanJobRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Namespace     string                    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Rules         []*ResourceImportScanRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceImportScanJobRequest) Reset() {
	*x = ResourceImportScanJobRequest{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceImportScanJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceImportScanJobRequest) ProtoMessage() {}

func (x *ResourceImportScanJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceImportScanJobRequest.ProtoReflect.Descriptor instead.
func (*ResourceImportScanJobRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceImportScanJobRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceImportScanJobRequest) GetRules() []*ResourceImportScanRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ImportNamespaceWorkloadReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportNamespaceWorkloadReference) Reset() {
	*x = ImportNamespaceWorkloadReference{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportNamespaceWorkloadReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportNamespaceWorkloadReference) ProtoMessage() {}

func (x *ImportNamespaceWorkloadReference) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportNamespaceWorkloadReference.ProtoReflect.Descriptor instead.
func (*ImportNamespaceWorkloadReference) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{2}
}

func (x *ImportNamespaceWorkloadReference) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ImportNamespaceWorkloadReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ImportNamespaceWorkloadReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ImportNamespaceComponentMapping struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Name          string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Workload      *ImportNamespaceWorkloadReference `protobuf:"bytes,2,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportNamespaceComponentMapping) Reset() {
	*x = ImportNamespaceComponentMapping{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportNamespaceComponentMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportNamespaceComponentMapping) ProtoMessage() {}

func (x *ImportNamespaceComponentMapping) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportNamespaceComponentMapping.ProtoReflect.Descriptor instead.
func (*ImportNamespaceComponentMapping) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{3}
}

func (x *ImportNamespaceComponentMapping) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImportNamespaceComponentMapping) GetWorkload() *ImportNamespaceWorkloadReference {
	if x != nil {
		return x.Workload
	}
	return nil
}

type ImportNamespaceApplicationMapping struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Name          string                             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Alias         string                             `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	TargetAppId   string                             `protobuf:"bytes,3,opt,name=target_app_id,json=targetAppId,proto3" json:"target_app_id,omitempty"`
	Components    []*ImportNamespaceComponentMapping `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportNamespaceApplicationMapping) Reset() {
	*x = ImportNamespaceApplicationMapping{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportNamespaceApplicationMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportNamespaceApplicationMapping) ProtoMessage() {}

func (x *ImportNamespaceApplicationMapping) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportNamespaceApplicationMapping.ProtoReflect.Descriptor instead.
func (*ImportNamespaceApplicationMapping) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{4}
}

func (x *ImportNamespaceApplicationMapping) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImportNamespaceApplicationMapping) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ImportNamespaceApplicationMapping) GetTargetAppId() string {
	if x != nil {
		return x.TargetAppId
	}
	return ""
}

func (x *ImportNamespaceApplicationMapping) GetComponents() []*ImportNamespaceComponentMapping {
	if x != nil {
		return x.Components
	}
	return nil
}

type ResourceImportManageJobRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	ScanTaskId    string                               `protobuf:"bytes,1,opt,name=scan_task_id,json=scanTaskId,proto3" json:"scan_task_id,omitempty"`
	Applications  []*ImportNamespaceApplicationMapping `protobuf:"bytes,2,rep,name=applications,proto3" json:"applications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceImportManageJobRequest) Reset() {
	*x = ResourceImportManageJobRequest{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceImportManageJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceImportManageJobRequest) ProtoMessage() {}

func (x *ResourceImportManageJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceImportManageJobRequest.ProtoReflect.Descriptor instead.
func (*ResourceImportManageJobRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceImportManageJobRequest) GetScanTaskId() string {
	if x != nil {
		return x.ScanTaskId
	}
	return ""
}

func (x *ResourceImportManageJobRequest) GetApplications() []*ImportNamespaceApplicationMapping {
	if x != nil {
		return x.Applications
	}
	return nil
}

type ResourceImportJobAcceptedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceImportJobAcceptedResponse) Reset() {
	*x = ResourceImportJobAcceptedResponse{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceImportJobAcceptedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceImportJobAcceptedResponse) ProtoMessage() {}

func (x *ResourceImportJobAcceptedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceImportJobAcceptedResponse.ProtoReflect.Descriptor instead.
func (*ResourceImportJobAcceptedResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceImportJobAcceptedResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResourceImportJobAcceptedResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceImportJobAcceptedResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ResourceImportJobIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceImportJobIDRequest) Reset() {
	*x = ResourceImportJobIDRequest{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceImportJobIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceImportJobIDRequest) ProtoMessage() {}

func (x *ResourceImportJobIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceImportJobIDRequest.ProtoReflect.Descriptor instead.
func (*ResourceImportJobIDRequest) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{7}
}

func (x *ResourceImportJobIDRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ResourceImportJobResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TaskId string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type   string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error  string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// The job-specific JSON result is intentionally dynamic.
	Result        *structpb.Value `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceImportJobResponse) Reset() {
	*x = ResourceImportJobResponse{}
	mi := &file_eruun_v1_resource_import_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceImportJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceImportJobResponse) ProtoMessage() {}

func (x *ResourceImportJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eruun_v1_resource_import_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceImportJobResponse.ProtoReflect.Descriptor instead.
func (*ResourceImportJobResponse) Descriptor() ([]byte, []int) {
	return file_eruun_v1_resource_import_proto_rawDescGZIP(), []int{8}
}

func (x *ResourceImportJobResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ResourceImportJobResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceImportJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResourceImportJobResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResourceImportJobResponse) GetResult() *structpb.Value {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_eruun_v1_resource_import_proto protoreflect.FileDescriptor

const file_eruun_v1_resource_import_proto_rawDesc = "" +
	"\n" +
	"\x1eeruun/v1/resource_import.proto\x12\beruun.v1\x1a\x1cgoogle/protobuf/struct.proto\"t\n" +
	"\x16ResourceImportScanRule\x12\x14\n" +
	"\x05kinds\x18\x01 \x03(\tR\x05kinds\x12\x1d\n" +
	"\n" +
	"name_regex\x18\x02 \x01(\tR\tnameRegex\x12%\n" +
	"\x0elabel_selector\x18\x03 \x01(\tR\rlabelSelector\"t\n" +
	"\x1cResourceImportScanJobRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x126\n" +
	"\x05rules\x18\x02 \x03(\v2 .eruun.v1.ResourceImportScanRuleR\x05rules\"k\n" +
	" ImportNamespaceWorkloadReference\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"}\n" +
	"\x1fImportNamespaceComponentMapping\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\bworkload\x18\x02 \x01(\v2*.eruun.v1.ImportNamespaceWorkloadReferenceR\bworkload\"\xbc\x01\n" +
	"!ImportNamespaceApplicationMapping\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05alias\x18\x02 \x01(\tR\x05alias\x12\"\n" +
	"\rtarget_app_id\x18\x03 \x01(\tR\vtargetAppId\x12I\n" +
	"\n" +
	"components\x18\x04 \x03(\v2).eruun.v1.ImportNamespaceComponentMappingR\n" +
	"components\"\x93\x01\n" +
	"\x1eResourceImportManageJobRequest\x12 \n" +
	"\fscan_task_id\x18\x01 \x01(\tR\n" +
	"scanTaskId\x12O\n" +
	"\fapplications\x18\x02 \x03(\v2+.eruun.v1.ImportNamespaceApplicationMappingR\fapplications\"h\n" +
	"!ResourceImportJobAcceptedResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"5\n" +
	"\x1aResourceImportJobIDRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xa6\x01\n" +
	"\x19ResourceImportJobResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12.\n" +
	"\x06result\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\x06result2\xe0\x02\n" +
	"\x15ResourceImportService\x12o\n" +
	"\x18SubmitResourceImportScan\x12&.eruun.v1.ResourceImportScanJobRequest\x1a+.eruun.v1.ResourceImportJobAcceptedResponse\x12s\n" +
	"\x1aSubmitResourceImportManage\x12(.eruun.v1.ResourceImportManageJobRequest\x1a+.eruun.v1.ResourceImportJobAcceptedResponse\x12a\n" +
	"\x14GetResourceImportJob\x12$.eruun.v1.ResourceImportJobIDRequest\x1a#.eruun.v1.ResourceImportJobResponseBIZGgithub.com/PixelCores/Eruun/pkg/apiserver/interfaces/grpc/pb/v1;eruunv1b\x06proto3"

var (
	file_eruun_v1_resource_import_proto_rawDescOnce sync.Once
	file_eruun_v1_resource_import_proto_rawDescData []byte
)

func file_eruun_v1_resource_import_proto_rawDescGZIP() []byte {
	file_eruun_v1_resource_import_proto_rawDescOnce.Do(func() {
		file_eruun_v1_resource_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_eruun_v1_resource_import_proto_rawDesc), len(file_eruun_v1_resource_import_proto_rawDesc)))
	})
	return file_eruun_v1_resource_import_proto_rawDescData
}

var file_eruun_v1_resource_import_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_eruun_v1_resource_import_proto_goTypes = []any{
	(*ResourceImportScanRule)(nil),            // 0: eruun.v1.ResourceImportScanRule
	(*ResourceImportScanJobRequest)(nil),      // 1: eruun.v1.ResourceImportScanJobRequest
	(*ImportNamespaceWorkloadReference)(nil),  // 2: eruun.v1.ImportNamespaceWorkloadReference
	(*ImportNamespaceComponentMapping)(nil),   // 3: eruun.v1.ImportNamespaceComponentMapping
	(*ImportNamespaceApplicationMapping)(nil), // 4: eruun.v1.ImportNamespaceApplicationMapping
	(*ResourceImportManageJobRequest)(nil),    // 5: eruun.v1.ResourceImportManageJobRequest
	(*ResourceImportJobAcceptedResponse)(nil), // 6: eruun.v1.ResourceImportJobAcceptedResponse
	(*ResourceImportJobIDRequest)(nil),        // 7: eruun.v1.ResourceImportJobIDRequest
	(*ResourceImportJobResponse)(nil),         // 8: eruun.v1.ResourceImportJobResponse
	(*structpb.Value)(nil),                    // 9: google.protobuf.Value
}
var file_eruun_v1_resource_import_proto_depIdxs = []int32{
	0, // 0: eruun.v1.ResourceImportScanJobRequest.rules:type_name -> eruun.v1.ResourceImportScanRule
	2, // 1: eruun.v1.ImportNamespaceComponentMapping.workload:type_name -> eruun.v1.ImportNamespaceWorkloadReference
	3, // 2: eruun.v1.ImportNamespaceApplicationMapping.components:type_name -> eruun.v1.ImportNamespaceComponentMapping
	4, // 3: eruun.v1.ResourceImportManageJobRequest.applications:type_name -> eruun.v1.ImportNamespaceApplicationMapping
	9, // 4: eruun.v1.ResourceImportJobResponse.result:type_name -> google.protobuf.Value
	1, // 5: eruun.v1.ResourceImportService.SubmitResourceImportScan:input_type -> eruun.v1.ResourceImportScanJobRequest
	5, // 6: eruun.v1.ResourceImportService.SubmitResourceImportManage:input_type -> eruun.v1.ResourceImportManageJobRequest
	7, // 7: eruun.v1.ResourceImportService.GetResourceImportJob:input_type -> eruun.v1.ResourceImportJobIDRequest
	6, // 8: eruun.v1.ResourceImportService.SubmitResourceImportScan:output_type -> eruun.v1.ResourceImportJobAcceptedResponse
	6, // 9: eruun.v1.ResourceImportService.SubmitResourceImportManage:output_type -> eruun.v1.ResourceImportJobAcceptedResponse
	8, // 10: eruun.v1.ResourceImportService.GetResourceImportJob:output_type -> eruun.v1.ResourceImportJobResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_eruun_v1_resource_import_proto_init() }
func file_eruun_v1_resource_import_proto_init() {
	if File_eruun_v1_resource_import_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_eruun_v1_resource_import_proto_rawDesc), len(file_eruun_v1_resource_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eruun_v1_resource_import_proto_goTypes,
		DependencyIndexes: file_eruun_v1_resource_import_proto_depIdxs,
		MessageInfos:      file_eruun_v1_resource_import_proto_msgTypes,
	}.Build()
	File_eruun_v1_resource_import_proto = out.File
	file_eruun_v1_resource_import_proto_goTypes = nil
	file_eruun_v1_resource_import_proto_depIdxs = nil
}
