// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: eruun/v1/resource_import.proto

package eruunv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceImportService_SubmitResourceImportScan_FullMethodName   = "/eruun.v1.ResourceImportService/SubmitResourceImportScan"
	ResourceImportService_SubmitResourceImportManage_FullMethodName = "/eruun.v1.ResourceImportService/SubmitResourceImportManage"
	ResourceImportService_GetResourceImportJob_FullMethodName       = "/eruun.v1.ResourceImportService/GetResourceImportJob"
)

// ResourceImportServiceClient is the client API for ResourceImportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceImportServiceClient interface {
	SubmitResourceImportScan(ctx context.Context, in *ResourceImportScanJobRequest, opts ...grpc.CallOption) (*ResourceImportJobAcceptedResponse, error)
	SubmitResourceImportManage(ctx context.Context, in *ResourceImportManageJobRequest, opts ...grpc.CallOption) (*ResourceImportJobAcceptedResponse, error)
	GetResourceImportJob(ctx context.Context, in *ResourceImportJobIDRequest, opts ...grpc.CallOption) (*ResourceImportJobResponse, error)
}

type resourceImportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceImportServiceClient(cc grpc.ClientConnInterface) ResourceImportServiceClient {
	return &resourceImportServiceClient{cc}
}

func (c *resourceImportServiceClient) SubmitResourceImportScan(ctx context.Context, in *ResourceImportScanJobRequest, opts ...grpc.CallOption) (*ResourceImportJobAcceptedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceImportJobAcceptedResponse)
	err := c.cc.Invoke(ctx, ResourceImportService_SubmitResourceImportScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceImportServiceClient) SubmitResourceImportManage(ctx context.Context, in *ResourceImportManageJobRequest, opts ...grpc.CallOption) (*ResourceImportJobAcceptedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceImportJobAcceptedResponse)
	err := c.cc.Invoke(ctx, ResourceImportService_SubmitResourceImportManage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceImportServiceClient) GetResourceImportJob(ctx context.Context, in *ResourceImportJobIDRequest, opts ...grpc.CallOption) (*ResourceImportJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceImportJobResponse)
	err := c.cc.Invoke(ctx, ResourceImportService_GetResourceImportJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceImportServiceServer is the server API for ResourceImportService service.
// All implementations must embed UnimplementedResourceImportServiceServer
// for forward compatibility.
type ResourceImportServiceServer interface {
	SubmitResourceImportScan(context.Context, *ResourceImportScanJobRequest) (*ResourceImportJobAcceptedResponse, error)
	SubmitResourceImportManage(context.Context, *ResourceImportManageJobRequest) (*ResourceImportJobAcceptedResponse, error)
	GetResourceImportJob(context.Context, *ResourceImportJobIDRequest) (*ResourceImportJobResponse, error)
	mustEmbedUnimplementedResourceImportServiceServer()
}

// UnimplementedResourceImportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceImportServiceServer struct{}

func (UnimplementedResourceImportServiceServer) SubmitResourceImportScan(context.Context, *ResourceImportScanJobRequest) (*ResourceImportJobAcceptedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResourceImportScan not implemented")
}
func (UnimplementedResourceImportServiceServer) SubmitResourceImportManage(context.Context, *ResourceImportManageJobRequest) (*ResourceImportJobAcceptedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResourceImportManage not implemented")
}
func (UnimplementedResourceImportServiceServer) GetResourceImportJob(context.Context, *ResourceImportJobIDRequest) (*ResourceImportJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResourceImportJob not implemented")
}
func (UnimplementedResourceImportServiceServer) mustEmbedUnimplementedResourceImportServiceServer() {}
func (UnimplementedResourceImportServiceServer) testEmbeddedByValue()                               {}

// UnsafeResourceImportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceImportServiceServer will
// result in compilation errors.
type UnsafeResourceImportServiceServer interface {
	mustEmbedUnimplementedResourceImportServiceServer()
}

func RegisterResourceImportServiceServer(s grpc.ServiceRegistrar, srv ResourceImportServiceServer) {
	// If the following call panics, it indicates UnimplementedResourceImportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceImportService_ServiceDesc, srv)
}

func _ResourceImportService_SubmitResourceImportScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceImportScanJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceImportServiceServer).SubmitResourceImportScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceImportService_SubmitResourceImportScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceImportServiceServer).SubmitResourceImportScan(ctx, req.(*ResourceImportScanJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceImportService_SubmitResourceImportManage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceImportManageJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceImportServiceServer).SubmitResourceImportManage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceImportService_SubmitResourceImportManage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceImportServiceServer).SubmitResourceImportManage(ctx, req.(*ResourceImportManageJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceImportService_GetResourceImportJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourceImportJobIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceImportServiceServer).GetResourceImportJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceImportService_GetResourceImportJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceImportServiceServer).GetResourceImportJob(ctx, req.(*ResourceImportJobIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceImportService_ServiceDesc is the grpc.ServiceDesc for ResourceImportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceImportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eruun.v1.ResourceImportService",
	HandlerType: (*ResourceImportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitResourceImportScan",
			Handler:    _ResourceImportService_SubmitResourceImportScan_Handler,
		},
		{
			MethodName: "SubmitResourceImportManage",
			Handler:    _ResourceImportService_SubmitResourceImportManage_Handler,
		},
		{
			MethodName: "GetResourceImportJob",
			Handler:    _ResourceImportService_GetResourceImportJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eruun/v1/resource_import.proto",
}
